### ISSUE TITLE
Thermo GAV Behavior

### ISSUE THREAD

**Issue by rgillis8** [ReactionMechanismGenerator/RMG-Py#1004]
I have been working on expanding our GAV system to handle oxygenated sulfur compounds. As I have done this I have noticed some strange (and in my opinion non-ideal) behavior.

I had always understood that if there was not an exact match to a group, then the GAV value used to estimate the thermo would correspond to the most specific node that matches the group. I had thought that if this node didn't have it's own values then it would average the thermo GAV values for its "children." 

However, this is not the case. Generally, if one of the most specific nodes does not match the group being examined then some default GAV is selected. Consider the following example...
![image](https://cloud.githubusercontent.com/assets/17207564/25390711/510d1d3e-29a2-11e7-8316-f103e74800a1.png)

The GAV values corresponding to this molecule are...
Thermo group additivity estimation: group(Cs-CsCsCsCs) + gauche(Cs(RRRR)) + other(R) + group(Os-CsH) + gauche(Os(CsR)) + other(R) + group(Os-CsH) + gauche(Os(CsR)) + other(R) + group(Ss-CsH) + gauche(Ss(CsH)) + other(R) + group(Os-CsH) + gauche(Os(CsR)) + other(R)

Note that the central carbon is represented by the Cs-CsCsCsCs group. This is the "default" group selected by the parent "Cs" node. I think it would be better if (similar to the kinetics estimation) an average of closest matches was used to estimate this value.

**Comment by nyee** [comment]
Thermo GAVs don't do any kind of averaging by default. The only partial exception is the heuristics designed for polycyclic corrections (and even that is not averaging children). 

Right now, almost every entry has either a data value or a pointer, which just directs that node to use a different group. I'm not sure if this method or an average is better, given that averages depend very strongly on tree structure. My instinct says that it is probably worth our time to just have sensible groups rather than try to rely on averages in thermo, because it is both more important to get right and less combinatorial than kinetics. 

In the kinetics it is necessary to do an average because it is infeasible to have every combination of entry hard-coded to point towards something sensible.

**Comment by rwest** [comment]
I think I agree with @nyee. If you are concerned that the "C" node uses the value for "Cs-CsCsCsCs" and think you have a better value for the "C" node (eg some average) just put that better value in there. And ideally demonstrate that some test set of estimated thermo values get better.  But how you would choose to weight your average, I'm not sure.

**Comment by rgillis8** [comment]
I see. As Nathan says if the groups are specific and extensive enough then it is not a problem. 

I would say that as RMG expands atom types it might be worthwhile to think about a place for averaging in thermo estimation. With carbon and oxygen I can see that it is probably better in the current implementation, but I don't think that we will be able to have reasonable values or pointers for every combination of sulfur, oxygen, nitrogen, and carbon.
