### ISSUE TITLE
O2 singlet forms during model generation (although allowSingletO2 is set to False)

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#1020]
`allowSingletO2` is [only checked once](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/ac6406485e8cf9eebac54e2313f8ef3ff1044ece/rmgpy/rmg/main.py#L452) in RMG, and not every time a species is generated.

In my nitrogen system an N2O2 species (`O(N=[N])[O]`) was generated, and it reacts through the 1,4_Linear_birad_scission family, forming N2 and a singlet O2.

As a temp fix, I'll forbid N2O2 in this family. However, we might want to consider checking for the singlet O2 on species generation.

**Comment by nyee** [comment]
The main reason for `allowSingletO2`, was just so that users did not accidentally input the wrong `O=O` instead of `[O][O]`. If a hypothetical family actually creates `O=O`, then the intent was for RMG to still allow its creation. In that regard `allowSingletO2` might be poorly named, because it seems to imply `O=O` is never allowed.

More practically, RMG probably lacks the thermo and kinetics to handle `O=O` because it is a weird excited state, and would mostly create junk if it were ever introduced. Here are three possible solutions (ranked from most to least scientifically correct IMO):

1. Add the thermo of singlet `O=O` to primary thermo library if it is available in literature. Maybe this will be enough to deter RMG from choosing reactions that create this species.
2. Continue to forbid singlet `O=O` from families on a case-by-case basis
3. Globally forbid singlet `O=O`. I'm not sure if anybody ever actually uses it in any models right now anyway. If we do this, we should probably refactor how we have implemented `allowSingletO2` option.

**Comment by alongd** [comment]
Closed (as far as I'm concerned) via https://github.com/ReactionMechanismGenerator/RMG-database/pull/239 bu adding the `Singlet_Val6_to_triplet` family
