### ISSUE TITLE
Non-deterministic thermo for polycyclics

### ISSUE THREAD

**Issue by nyee** [ReactionMechanismGenerator/RMG-Py#1027]
As referenced in #638, #639, the getSmallestSetOfSmallestRings has non-deterministic results which will often result in non-deterministic thermo with the new polycyclic heuristic.

If you try running this code-snippet:
```
from rmgpy.data.rmg import RMGDatabase
from rmgpy import settings
from rmgpy.species import Species

smiles = "CC1CC12C1C3CC1C32"
spec_in = Species().fromSMILES(smiles)

database = RMGDatabase()

database.load(settings['database.directory'], thermoLibraries=[],\
             kineticsFamilies='none', kineticsDepositories='none', reactionLibraries = [])
thermoDatabase = database.thermo

print("When molecule created multiple times")
for i in range(5):
    spec_in = Species().fromSMILES(smiles)
    thermo_gav = thermoDatabase.getThermoDataFromGroups(spec_in)
    print(thermo_gav.comment)

print("\n\n")
    
print("When molecule created once:")
spec_in = Species().fromSMILES(smiles)
for i in range(5):
    thermo_gav = thermoDatabase.getThermoDataFromGroups(spec_in)
    print(thermo_gav.comment)
```

The first loop can give two different results (differences highlighter)

Thermo group additivity estimation: group(Cs-CsCsCsCs) + other(R) + group(Cs-CsCsCsH) + other(R) + group(Cs-CsCsCsH) + other(R) + group(Cs-CsCsCsH) + other(R) + group(Cs-CsCsCsH) + other(R) + group(Cs-CsCsCsH) + other(R) + group(Cs-CsCsHH) + other(R) + group(Cs-CsCsHH) + other(R) + group(Cs-CsHHH) + other(R) + polycyclic(s1_3_4_ane) + **polycyclic(s2_4_4_ane) + polycyclic(s2_4_4_ane) + polycyclic(s3_4_4_ane)** - ring(Cyclobutane) - ring(Cyclobutane) - ring(Cyclobutane) - ring(Cyclobutane)

Thermo group additivity estimation: group(Cs-CsCsCsCs) + other(R) + group(Cs-CsCsCsH) + other(R) + group(Cs-CsCsCsH) + other(R) + group(Cs-CsCsCsH) + other(R) + group(Cs-CsCsCsH) + other(R) + group(Cs-CsCsCsH) + other(R) + group(Cs-CsCsHH) + other(R) + group(Cs-CsCsHH) + other(R) + group(Cs-CsHHH) + other(R) + **polycyclic(s3_4_4_ane) + polycyclic(s2_4_4_ane) + polycyclic(s3_4_4_ane)** + polycyclic(s1_3_4_ane) - ring(Cyclobutane) - ring(Cyclobutane) - ring(Cyclobutane) - ring(Cyclobutane)

On the other hand, the second loop will pick one of the two above and always give the same one. This implies that if a molecule object is already created, then getSSSR and polycyclic thermo will give the same result for that object. However, if a new object is created, then do not expect to get the same results. I also tried the same code but replacing  `fromSMILES()` with `fromAdjacencyList()` and got the same results, so it is not dependent on what method is used to create the molecule.

**Comment by mliu49** [comment]
I think this is slightly different from #638. In that case, there was a clear SSSR, but the method was returning a wrong one. In your case, there are multiple possible SSSR because of the bridged 4-member rings, and the set which is returned is non-deterministic.

@KEHANG did some work with trying to make the SSSR more deterministic, but I don't think it covered cases like this. I'm currently working on implementing deterministic ring finding methods which can hopefully be applied here as well.

One option is the largest set of smallest rings which gives all of the smallest rings including linearly dependent ones. For your example, it would return 6 rings (1 x 3-membered + 5 x 4-membered). Another option is the complete set of elementary rings, which would give the same result for your example, but would give 6 (2 x 5-membered, 1 x 6-membered, 2 x 7-membered, 1 x 8-membered) rings for the example in #638.

I think either of these will give more complete information compared to the SSSR, but both would require restructuring the polycyclic algorithm and possible refitting the group values.
