### ISSUE TITLE
Does RMG comes with built-in features for converting Chemkin mechanism reactions to SMILES or SMARTS formats?

### ISSUE THREAD

**Issue by leosfan** [ReactionMechanismGenerator/RMG-Py#1029]
I'm lost when trying to read chemkin mechanism files into RMG, and then use RMG to convert mechanism files to SMILES reaction. From the user guide, it seems doable because RMG needs to read chemkin reactions in a machine-friendly style. I wonder if I can do the same. However, so far I'm not very successful. Does anyone know how to make this happen?

**Comment by alongd** [comment]
Hi @leosfan ,
Principally Chemkin files contain strings to represent species, and without a proper dictionary RMG cannot determine what the user meant (e.g., what is meant by `H15DE25DM-S`??)
Since RMG won't read Chemkin files as libraries, you should first convert your Chemkin file into proper RMG libraries (kinetics + thermo), and then you can either let RMG choose species and reactions from it, or seed it. For that you can either use the standalone script [ImportChemkinLibrary](https://github.com/ReactionMechanismGenerator/RMG-database/blob/master/scripts/importChemkinLibrary.py) (where youll have to also manually supply an AdjList dictionary), or use the [Importer tool](https://github.com/rwest/RMG-Py/tree/importer) that could also help you guess which string represents what species using RMG's rate and kinetic estimations.

**Comment by leosfan** [comment]
Thanks for the help! @alongd 
Does this mean that the seed mechanisms in RMG kinetic libraries can be converted to SMILES format? In addition, are those mechanisms open-source data as long as they are cited properly?

**Comment by alongd** [comment]
All libraries in RMG (including ones that you intend to use as seeds) must have dictionaries [like this one](https://github.com/ReactionMechanismGenerator/RMG-database/blob/master/input/kinetics/libraries/BurkeH2O2inArHe/dictionary.txt) which are in an [Adjacency List](http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/species.html) format.
I don't think we use SMILES in our libraries. You may convert a single species' SMILES into the RMG-format AdjList on our [website](http://rmg.mit.edu/molecule_search).

Yes, the mechanisms in our database (or literature) are free to use, and should be cited properly as you mentioned.
