### ISSUE TITLE
aromatic molecules in thermo lib not treated as aromatic

### ISSUE THREAD

**Issue by dyu2017** [ReactionMechanismGenerator/RMG-Py#1032]
I found that when added  a thermo lib, the benzene bonds in the aromatic molecules in the thermo lib are treated as either a single or double bond, not as aromatic bonds.
This can create issues when determining the rate rules for reactions.
Is there any way to fix this?

**Comment by dyu2017** [comment]
Thanks. It worked.

**Comment by dyu2017** [comment]
It looks like the same thing happened for some aromatic molecules calculated with QMTP. The aromatic bonds on those molecules are no longer recognized as benzene bonds.

**Comment by mliu49** [comment]
That's probably because QMTP will calculate the thermo for the first structure in `Species.molecule, which will never be the aromatic structure to start with. Currently, it is not possible to reorder resonance structures by default because it would cause other issues. However, it is something that is planned.
