### ISSUE TITLE
There is an error with thermo.py file, whenever I try to create a reaction mechanism.

### ISSUE THREAD

**Issue by stormblessed** [ReactionMechanismGenerator/RMG-Py#1044]
Whenever I try to generate a reaction mechanism using cmd there is an error. Mechanism generation starts fine but after some time there is en error showing "**line, 1640 in______addGroupThermoData
data.comment = '{0}({1})'.format(database.label, comment)
AttributeError: 'NoneType' object has no attribute 'comment**'    "
![error](https://user-images.githubusercontent.com/29142726/26980870-af9056c8-4d33-11e7-9740-0a0230eb4665.PNG)

**Comment by alongd** [comment]
Could you upload your input file so we can try reproducing the error?

**Comment by stormblessed** [comment]
sure, I'm converting .py to docx.
[furfural.docx](https://github.com/ReactionMechanismGenerator/RMG-Py/files/1064411/furfural.docx)

**Comment by amarkpayne** [comment]
I am running your input file now to see what happens. How many species were added to the model before it crashed? Also, see what happens if you add 'primaryThermoLibrary' to your input file after GRI-Mech3.0.

**Comment by amarkpayne** [comment]
My RMG job for this is still running after 30 species. I had to append the primaryThermoLibrary to my input file to get it to not throw an error for Ne, but after that I did not run into any issues. It is possible that this is the issue you were running into. If you weren't able to get to 30 species, even with adding the primaryThermoLibrary then perhaps this is a issue with Windows that needs to be addressed (I ran my job on Linux).

**Comment by stormblessed** [comment]
The problem is still there, this time I ran RMG using primaryThermoLibrary
as well but after some time the error appears.

**Comment by stormblessed** [comment]
The problem is still there, this time I ran RMG using primaryThermoLibrary as well but after some time the error appears. Is there possibility of error in **thermo.py** file?
![error_1](https://user-images.githubusercontent.com/29142726/27028630-a2af5ede-4f65-11e7-8977-916e03cf9db4.PNG)

**Comment by amarkpayne** [comment]
This is an interesting problem because using your input file and primaryThermoLibrary I was able to get to at least 30 species before I stopped the job on my Linux machine, so I don't think it is strictly speaking a problem with thermo.py. Perhaps there is an error in the version of the database you are using (How did you install RMG? If you cloned the database from the github for RMG-database have you updated it recently?), or maybe this is a bug that is specific to Windows (I am going to try to run your input file in windows and see what happens).

One final thing to try if you can would be to run RMG in debug mode by using the `-d` flag when you start your RMG job on the command line. Hopefully this will tell us which molecule it was trying to generate thermo for, which might hint at the problem.

**Comment by stormblessed** [comment]
Ok, can you tell me how to update that database.

**Comment by amarkpayne** [comment]
Assuming you cloned your database from the RMG-database github:

1) Open a command prompt and navigate to your RMG-database directory
2) Type `git fetch`
3) Type `git rebase`

**Comment by mjohnson541** [comment]
This looks like it may be related to #880
