### ISSUE TITLE
Default installation of rmg-py did not create some of the files in RMG-Py (including rmg.py)

### ISSUE THREAD

**Issue by monorinam** [ReactionMechanismGenerator/RMG-Py#1087]
Installed on Mac OS X 10.12.5, with anaconda for python 2. Some files were missing from the folder when I used 'conda create -c rmg --name rmg_env rmg rmgdatabase' (instructions here: https://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaUser.html)

I deleted the environment and compiled from source, that seemed to fix the issue of missing files.

**Comment by amarkpayne** [comment]
I tried running this installation on Ubuntu 16.04, and it appeared to work for this OS. My `anaconda2/envs/install_issue/bin/` folder contained the rmg.py file (I named my environment "install_issue" so as to not interfere with my personal rmg_env). Since you were able to install by source successfully I'll go ahead and close out this issue, but if someone experiences this issue in the future perhaps we need to test this installation on Mac OS X 10.12.5.
