### ISSUE TITLE
Semi-duplicate code for reading kinetics comments

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-Py#1096]
There are two methods that parse the chemkin kinetics's comments. To the best of my knowledge one of the files is used in `loadChemkinFile` and the other one is for Connie's uncertainty analysis.

loading chemkin file | uncertainty analysis
-------------------------|--------------------------
method `readReactionComments` in chemkin.py | `extractSourceFromComments` in family.py
no database necessary | requires database
returns template_label | finds list of original rule entries and their weights
works for LibraryReactions & Template Reactions | only works for TemplateReactions
input is a string from chemkin file | input is a reaction object, of which it parses `rxn.kinetics.comment`
applies attributes (like degeneracy) to a new reaction object | does not modify the reaction object with the attributes

Anyways, it seems like these two methods have different purposes, dependencies, and methodologies. At the same time, it is poor coding practice to replicate reading a string. For example, adding an extra line in the comments will break `extractSourceFromComments` but not `readReactionComments`, as seen in #1094. 

Maybe it would be better to have Reaction objects use a method to read in and be able to write their own kinetics comments. At the same time, we could improve comments so that a fully built database is not needed to fully parse the comments for uncertainty analysis. Maybe I'm just living in ideal fantasy.

**Comment by goldmanm** [comment]
It seems possible to utilize the expanded chemkin reading in #1076 to avoid all almost all parsing in `extractSourceFromComments`. This would also avoid dangerous commands like `reaction.kinetics.comment.replace('\n', ' ')` which likely help caused an issue in #1094.

**Comment by goldmanm** [comment]
This would leave `extractSourceFromComments` to just have the following commands:

```
[get trainingReaction if exact match found there, otherwise]
if 'Exact match' in comments:
    exact = True
template = self.retrieveTemplate(rxn.template)
self.getSourcesForTemplate(template)
```

also, maybe changing the name of methods 'extractSourceFromComments' to 'getReactionSourceInfo', since for LibraryReaction and PDepReaction, it doesn't even look at comments (and possibly it mostly won't be searching comments for TemplateReaction either)

**Comment by mjohnson541** [comment]
I'm going to make the controversial statement that I don't really understand why we should have to parse anything at all in these sort of process.  Why are we encoding information into strings rather than just storing the information in the object?  And why do we primarily read information in through chemkin files that have specific restrictions rather than output library/seed mechanism files (#1093) whose format we entirely control and that are comparatively easy for us to read in?

**Comment by goldmanm** [comment]
I completely agree that that would be the better path. If we want to remove the need for comments, while keeping the same functionality, we may need someway to store these attributes for when dealing with the uncertainty module ( I don't think these need to be output to the seed mechanism)

* The training reaction that the source came from (if it was taken from training reaction)
* The averages of which rate rules which led to this rate
* The source of the rate rule

Another advantage to not needing comments would be a memory saving. As noted before, having verbose commenting leads to significant memory increase, and that is just due to more strings.

**Comment by mjohnson541** [comment]
I think it would actually be preferable to determine the uncertainties of thermo/rate coefficients on the fly and just keep it attached to the reaction rather than having to look it up afterwards (which I think may not even be possible if the database has changed significantly?).  Ideally I think the rest of uncertainty could just read in the uncertainties from a seed mechanism.  Although that may be more trouble than it's worth.

**Comment by goldmanm** [comment]
To my understanding, the uncertainty module:

1. reads the template from chemkin file (don't think it needs to be verbose)
2. reruns the generate kinetics of that template ('on the fly')
3. generate kinetics saves the information in kinetics.comment (using the verbose setting, which is what would be printed in the chemkin file)
4. parses kinetics.comment info to build the uncertainties.

So it is doing both 'on the fly' and 'looking it up afterwards'.

**Comment by goldmanm** [comment]
We'd also have to expand the seed mechanism capabilities (to store TemplateReactions with adequate information), not to mention fixing the uncertainty parsing mess, if we need would like to move away from parsing the chemkin file (which would be lovely not to parse those comments anymore).

**Comment by mjohnson541** [comment]
So actually I was wrong, we theoretically have all of the template information in the seed mechanism, it's all in the kinetics comment and the descriptions.  But that doesn't get us much farther so I was thinking in terms of attributes added to kinetics objects:  

boolean exactMatch (is it an exact match)
list match (the tree node it hit on)
list averagedTemplates (list of templates averaged to get kinetics for match (empty if exactMatch)
float euclideanDistance 
float reactionPathDegeneracy

Am I missing anything?

**Comment by goldmanm** [comment]
For reactions that come for depositories (like training reactions), we want the index of the training reaction, possibly -1 if not from a training reaction.

**Comment by mjohnson541** [comment]
Oh actually now that you remind me I think we forgot the most important:  
string family

**Comment by goldmanm** [comment]
I think some of this is stored at the `TemplateReaction` level. For example, `family`, `template`, and  `degeneracy` are already attributes of `TemplateReaction`. I think it would be preferable to store that information at the Reaction level object if possible. This would likely require allowing Template Reactions in seed mechanisms.

The boundary between kinetics and reactions is a little blurry, but I think avoiding duplicate information in reaction and kinetics is a good practice to have.

**Comment by mjohnson541** [comment]
The problem is that when these kinetics decisions are made the reaction object isn't present, which means that in order to do that we either have to parse the comments after the kinetics object returns to the reaction or we have to rewrite how we do kinetics estimation so that the reaction object is present.

**Comment by mjohnson541** [comment]
Oh wait never mind that isn't an issue.

**Comment by mliu49** [comment]
This completely passed under my radar, so apologies for being so late to the conversation. The uncertainty module reloads the entire database because it needs verbose averaging info (enabled via verboseComments in the options block) to determine all the rate rules used.

It seems to me like the uncertainty module really just needs the original template, after which it can use the loaded database to retrieve the necessary information. I do think that loading the database is still necessary for the current state of the algorithm. If we do switch to saving the uncertainties during model generation, we could potentially eliminate some of that. However, the uncertainty module also does correlated uncertainty, which will probably still need the full database to be loaded, with all rate rule info.
