### ISSUE TITLE
Upgrade isomorphism check algorithm

### ISSUE THREAD

**Issue by KEHANG** [ReactionMechanismGenerator/RMG-Py#1098]
As you may know, RMG uses `VF2` algorithm to check molecular graph isomorphism. Thanks @rwest for sharing the info that a new version [`VF3`](http://mivia.unisa.it/datasets/graph-database/vf3-library/) just came up, whose author claimed it on average improve time performance by at least 2 orders of magnitude.

It's a good opportunity to speed up RMG by upgrading to `VF3`. But before doing that, we might want to 

- [ ] check how much percent of time is used for isomorphism check for large applications like PDD, surrogate pyrolysis (I guess it'd be a big number)

- [ ] create a big list of molecules for time performance comparison testing (my concern would be `VF3` works much better on large graphs, but not necessarily on graphs that RMG generates, but let's see)

**Comment by amarkpayne** [comment]
I am currently profiling surrogate pyrolysis runs, so I'll post the results as soon as I have them.

**Comment by mliu49** [comment]
So VF3 is actually a C++ package, so in order to use it, we would likely need to write some sort of wrapper. Depending on how straightforward that is, we probably won't see as much of the speedup benefit.

**Comment by rwest** [comment]
My impression at the time of first discovering VF3 was they claimed the algorithm itself was much faster, not just the implementation. But I've but looked into it

**Comment by mliu49** [comment]
Right, the algorithm supposedly is faster, but if for example, the overhead of interfacing with their program were to be an order of magnitude greater, then it wouldn't matter that it's faster.

From what I can tell, the package that they provide loads the input from a file and prints the output. That's surely not going to work for us, but I don't know enough about C/C++ to say exactly how we could interface between RMG graphs and this library.

Btw, this came up again during an RMG subgroup meeting since we found that forbidden structure checking was taking ~2/3 of typical runtime.

**Comment by rwest** [comment]
I guess my point was that we could re-implement their algorithm in our own code (if it is worth it).
