### ISSUE TITLE
avoid circular dependencies with separate file for RMG-specific exceptions

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-Py#1101]
I came across a circular dependency when trying to implement `KineticsError` in arrhenius.pyx. Importing KineticsError required importing all import statements in `kinetics.data.common.py` which imported `reaction.py` which then tried to import objects from `arrhenius.pyx`. 

Not being able to use `KineticsError` in classes descending from `KineticsData` is not intuitive nor functional. 

To avoid this, and other, circular imports, maybe grouping all exceptions in a separate file `rmgpy.exceptions.py` which doesn't require any imports. This could also add descriptions for when and where these Exceptions should be used. Any thoughts on this? Any potentially better organizational strategies?

Mark

**Comment by amarkpayne** [comment]
I think this makes a lot of sense.  Is there a way that this can be done without having to modify all the references to KineticsError in all of RMG?

**Comment by goldmanm** [comment]
I think it would require changing the import statements from `from rmgpy.data.kinetics.common import KineticsError` to `from rmgpy.exceptions import KineticsError` in each file that utilizes the error. I'd likely also want to do this for all the dozen or so exceptions: `UndeterminableKineticsError`, `ThermoError`, `SolverError`, etc. 

It's not an easy task to reorder. Which is why I posted this issue to get some feedback before trying to take on the challenge.

**Comment by amarkpayne** [comment]
Could you create a file `rmgpy.exceptions` to place all the exceptions in, and instead of changing every single reference in RMG simply go to `rmgpy.data.kinetics.common` and define the `KineticsError` class there to inherent from the `KineticsError` class defined in `rmgpy.exceptions`? That way:

1) New references can reference `KineticsError` from `rmgpy.exceptions`.
2) All old references to `KineticsError` from `rmgpy.data.kinetics.common` will still work, without any modification needed.
3) Any future changes to `KineticsError` will happen in one place.

Would this work?

**Comment by goldmanm** [comment]
I think that's an ingenious workaround to avoid changing all import statements.

**Comment by mjohnson541** [comment]
closed with #1106
