### ISSUE TITLE
Ran into some interesting code 

### ISSUE THREAD

**Issue by KEHANG** [ReactionMechanismGenerator/RMG-Py#1167]
Just saw some interesting lines of code probably due to fast development and merge. Anyone who spots those kinda of code on master please put them in this issue. Meanwhile we are going to setup some rules for rigorous quality control and merge. Any suggestions/comments on how to prevent those are welcome.

- [x] double returns (line 1688 and 1689) https://github.com/ReactionMechanismGenerator/RMG-Py/blob/c8133da8aed5d3e74f97bee46d5612979bf67d2a/rmgpy/data/thermo.py#L1689

**Comment by mliu49** [comment]
I've been thinking that we need more rigorous code checking requirements. I think that taking this step would definitely help our code quality and also reduce the workload for reviewers. I looked into apps with GitHub integration, and found Codacy, which does automatic code reviews. You can see the review for the current master branch [here](https://www.codacy.com/app/mjliu/RMG-Py/dashboard). I'm not sure whether or not this will be helpful, since there are a lot of things that it does not seem to catch. For example, it didn't catch the error you mentioned (although PyCharm did flag it for me).

**Comment by mjohnson541** [comment]
I think right now the Codacy output is more confusing to pull request writers than it is helpful.  It doesn't pick up many things we'd like it to and it picks up a bunch of issues we aren't very concerned about and some (particularly security ones) that one would not expect a pull request writer to fix.  I think it is incredibly confusing for non-developers and for developers what help it provides is buried underneath a bunch of less important issues.  

If there is some way we can turn off the less important things it picks up I think we should do that, but otherwise I think we should put off using Codacy until we fix the issues it has with master.

**Comment by mliu49** [comment]
Right now, we're just testing out Codacy to see whether or not it's useful. You can still merge without Codacy passing. Also, pull requests are analyzed based on the changes that are made, so the countless issues identified with the current master don't really matter. For Python, Codacy runs Bandit and PyLint. Both can be configured to choose exactly which items you want it to flag. If we decide that we don't care about security issues, then we can turn those off.

I was originally going to suggest having people run PyLint locally before I found out that there are automatic code reviewers. I definitely think it's something we need, but we we can decide whether or not Codacy is the right tool for us. This is partially motivated by [Google's Python style guide](https://google.github.io/styleguide/pyguide.html?showone=Lint#Lint).

**Comment by mjohnson541** [comment]
Actually, I'm exactly sure how it decides, but in the proper seed mechanisms PR it is getting upset about exec statements that weren't changed in the PR.

**Comment by mjohnson541** [comment]
Never mind, it's working as expected.

**Comment by amarkpayne** [comment]
Fixed with #1168 now merged.
