### ISSUE TITLE
Treatment of bugfix PR

### ISSUE THREAD

**Issue by mjohnson541** [ReactionMechanismGenerator/RMG-Py#1202]
After getting an email from @chiyw13 about the best way to deal with issue #1157 I noticed that we have a number of stale bugfix PR's:  #1171, #1170 and #1165.  #1171 and #1170 fix job breaking bugs and #1165 fixes bugs in the uncertainties module.  However, it also occurs to me that we may have as many bugfixes packaged into large pull PR's.  I think it might be worthwhile for us to put together additional guidelines for how we treat bugfix PR's.  

Since these bugs waste users' and our time I think it's worth our time to keep the master branch particularly bug free.  

As @goldmanm pointed out in #1170 a very important first step is making bugfixes separate from other PR's when at all possible.  I really really don't mean to single anyone out, especially because I'm guilty of these things as well, but clearly based on what happened to particularly #1170 and #1171, but also #1165, which are about three weeks old and whose commits are all about a month old, that doesn't seem to be enough.  I understand people are busy and the need to maintain a strict review process, but I don't think either of those excuses the length of time it is taking us to push bugfixes to the master branch.  

I think we need to add guidelines that will prioritize these PR's and allow us to review them efficiently.  I think it may be optimal to shift some responsibility for these PR's from the author to the developers as a whole.  We also might want to properly define what is and what isn't a bugfix PR.  As @goldmanm suggested I think we should also have a policy about putting bugfixes in separate pull requests when at all possible.

**Comment by mliu49** [comment]
I think part of it is due to lag time between reviewing/followup. For important bug fixes that should be merged soon, the author should communicate with the reviewer and try to get it through the review process as quickly as is reasonable.

For #1171, there were multiple cycles of comments/changes, and the PR is now out of date due to other ones being merged. If it gets rebased, I think it can be merged right away.

For #1170, I commented that it fixes issues that are only issues on the `only_core_degeneracy` branch. Since that branch introduces the issues, I think the fixes should stay in the same branch. There's no point in merging a fix for a non-issue into master.

#1165 should definitely be reviewed and merged. I think the holdup there may be that nobody wants to deal with uncertainty, and additional testing would be best to make sure that the fixes work.

**Comment by mjohnson541** [comment]
I've actually ran into the degeneracy calculation error #1170 fixes on master and I ported commits from that branch to fix it.  Perhaps I should have posted that, I thought since that pull request was up and framed as a bugfix that that was known.

**Comment by amarkpayne** [comment]
For #1170, I think this PR is waiting on some profiling comparisons between this and the branch `degeneracy_speedup` (as well as master). These tests were ran for 7 days, and are finishing up as we speak, though I won't have a comparison for master until the end of the week (my first attempt error-ed out).

This should move the process along for #1170, and I'll add my review for #1165 by tomorrow evening.

**Comment by mjohnson541** [comment]
Why does #1170 need profiled on job that takes 7 days?  It doesn't involve any time intensive code and it doesn't even fix a speed related issue.

**Comment by amarkpayne** [comment]
Sorry, my mistake. The profiling is for the other pull request related to this branch.
