### ISSUE TITLE
Mechanism Size vs Temperature, no pattern in size

### ISSUE THREAD

**Issue by DetlevCM** [ReactionMechanismGenerator/RMG-Py#1237]
So, another weird observation...

I am looking into creating a pyrolysis mechanism in RMG. Besides the mechanism itself, temperature as well as pressure sensitivity are also of interest, both in RMG and the final mechanism.
And here is where it gets weird... - Apart from a single parameter, either pressure or temperature, all other parameters are unchanged.

The only mechanism to finish so far (RAM issue, especially with multiple jobs) has been at 500C or 773.15K.
The mechanism generation process doesn't seem to be influenced by pressure at all - but OK, why not. 

Now it gets weird:
Both 300C and 1000C or 573.15K and 1273K will produce bigger (!!) mechanisms - by at least a factor of two with regards to the core species. Yes, there is high and low temperature thermo, but it shouldn't result in an in between mechanism being the smallest of "the lot".

Would you have any explanation for this behaviour?

**Comment by mjohnson541** [comment]
If you aren't using pressure dependence or any libraries that have pressure dependent reactions the rates produced are all high pressure limit and thus will not be dependent on pressure.  If the pressure dependent reactions are unimportant or their variations don't affect the pathway choice the mechanism generation would also not be influenced by pressure.  

It's hard to say without knowing exactly what system you are modeling what tolerances you used.  Usually I would take that as a sign that the in between temperature mechanism did not develop properly.  Most commonly this is because some stable intermediate was added to the model, but its decay pathway was not.  You can check that by generating species profiles under the reactor conditions (either using our simulate script or other software).  If that is the problem you can usually solve it by either running the model again at tighter tolerances or by running the species that didn't breakdown in it's own RMG job and merging it with the original model.

**Comment by DetlevCM** [comment]
I'm not too surprised about the lac of pressure dependence - as I am only using the standard kinetic families and no libraries.

As to the second point:
Indeed, the 500C mechanism is incomplete - or must be, when one looks at the 300C and 1000C mechanisms. 
What I do not understand, is how an in between temperature can have a problem.
If anything, I would normally expect a low temperature mechanism to not go to completion, for example due to low reaction rates and thus low species fluxes.
Incidentally, the 300C run (which is still running) has a slightly smaller core than the 1000

Apart from the temperature, all other settings were/are completely identical between the individual mechanism generation steps.

**Comment by mjohnson541** [comment]
The reason is that the next species RMG picks up is dependent on how concentrations accumulate within the model.  At different temperatures the rates are different so this occurs in a slightly different way.  This causes the same species in different models to accumulate to different extents.  Consider the system:

->A
A -> B
A -> C
B->
C->

Suppose B and C are interchangeable in the network (rate coefficients for production and loss are the same).  If A and B are in the model the flux A->C will be drastically less than the same flux if only A is in the model.  What this means is that whether RMG picks up a species is heavily dependent on how much of the nearby reaction network already exists in the model.  At different temperatures rates are different and things get picked up in different orders.  This changes where fluxes build up, which changes what pathways get added to the model.  In short whether a pathway is missed depends on what order RMG builds the model in and that order is different for different sets of reactors.

**Comment by DetlevCM** [comment]
That makes perfect sense, however it still doesn't explain (to me) why the intermediate model fails to grow.
This makes more sense if the 300C model were the smallest, the 500C model were bigger and then the 1000C model were the largest. (Or vice versa if the low temperature reactions were key.)

**Comment by mjohnson541** [comment]
The short answer is that your temperature change is too large for you to be able to expect that sort of monotonic response.  When you change the temperature by a large amount you are completely changing the value of most rate constants.  This can turn certain pathways on and other pathways off.  Thus, changing the temperature by a difference as large as 200K can completely change the network so you can't expect RMG to construct it in the same way.  Why this problem occurred for the 500C model and not for the other two is a very complex function of the system you were running if you consider the above example perhaps 500C took the already had B so it ignored the C pathway and the other two took the C pathway (of course its probably more complicated than that, but that's the idea).

**Comment by DetlevCM** [comment]
Hmm, if it truly is a problem of large temperature steps, then I must test smaller steps to see if the issue can be repreoduced...

**Comment by bslakman** [comment]
Just a thought, it may be what the user defined as the valid "temperature range" for rate(s) in a the training set for your reaction family. RMG might use a different rate altogether (or maybe not find that reaction in a library) at 300C or at 1000C that it is using at the intermediate range. If it's an important reaction it will throw the mechanism generation off. Maybe even if it isn't important.
