### ISSUE TITLE
Backwards Compatibility

### ISSUE THREAD

**Issue by mjohnson541** [ReactionMechanismGenerator/RMG-Py#1287]
I noticed that #1284 broke one of my scripts by renaming functions and modules within rmgpy.tools.  

Some thoughts on this for the future:  
1) At minimum I think renamings particularly those of functions commonly used externally (like those in tools) should probably be brought up in RMG meetings in the future
2) If we decide we're concerned with backwards compatibility and want to enforce it I think we should at least start doing so in the tools module

**Comment by cgrambow** [comment]
I get conflicting points of view depending on who I talk to. I guess some developers think PEP 8 is more important, e.g., no camelCase for functions, and others prefer consistency/backwards compatibility throughout RMG. I'm in the latter group, but I guess I just go with whatever the reviewer thinks. The real question is why wasn't RMG developed consistently with PEP 8 in the first place considering PEP 8 was first released in 2001...

**Comment by mliu49** [comment]
My understanding is that we retained Java naming conventions during the switch to Python, which uses CamelCase for classes and mixedCase for methods.

I agree that consistency is preferable, but we lost consistency with the addition of a lot of PEP 8 conforming code a few years ago. As a result, it became very difficult to enforce "consistency" since the code was inconsistent. We decided that we needed to take an official stance last year, and settled on officially adopting PEP 8 naming conventions.

In hindsight, perhaps it would have been easier to fix the non-conforming code, but we thought that PEP 8 would be better for us in the long run.

Question: Would it be better or worse to convert everything to PEP 8 standards in a single step compared to the current trend of gradual conversion?

**Comment by cgrambow** [comment]
I agree that PEP 8 is better in the long run. I have thought about your question before and I think it would make more sense to just do it all in one go (should be relatively automatable).

**Comment by mliu49** [comment]
Seems like it could be really straightforward via basic text processing (as opposed to smart refactoring): https://stackoverflow.com/questions/23607374/python-how-to-batch-rename-mixed-case-to-lower-case-with-underscores

I think we could do it, though we should at least wait until after the next release.

**Comment by cgrambow** [comment]
That's a neat command! Although it might be better to fully refactor, since there are lots of other PEP 8 violations in the code. A few I can think of off the top of my head are not having two blank lines between class/function definitions or 1 blank like between class method definitions, and having spaces around equal signs for keyword arguments.
