### ISSUE TITLE
intra_H_migration reaction marked as duplicate in the chemkin file

### ISSUE THREAD

**Issue by xiaoruiDong** [ReactionMechanismGenerator/RMG-Py#1297]
I am using the latest version of RMG-Py to generate a model and afterwards when I try to create the 'Chemistry Set' in CHEMKIN using the file 'chem_annotated.inp', an error popped out, saying several reactions are marked duplicate but no duplicate be found. These reactions are all from intra_H_migration.

PS: version of RMG
The current git HEAD for RMG-Py is:
	e32da33dd628c9386ffeffdf2e439a316c60387c
	Wed Feb 14 17:04:45 2018 -0500

The current git HEAD for RMG-database is:
	3d68758a71da7e0f9cbeab08ffd94ed584f8b59b

[chem_annotated.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/1742034/chem_annotated.txt)
[cycloP_gas.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/1742035/cycloP_gas.txt)

**Comment by alongd** [comment]
Could you attach the 'chem_annotated.inp'?

**Comment by xiaoruiDong** [comment]
@alongd files are attached. The related reactioin # is 1731 7995  8476 8681 10011 (from cycloP_gas.out)

**Comment by mliu49** [comment]
I have a theory. This is not due to duplicate marking while saving the chemkin file, but rather the duplicate marking that is done as a result of the multiple TS changes. Following the multiple TS PR, additional duplicate marking is done in `find_degenerate_reactions` and `checkForExistingReaction`. However, those steps occur before the reaction is added to the model. As a result, two reactions (from two transition states, which is most commonly seen in intra_H_migration), will be marked as duplicate, but only one might make it into the core. Then, when saving the chemkin file, a non-duplicated reaction will have a duplicate flag.

Potential solutions:
- Reset duplicate flags when adding a reaction to the model
- Reset duplicate flags right before `chemkin.markDuplicateReactions`
- Check for single reactions with duplicate flags when marking duplicates
- Refactor multiple TS handling to not use the duplicate attribute

The first two are essentially equivalent, only differing in when it's done, and shouldn't add that much computational time. The third doesn't really accomplish much more than the first two, but might be more robust at the cost of computation time. The last might be the most difficult to implement, and may or may not be more efficient.

@goldmanm, what do you think?

**Comment by xiaoruiDong** [comment]
@mliu49 I double checked that I didn't use pruning.
