### ISSUE TITLE
Reaction system(system reactor)

### ISSUE THREAD

**Issue by shrabanti1937** [ReactionMechanismGenerator/RMG-Py#1323]
Hi,
I want to clear my understanding about the uses of system reactor in the input.py file.
Suppose if I want to generate a mechanism which will work for  equivalence ratio(phi) of 0.2-3.0, or temperature of (300-3000)K .  To generate this, do I need to specify different combination of system reactor for all probable equivalence ratios and all probable temperatures? Is there any specific criteria on selecting the system reactor?

Thanks

**Comment by mjohnson541** [comment]
So RMG's simple reactors currently operate at constant T and P and liquid reactors all operate at constant T and V.  In general you have to choose a set of reactors (T, P and initial concentrations) in your input file that span the conditions you are interested in well enough that you pick up the chemistry important for your application.  It's hard to draw up good guidelines for the spacing because it depends not only on your system, but also on T and P (you generally need less spacing at high T than low T for example).  You also don't want to use too many.  

Typically when I want to generate an oxidation mechanism valid 700-1500 K at fixed pressure I will use reactors at:  700 K, 850 K, 1000 K and 1500 K.  Pressures are usually broken up by factors of ten:  0.1 bar, 1.0 bar, 10.0 bar etc.  With equivalence ratio we typically just consider three possibilities:  lean, rich, and stoichiometric.  These heuristics are usually sufficient for us, although every system is different, in particular you may need more spacing in the equivalence ratio.

**Comment by shrabanti1937** [comment]
Thanks @mjohnson541 . Your example was helpful. I got a better understanding.
