### ISSUE TITLE
Thermo and kinetic library

### ISSUE THREAD

**Issue by shrabanti1937** [ReactionMechanismGenerator/RMG-Py#1415]
### Topic

 - [ ] Running an RMG job

### Question
Hi,
I want to use a mechanism from a literature as my kinetic library in input file.
Can I use a different kinetic or themo data from reference as my library in the input file, which is not available in RMG database?
If so is it a right way if I manually convert a chemkin file to RMG format (.py) following the format of an available file in the database?

Thanks.

**Comment by mjohnson541** [comment]
There's a script: RMG-database/scripts/importChemkinLibrary.py for converting a chemkin file into an RMG library.  I'm pretty sure it should automatically put it in the database, but otherwise put it in RMG-database/input/kinetics/libraries.

**Comment by shrabanti1937** [comment]
Hi mjohnson541,

Thanks for your reply. I was trying to run the script you mentioned.  It is showing import argparse error. I am not familiar with this. Do I need to install argparse? I tried to install it through python command window which doesn't help.

**Comment by alongd** [comment]
Please past the full error trace message

**Comment by mliu49** [comment]
The argparse module has been included in Python since version 2.7.

In addition to the error trace, could you provide details on your installation of RMG? Helpful information would include whether or not you used Anaconda, whether you downloaded the binary or installed from source, and your operating system.

**Comment by shrabanti1937** [comment]
Hi 
I am using RMG installation For Basic Users: Binary Installation Using Anaconda for Windows.
Version 2.1.0.
I attached the error message as .png file.
![error](https://user-images.githubusercontent.com/36457961/42114315-3be329a2-7bb4-11e8-8ab6-2bfa837ffb46.PNG)

**Comment by rwest** [comment]
To import it into RMG format you will need chemical identifiers for every named species in the model. I have a tool that can help with this, as well as several models that have already been imported. We haven't yet made a very easy to use interface, so let me know (r.west@northeastern.edu) if you'd like help.

**Comment by mliu49** [comment]
@shrabanti1937, a couple of notes:
1. As rwest mentioned, you will need to provide the chemical structure of every species in the mechanism you're importing. If the mechanism is reasonably sized and you know what all the species are, you can do this yourself. We have a script to convert a list of SMILES into an RMG species dictionary which can make it a bit easier. Otherwise, you will need to use the tool he mentioned which tries to automatically identify every species.
2. The error you're encountering is because you're using the main `rmg.py` script to run another script. Instead, you should directly call the importing script and provide the chemkin file, species dictionary, and a name for the library as inputs: 
```
python C:\ProgramData\Anaconda2\envs\rmg_env\Scripts\importChemkinLibrary.py chem.inp species_dictionary.txt library_name
```

**Comment by shrabanti1937** [comment]
Thanks rwest and milu49 for your reply. I misunderstood the process of using a script. I will try all above mentioned steps.
