### ISSUE TITLE
optical isomers in cyclic molecules

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-Py#1419]
### Bug Description
RMG symmetry inaccurately estimates optical isomers for cyclic molecules

### How To Reproduce
For dimethyl cyclo hexane, the symmetry number should have a factor of 9 for the methyl groups, a factor of two for flipping the ring, and a factor of 0.5 since there are two optical isomers. This should result in an overall value of 9.

```
        molecule = Molecule().fromSMILES('C1CCC(C)CC1C')
        cyclic_symmetryNumber = calculateCyclicSymmetryNumber(molecule)
        overall_symmetryNumber = molecule.calculateSymmetryNumber()
```

The overall symmetry number is 18, not 9. Since the cyclic symmetry number is 2, it is missing the optical isomers.

### Expected Behavior
I expect the correct symmetry number: 9

### Installation Information
platform independent bug

### Additional Context
The optical isomer algorithm is tied within calculate atom symmetry number, since similar operations are required. for cyclic atoms, calculate atom symmetry is not run, which causes this error. 

It seems worthwhile to separate the optical isomer number from the atom symmetry number, which would require getAtomSymmetryNumber to be refactored, either into separate methods (causing speed decrease) or into the same method (outputting two separate values).

**Comment by cgrambow** [comment]
I think I agree with you that the symmetry number should be 9, but not necessarily for the reason you provided. This problem is somewhat more complex in that it depends on the cis-trans isomerism of dimethylcyclohexane.

For the trans isomer (i.e., when the methyl groups point in opposite directions), there exists a symmetry due to flipping the ring (assuming that ring inversion is fast) and the remaining symmetries are as you described. However, for the cis isomer, there is no ring flipping symmetry. Additionally, there exists a plane of symmetry such that the molecule is not chiral even though there are two chiral centers. So for the trans isomer, we have `2*3*3*0.5 = 9` and for the cis isomer, the only symmetry is due to the methyl groups, so `3*3 = 9`.

If we choose to refactor the symmetry algorithm, we should be aware of such issues, which might lead to different results in other cases.

Lastly, I should note that the RMG website ([link](http://rmg.mit.edu/database/thermo/molecule/1%20%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B7,S%7D%20%7B9,S%7D%20%7B10,S%7D%0A2%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B3,S%7D%20%7B11,S%7D%20%7B12,S%7D%0A3%20%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B4,S%7D%20%7B13,S%7D%20%7B14,S%7D%0A4%20%20C%20u0%20p0%20c0%20%7B3,S%7D%20%7B5,S%7D%20%7B6,S%7D%20%7B15,S%7D%0A5%20%20C%20u0%20p0%20c0%20%7B4,S%7D%20%7B16,S%7D%20%7B17,S%7D%20%7B18,S%7D%0A6%20%20C%20u0%20p0%20c0%20%7B4,S%7D%20%7B7,S%7D%20%7B19,S%7D%20%7B20,S%7D%0A7%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B6,S%7D%20%7B8,S%7D%20%7B21,S%7D%0A8%20%20C%20u0%20p0%20c0%20%7B7,S%7D%20%7B22,S%7D%20%7B23,S%7D%20%7B24,S%7D%0A9%20%20H%20u0%20p0%20c0%20%7B1,S%7D%0A10%20H%20u0%20p0%20c0%20%7B1,S%7D%0A11%20H%20u0%20p0%20c0%20%7B2,S%7D%0A12%20H%20u0%20p0%20c0%20%7B2,S%7D%0A13%20H%20u0%20p0%20c0%20%7B3,S%7D%0A14%20H%20u0%20p0%20c0%20%7B3,S%7D%0A15%20H%20u0%20p0%20c0%20%7B4,S%7D%0A16%20H%20u0%20p0%20c0%20%7B5,S%7D%0A17%20H%20u0%20p0%20c0%20%7B5,S%7D%0A18%20H%20u0%20p0%20c0%20%7B5,S%7D%0A19%20H%20u0%20p0%20c0%20%7B6,S%7D%0A20%20H%20u0%20p0%20c0%20%7B6,S%7D%0A21%20H%20u0%20p0%20c0%20%7B7,S%7D%0A22%20H%20u0%20p0%20c0%20%7B8,S%7D%0A23%20H%20u0%20p0%20c0%20%7B8,S%7D%0A24%20H%20u0%20p0%20c0%20%7B8,S%7D%0A)) actually yields a symmetry number of 9 unlike your code above. We have noticed this incongruity before, but I thought it would be a good idea to document it here as well.
