### ISSUE TITLE
Model Looping Bug

### ISSUE THREAD

**Issue by mjohnson541** [ReactionMechanismGenerator/RMG-Py#1427]
In some RMG runs the iterator gets caught into a loop where it adds the same reactions to the edge over and over again:  

```
Generating kinetics for new reactions...
For reaction C=[C]CC(1339) + buten1yl1(1340) <=> butyne1(2546) + butene1(553) Ea raised from -4.7 to -4.7 kJ/mol.
Updating 0 modified unimolecular reaction networks (out of 4820)...


Summary of Secondary Model Edge Enlargement
---------------------------------
Added 0 new core species
Created 0 new edge species
Added 0 new core reactions
Created 2 new edge reactions
    C=[C]CC(1339) + buten1yl1(1340) <=> butyne1(2546) + butene1(553)
    C=[C]CC(1339) + buten1yl1(1340) <=> butyne1(2546) + butene1(553)

After model enlargement:
    The model core has 98 species and 1720 reactions
    The model edge has 3573 species and 9050 reactions

...

Generating kinetics for new reactions...
For reaction C=[C]CC(1339) + buten1yl1(1340) <=> butyne1(2546) + butene1(553) Ea raised from -4.7 to -4.7 kJ/mol.
Updating 0 modified unimolecular reaction networks (out of 4889)...


Summary of Secondary Model Edge Enlargement
---------------------------------
Added 0 new core species
Created 0 new edge species
Added 0 new core reactions
Created 2 new edge reactions
    C=[C]CC(1339) + buten1yl1(1340) <=> butyne1(2546) + butene1(553)
    C=[C]CC(1339) + buten1yl1(1340) <=> butyne1(2546) + butene1(553)

After model enlargement:
    The model core has 98 species and 1720 reactions
    The model edge has 3573 species and 9052 reactions
```

It's worth noting that if you go earlier in the log file other chemistry continues to be added while these reactions are re-added to the edge and that this has only been observed so far for pdep jobs.  

I was running propyl-methyl ether combustion with input file:  
[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/2198000/input.txt)

The truncated log file:  
[RMG.log](https://github.com/ReactionMechanismGenerator/RMG-Py/files/2197996/RMG.log)

Reproducing this bug appears to be a bit difficult as it appears to depend on what database branch you use.  I ran the above on the MPether branch.

**Comment by alongd** [comment]
A similar issue was recently observed for a p-ded job of ethylamine running on the [rulestotraining](https://github.com/ReactionMechanismGenerator/RMG-database/pull/273) -db branch and master -Py branch:

```

Summary of Secondary Model Edge Enlargement
---------------------------------
Added 0 new core species
Created 0 new edge species
Added 2 new core reactions
    CH2NH2(26) + CH3NH(71) <=> CH2NH(25) + CH3NH2(70)
    CH2NH2(26) + CH3NH(71) <=> CH2NH(25) + CH3NH2(70)
Created 0 new edge reactions

After model enlargement:
    The model core has 80 species and 3666 reactions
    The model edge has 237 species and 7637 reactions


Saving current model core to Chemkin file...
Chemkin file contains 3673 reactions.
Saving current model to verbose Chemkin file...
Chemkin file contains 3673 reactions.
Saving current model core to HTML file...
Updating RMG execution statistics...
    Execution time (DD:HH:MM:SS): 00:07:51:41
    Memory used: 749.06 MB

Conducting simulation of reaction system 2...
initializing surface ...
surface initialization complete
At time 5.0000e-04 s, reached target termination time.


Generating kinetics for new reactions...
Updating 0 modified unimolecular reaction networks (out of 6061)...


Summary of Secondary Model Edge Enlargement
---------------------------------
Added 0 new core species
Created 0 new edge species
Added 2 new core reactions
    CH2NH2(26) + CH3NH(71) <=> CH2NH(25) + CH3NH2(70)
    CH2NH2(26) + CH3NH(71) <=> CH2NH(25) + CH3NH2(70)
Created 0 new edge reactions

After model enlargement:
    The model core has 80 species and 3668 reactions
    The model edge has 237 species and 7637 reactions
```

input file:
[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/2198055/input.txt)

log file:
[log.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/2198061/log.txt)

**Comment by mliu49** [comment]
I've only looked at the log files, so these are just my hypotheses.

In @mjohnson541's case, we're repeatedly adding the same reaction to the edge. From what I could tell, the following occurred:
- Iteration 0: During the react edge stage, the problematic reaction is created for the first time.
- Iteration 1: During the enlarge stage, 5 pdep networks are explored normally. During the react edge stage, the problematic reaction is recreated and added to the edge. This process is repeated, although with different pdep networks being explored.

This suggests that there is either an issue with `checkForExistingReaction` or how react flags are set. The most recent change to `checkForExistingReaction` was by me to fix the duplicate reaction issue from multiple TS. I used the `duplicate` attribute to determine whether or not family reactions should be added. It does seem like this reaction has two different transition states, since either species could abstract a hydrogen from the other. This would lead to repeatedly adding reactions if they are generated in subsequent iterations with `duplicate=True`. I didn't think it was possible to regenerate the same reaction in different iterations though, which is why it could also be an issue with the react flags.

In @alongd's case, the same reaction is being added to the core. This could simply be because all of the reactants and products are already in the edge. Again, either reactant can abstract a hydrogen from the other to from the product species, so there are two duplicate reactions. It seems like you removed the middle of the log file, so I don't know what happened leading up to the problem. 

However, after you get there, RMG repeatedly does the react edge stage, with no enlarge stages. This could be explained if the first simulation does not identify any objects to enlarge the model with. It seems that in such a case, we'll skip the second simulation for setting the reaction filter, but still run the react edge step. Again, this means that we're re-generating this reaction even though we should have already reacted those species, and they're getting added because of the changes to `checkForExistingReaction`.

### Conclusions
This bug most likely showed up as a result of the changes to `checkForExistingReaction`. Those changes were made under the assumption that we only ever react set of reactants once. However, this appears to not be the case, as we're regenerating these reactions during every react edge call.

**Comment by mjohnson541** [comment]
We should only react each set of reactants once so doesn't this almost have to be an issue with react flags?
