### ISSUE TITLE
Unclear/nonideal bathGas determination in pdep

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-Py#1428]
### Context

When you run an pressure dependent job in RMG, [you don't specify the specific bath gas](https://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/input.html#pressure-dependence), and there is no information given about which bath gas is being used. 

The bath gas used is pre-set as equal fractions of all non-reactive molecules (which are often nitrogen, helium, and argon). The code, line 547 in [pdep.py](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/rmg/pdep.py) contains a great question, which I am trying to pose here, "is this really the only/best way to weight them?" ([commit](https://github.com/ReactionMechanismGenerator/RMG-Py/commit/c995ee3e2cbd9ac3a2a37d9c36f5db75860fd6b7)). 

### Question

When users use pdep, do they already have a specific type of bath gas in mind or is it ambiguous at that point? Should the bath gas be allowed to be input by the user or is it alright to have it a preset mixture? 

Any other ideas for changes/fixes?

**Comment by alongd** [comment]
I think this isn't being dealt with correctly in RMG.

For example, although the user has to specify at least one inert species in a PDep job to avoid an input file error, that specie could have a `0` concentration in all reactors, so it's not really the relevant bath gas.

Also, RMG adds 'Ne' and 'He' (I suspect He is not marked as nonreactive, since it appears with a species index in my jobs) by default to the species list, and the nonreactive gases (most of which are invented by RMG and are irrelevant to the run) get averaged as the bath gas.

Another related question: Why does the bath gas has to be nonreactive? In a combustion system where NOx are modelled, N2 is the bath gas, and it is quite reactive.

Perhaps we could a bath gas attribute to PDep jobs (and have something as default for backwards compatibility?).
