### ISSUE TITLE
How to set temperature range for thermo() in Arkane?

### ISSUE THREAD

**Issue by pez16103** [ReactionMechanismGenerator/RMG-Py#1517]
### Topic
General area which your question is related to.
 - [ ] Installation of RMG
 - [ ] Running an RMG job
 - [ ] Using RMG API
 - [x] CanTherm
 - [ ] Dependencies
 - [ ] An error message 

### Context
A clear and concise description what you're trying to do.

### Question
Write your question here.
I was wondering how does the program determine Tint in arkane when I run example/arkane/species/H. After I modified T in therm.py, 

species.thermo = wilhoit.toNASA(Tmin=200.0, Tmax=3000.0, Tint=1000.0)

I checked chem.inp and found only Tmin and Tmax are updated as the expected values, while Tint will be changed.

H                       H   1               G   200.000  3000.000 1988.08      1

### Installation Information
Describe your installation method and system information if applicable.
 - OS (include version if known): (e.g. Windows 10, Ubuntu 18, macOS 10.13, etc.)
 - Installation method: (e.g. installation from binary or source, with or without anaconda)
 - RMG version information:
   
   - RMG-Py: 
   - RMG-database:

**Comment by alongd** [comment]
Hi,
`Tint` is allowed to vary in order to improve the fit. If for some reason you'd like to fix it (probably compromising for accuracy), you could change line 136 you pointed to in thermo.py to be:
`species.thermo = wilhoit.toNASA(Tmin=200.0, Tmax=3000.0, Tint=1000.0, fixedTint=True)`
There are additional optional parameters to the `toNASA` function, please see [this docstring](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/thermo/wilhoit.pyx#L471).
Let us know if you have any additional questions
