### ISSUE TITLE
Windows installation instructions out of date

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#1529]
The [Binary Installation Using Anaconda for Windows](http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaUserWindows.html) and [Installation by Source Using Anaconda Environment for Windows](http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaDeveloperWindows.html) are misleading since the current version of RMG cannot function on Windows. Previously we though to change them to describe the virtual machine approach, but haven't done that yet (or have we? I'm not aware of it). In any case, the present Windows instructions should perhaps be removed.

**Comment by 12Chao** [comment]
We have just spent some time trying to install on Windows (latest issue is this:
```
> conda env create -f environment_windows.yml
Solving environment: failed

ResolvePackageNotFound:
  - dde
  - keras=1.2.2
```
)
so it is helpful to know that windows installation is currently impossible - will save us from wasting too much more time!

Is this impossible to fix in the medium/long term?
What is the recommended virtual machine approach?
We have several students in the group with Windows laptops.
(this message typed by @rwest)

**Comment by alongd** [comment]
A short term solution would be to direct the students running Windows to our RMG workshop that happens to take place next week. The first session on Monday morning is all about virtual machine installation for Win users, and will be broadcast via WebEx. I assume you are informed about it, let me know otherwise and I'll email you the details. For the long term, we need to fix the installation instructions. I don't think we have plans to support Windows moving forward, in my understanding it's too time consuming to debug the binaries (or just the realease).

**Comment by rwest** [comment]
Thanks Alon. I think at least a few of them are planning to come next week. 

Pity about the windows regression. For years it was impossible but I had thought anaconda made it easier. Oh well

**Comment by mliu49** [comment]
Anaconda definitely makes it easier to support Windows, but preparing the Windows binaries was always the most time consuming step during a release. One challenge is that OS differences must be accounted for within RMG, e.g. during file system operations or subprocess calls. This is often overlooked until binary testing or an issue is posted, since none of the developers in our group use Windows. The other major challenge is that we have a ton of dependencies which don't always have compatible Windows binaries. Then we have to not only create new binaries for RMG, but also some dependencies.

Basically, Windows support is definitely not impossible, but simply time consuming. If someone were willing to be a dedicated Windows developer, I think we could resume supporting Windows. As is, I would guess that it might take a work day (or two) to resolve the current issues with RMG on windows.

For the environment creation error you posted, the problem is with the dependencies for the machine learning thermo estimator. DDE is our own package, which was created as a noarch conda package, which I would have expected to work on Windows. However, we don't have a Windows package for keras 1.2.2 in the RMG channel.

We were planning to replace the Windows installation instructions with a recommendation to use a virtual machine along with installation instructions. @amarkpayne has previously said that he'll work on those changes.

If desired, we could immediately update the documentation by marking the Windows installation instructions as no longer supported.

**Comment by rwest** [comment]
Thanks Max. Makes sense.
I think at least as a temporary measure, an immediate update to the developer instructions saying "sorry, windows not currently supported" would save people from blaming themselves and getting frustrated.

(I just checked the google analytics to see how many hits per week the installation instructions get, but it seems we don't have tracking on the documentation?)

**Comment by amarkpayne** [comment]
I am working on a PR right now to update the instructions on the website, I hope to have it ready by later this afternoon.
