### ISSUE TITLE
How to use termination condition to control consumption of fuel?

### ISSUE THREAD

**Issue by AH9316** [ReactionMechanismGenerator/RMG-Py#1587]
### Topic
General area which your question is related to.
 - [ ] Installation of RMG
 - [x] Running an RMG job
 - [ ] Using RMG API
 - [ ] Arkane (formerly CanTherm)
 - [ ] Dependencies
 - [ ] An error message 

### Context
With running multiple RMG simulation with different conversion termination, I notice that the final number of core species and the final number of core reactions will increase with the value of the conversion termination. So I get a conclusion that if we want a completed mechanism, we should make sure all main fuel is consumed, which set conversion termination as 1. 

However, when we have multiple fuels mixtures, for example, we have 80% propane, 20% toluene and corresponding stoichiometric air(O2+N2), I did a test. I set conversion termination for propane as 0.5, and conversion termination for toluene as 1.0 and when the simulation reached the target conversion termination for propane(0.5), only 0.1721 of toluene is consumed. The screen capture as below:
![RMG_problem](https://user-images.githubusercontent.com/49660649/56720079-d26f2c80-66f6-11e9-93b8-9ce766222fee.png)

### Question
1. For the above specific example, can I say that if I set conversion termination for toluene as 1 as the only termination criteria, when the simulation reaches the target conversion termination, the propane should be 100% consumed?

2. General, when we set conversion termination for some fuels that smaller than 1, for example, we have 1 mole methane at the beginning and we set conversion termination as 0.6.  What will happen to the rest of 40% methane, it's still methane or it will decompose to other species or radical?

3. For time termination, because we do not know how long it will take to consume all fuels, it won't be a good choice. Do we have other termination criteria to make sure all fuels will be consumed at the end and we can get a completed mechanism?

**Comment by alongd** [comment]
In general, I wouldn't recommend using a conversion termination criterion of exactly 1, since I expect some of the reactant to remain due to chemical equilibrium. Even if the amount is tiny and we would call it negligible, it is not 0 for the computer, and it just won't terminate.
A recommendation, touching on Q3 above, is to use[ `terminationRateRatio`](http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/input.html#reaction-system). Simply put, the model generation will terminate once all fluxes in the system are relatively small.
