### ISSUE TITLE
File exist error

### ISSUE THREAD

**Issue by rlawson** [ReactionMechanismGenerator/RMG-Py#1595]
### Topic
General area which your question is related to.
 - [ ] Installation of RMG
 - [x] Running an RMG job
 - [ ] Using RMG API
 - [ ] Arkane (formerly CanTherm)
 - [ ] Dependencies
 - [x] An error message 

### Context
A clear and concise description what you're trying to do.

### Question
I imported a chemical model into reaction library and thermo library and used it to run a simulation. However, i keep getting an error below.

Traceback (most recent call last):
  File "/auto/rcf-proj/fe/rlawson/research/simulation/envs/runs/aniline_gasoline/3_T_0.01_R_0.01_725/./rmg.py", line 173, in <module>
    main()
  File "/auto/rcf-proj/fe/rlawson/research/simulation/envs/runs/aniline_gasoline/3_T_0.01_R_0.01_725/./rmg.py", line 167, in main
    rmg.execute(**kwargs)
  File "/home/rcf-proj/fe/rlawson/research/simulation/envs/rmg_env/lib/python2.7/site-packages/rmgpy/rmg/main.py", line 603, in execute
    self.initialize(**kwargs)
  File "/home/rcf-proj/fe/rlawson/research/simulation/envs/rmg_env/lib/python2.7/site-packages/rmgpy/rmg/main.py", line 443, in initialize
    util.makeOutputSubdirectory(self.outputDirectory, 'pdep')
  File "/home/rcf-proj/fe/rlawson/research/simulation/envs/rmg_env/lib/python2.7/site-packages/rmgpy/util.py", line 121, in makeOutputSubdirectory
    os.mkdir(dir)
OSError: [Errno 17] File exists: '/auto/rcf-proj/fe/rlawson/research/simulation/envs/runs/aniline_gasoline/3_T_0.01_R_0.01_725/pdep'
srun: error: hpc3533: task 0: Exited with exit code 1

I'll appreciate any help to resolve this. Thank you

**Comment by mjohnson541** [comment]
This doesn't look like a library issue.  Have you tried running in a clean directory (no RMG output files)?  It looks like it should be deleting the pdep directory before making a new one, but for some reason in this case it seems to not delete the old directory and tries to make a new pdep directory while the old one is still there.

**Comment by rlawson** [comment]
Yes, I did start in a clean directory with no RMG output files but I still get that same error. we checked the RMG log and it shows the model generation was completed, which sort of contradicts.

**Comment by mjohnson541** [comment]
Can you send your input file?

**Comment by rlawson** [comment]
[input_gasoline_aniline_baseline_T_0.01_R_0.01_725.zip](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3159532/input_gasoline_aniline_baseline_T_0.01_R_0.01_725.zip)

**Comment by rlawson** [comment]
I think our species mole fractions are somewhat low and this interferes with the rate ratio termination we have set. Secondly, I don't see one of the species (aniline) in the reactions generated.

**Comment by mliu49** [comment]
We remove old directories before making the new directory, but the fact that the old directory still exists suggests that the removal failed. However, I would have expected there to be an error message about failure to remove the directory if that were the case. Honestly, I can't think of what could cause that specific error message.

Could you provide a bit more information about your install? In particular, operating system and RMG version if you did the binary install or git hash if you installed from source would be helpful.

**Comment by mjohnson541** [comment]
That's strange, this input file should react everything in the core straight off and you have no constraints on the species.  I'd recommend raising the rate ratio termination to 0.3 or 0.1.  I don't recommend generating restart files, we're working on better ways to restart jobs right now, but the current restart files are often more trouble than they're worth.   However, none of that seems to explain your issue.

**Comment by rlawson** [comment]
I installed using Anaconda on a Linux system with Python 2.7. I basically followed the installation procedure of 3.2.1 on the documentation. 
I'll run a case with rate ratio termination of 0.1 to see the outcome.

**Comment by AH9316** [comment]
@mjohnson541 I have a question about rate ratio termination. 
According to https://www.youtube.com/watch?v=gazRzW5IU9E&list=PLZUqt5RldKbTcbPdmDIvY5mfaWAerMUo7&index=5, if we set termination criteria as rate ratio, the simulation will stop when the characteristic rate reaches a given fraction of the maximum characteristic observed so far. 
If I did not misunderstand the meaning of rate ratio termination, the smaller rate ratio termination will introduce more edge species and edge reactions to the core region, right? So why should we increase rate ratio termination rather than decrease rate ratio termination?

**Comment by mjohnson541** [comment]
You're correct.  In general 0.01 is a very safe value, but lately I've run into cases where it starts to add extra unwanted species because it's operating when the overall flux is very small.  Increasing the value to around 0.1 seems to help a lot in these cases.  I assumed the issue was related to odd behavior near the end of the run, since the flux criterion should scale to low fluxes without trouble, am I correct on this @rlawson or is this an issue with it terminating earlier than anticipated?

**Comment by rlawson** [comment]
I saw this behavior at the end of just the first iteration. Changing the termination rate ratio even to 0.1 didn't help. However, I got it running without trouble when I rather used the termination conversion of 0.95 for one of the input species instead of a rate ratio termination

**Comment by rwest** [comment]
Sometimes strange things happen when the operating system or file system don't respond instantly, due to cacheing or something, especially common when using network mounted drives typical on a cluster. Could it be, for example, that the system call to delete the old folder completes and returns to Python which then tries to make the new folder, before the old folder is *actually* fully deleted. Something like that? 
Otherwise it's hard to explain. Unless running two instances of RMG in the same folder? - which could also likely cause problems like this.
