### ISSUE TITLE
Running big molecules(aromatic,gasoline surrogate) issuses

### ISSUE THREAD

**Issue by AH9316** [ReactionMechanismGenerator/RMG-Py#1613]
### Topic
General area which your question is related to.
 - [ ] Installation of RMG
 - [x] Running an RMG job
 - [ ] Using RMG API
 - [ ] Arkane (formerly CanTherm)
 - [ ] Dependencies
 - [ ] An error message 

### Context
Regards to issue #1611, we are trying to use toluene-air, heptane-air and isooctane-air models as seed mechanism to get gasoline surrogate model. However, we meet a problem when we run the toluene RMG simulation. According to issue #1579, we only can get 32 species and 43 reactions of toluene model with 4 days running. And this model is not big enough to do anything, such as ignition delay time simulation.

At the same time, we run the gasoline surrogate(0.17 mole n-heptane, 0.63 mole isooctane, 0.2 mole toluene, 11.545 mole oxygen, 43.4092 mole nitrogen) with 5 to 6 days and we get a model with 35 species and 61 reactions. And this model is not big enough to do anything, too. I attach the input file below:

[input_gasoline_surrogate_T_0.01_R_0.01_725_to_950 .txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3244427/input_gasoline_surrogate_T_0.01_R_0.01_725_to_950.txt)

For the aromatic simulation, we actually did some test, we tried to use filter and pruning the model to speed up the simulation, but it didn't work well, refer to #1589. And then we add some species that may be generated by toluene-air reactions into the model to speed up RMG simulation, it actually does not work well, too. The simulation is still stuck at some point, which has a small number of species and a small number of reactions.

### Question
1. By reviewing how filter and pruning to speed up RMG simulation, I find that these 2 methods actually will decrease the final model because we try to remove some species from core region or prevent some species adding into core region. However, now, we have a problem that the final model is too small, so I wonder should we use filter or pruning to speed up simulation? 

2. What are the possible reasons that cause aromatic RMG simulation cannot continue at some point? And how to make RMG enlarge the final model?

**Comment by mjohnson541** [comment]
Hmm...interesting, we don't usually see slowdown like that that early in mechanism construction, although you do have several different quite large species, so some slowdown relative to a normal run is expected.   Although I find the fact that a model with as large of species as you're using completed generation with 32-35 species quite strange at the tolerance you're using.  
  
There are a couple of concerns I have with your input file:  

1) You have no thermochemistry libraries beyond the primary one and no seeds to cover the small molecule chemistry (C2).  This is very very important and bad thermochemistry and seed chemistry can hurt model generation in many different ways you don't expect.  For these conditions I would usually use at least:  
thermoLibraries=['Klippenstein_Glarborg2016','BurkeH2O2','primaryThermoLibrary','thermo_DFT_CCSDTF12_BAC','CBS_QB3_1dHR','DFT_QCI_thermo'],
seedMechanisms=["C2H4+O_Klipp2017","Klippenstein_Glarborg2016","BurkeH2O2inN2"],

To get a more accurate model it will of course need thermochemistry and rates related to the particular model being generated, but this is usually sufficient for a first run of RMG.  

2) It's possible your issues are occurring because the termination criterion is triggering too early.  Try using different termination criteria (isoctane conversion and time perhaps), that might help.  

3) Worst case you can always decrease your toleranceMoveToCore to get RMG to add more species

4) I highly highly highly recommend always leaving filterReactions=True on.  Having it off can make RMG drastically slower and we've never had any cases where we missed chemistry due to having it on.  

5)  The way you're running RMG in that input file there's no reason to not have toleranceMoveToCore==toleranceInterruptSimulation

6) You haven't added any species constraints, you can run RMG this way, usually without too many issues, but it may be a bit slower than if you prevent large molecules from adding end to end.

**Comment by sthakris** [comment]
> Hmm...interesting, we don't usually see slowdown like that that early in mechanism construction, although you do have several different quite large species, so some slowdown relative to a normal run is expected. Although I find the fact that a model with as large of species as you're using completed generation with 32-35 species quite strange at the tolerance you're using.
> 
> There are a couple of concerns I have with your input file:
> 
>     1. You have no thermochemistry libraries beyond the primary one and no seeds to cover the small molecule chemistry (C2).  This is very very important and bad thermochemistry and seed chemistry can hurt model generation in many different ways you don't expect.  For these conditions I would usually use at least:
>        thermoLibraries=['Klippenstein_Glarborg2016','BurkeH2O2','primaryThermoLibrary','thermo_DFT_CCSDTF12_BAC','CBS_QB3_1dHR','DFT_QCI_thermo'],
>        seedMechanisms=["C2H4+O_Klipp2017","Klippenstein_Glarborg2016","BurkeH2O2inN2"],
> 
> 
> To get a more accurate model it will of course need thermochemistry and rates related to the particular model being generated, but this is usually sufficient for a first run of RMG.
> 
>     2. It's possible your issues are occurring because the termination criterion is triggering too early.  Try using different termination criteria (isoctane conversion and time perhaps), that might help.
> 
>     3. Worst case you can always decrease your toleranceMoveToCore to get RMG to add more species
> 
>     4. I highly highly highly recommend always leaving filterReactions=True on.  Having it off can make RMG drastically slower and we've never had any cases where we missed chemistry due to having it on.
> 
>     5. The way you're running RMG in that input file there's no reason to not have toleranceMoveToCore==toleranceInterruptSimulation
> 
>     6. You haven't added any species constraints, you can run RMG this way, usually without too many issues, but it may be a bit slower than if you prevent large molecules from adding end to end.

Adding up to this issue, I was trying to generate TNT model which is a aromatic ring with NO2 and my model does not converge or no model is gnerated. It gets stuck at one point. Is RMG capable of generating model for CHON large molecule. I do not have a mixture as in gasoline surrogate. I just want to have a pyrolysis model of big molecules with Nitogen atoms like NO2, NH2, NH. 

I used a Filtering instruction given in documentation and tried different model parameter and still it gets stuck. 
Can you suggest anything on it so RMG starts doing something?
