### ISSUE TITLE
can we generate seed mechanism from unfinished RMG job.

### ISSUE THREAD

**Issue by shenghuiqin** [ReactionMechanismGenerator/RMG-Py#1663]
Topic
General area which your question is related to.
 - [ ] Installation of RMG
 - [x] Running an RMG job
 - [ ] Using RMG API
 - [ ] Arkane (formerly CanTherm)
 - [ ] Dependencies
 - [ ] An error message 

### Context
I want to use chem.inp and species.txt files (chemkin folder from RMG job) to generate 'seed mech'
eg, while I am running a time-consuming RMG job, I want it to finish quickly. I wish to suspend the job and let me change my input file, and then continue running. This seems unachievable, so I thought an alternative way is to stop the job, and generate seed mech and rerun with seed again.

### Question
can we solely generate seed mechanism using unfinished RMG job.

**Comment by mjohnson541** [comment]
There's a script in RMG-database/scripts called importChemkinLibrary.py that can convert your chem.inp + species_dictionary.txt files into a reaction library (which is the same object as a seed mechanism).  You can then put that reaction library in RMG-database/input/kinetics/libraries and then you'll be able to use it as a seed mechanism in an RMG run.  In future you can set generateSeedEachIteration=True in the options block to generate a seed each iteration of the RMG job (speed cost of this is negligible).  

It's worth noting this isn't going to save you nearly as much time as you might think, because when you start the new job, while RMG knows more about what will be in the core, RMG doesn't know what has and hasn't reacted and thus has to react all of the species again.

**Comment by shenghuiqin** [comment]
> There's a script in RMG-database/scripts called importChemkinLibrary.py that can convert your chem.inp + species_dictionary.txt files into a reaction library (which is the same object as a seed mechanism). You can then put that reaction library in RMG-database/input/kinetics/libraries and then you'll be able to use it as a seed mechanism in an RMG run. In future you can set generateSeedEachIteration=True in the options block to generate a seed each iteration of the RMG job (speed cost of this is negligible).
> 
> It's worth noting this isn't going to save you nearly as much time as you might think, because when you start the new job, while RMG knows more about what will be in the core, RMG doesn't know what has and hasn't reacted and thus has to react all of the species again.

THANK YOU! It helps.

**Comment by shenghuiqin** [comment]
![image](https://user-images.githubusercontent.com/44587695/61800893-dbf25880-adfb-11e9-928b-47a1ee23e1e9.png)


> There's a script in RMG-database/scripts called importChemkinLibrary.py that can convert your chem.inp + species_dictionary.txt files into a reaction library (which is the same object as a seed mechanism). You can then put that reaction library in RMG-database/input/kinetics/libraries and then you'll be able to use it as a seed mechanism in an RMG run. In future you can set generateSeedEachIteration=True in the options block to generate a seed each iteration of the RMG job (speed cost of this is negligible).
> 
> It's worth noting this isn't going to save you nearly as much time as you might think, because when you start the new job, while RMG knows more about what will be in the core, RMG doesn't know what has and hasn't reacted and thus has to react all of the species again.

sorry to bother you again:worried:, I tried to run importchemkinlibrary.py, it stops with no error but also no output file, can you help to see what's the problem?

**Comment by mjohnson541** [comment]
Sorry, when you run the script it makes the library in your RMG-database, not the local directory.
