### ISSUE TITLE
Does RMG mechanism depend on initial mole fractions of reactant?

### ISSUE THREAD

**Issue by AH9316** [ReactionMechanismGenerator/RMG-Py#1698]
### Topic
General area which your question is related to.
 - [ ] Installation of RMG
 - [ ] Running an RMG job
 - [ ] Using RMG API
 - [ ] Arkane (formerly CanTherm)
 - [ ] Dependencies
 - [ ] An error message 

### Context
Using RMG to generate mechanisms for a while, we find that the mechanisms that generated from RMG are different with different initial mole fractions of the same reactants. For example, we get different mechanisms that have 10% 1,3,5-TMB and 20% 1,3,5-TMB, separately. Let's call 10% 1,3,5-TMB mechanism as M1 and 20% 1,3,5-TMB mechanism as M2. We use M1 and M2 to run Ignition Delay Time(IDT) simulation, and we get some reasonable and unreasonable results. If we only use M2 to run IDT with 5% 1,3,5-TMB, 10% 1,3,5-TMB, 20% 1,3,5-TMB, and 30% 1,3,5-TMB, we get a good result, which is IDT(30%)>IDT(20%)>IDT(10%)>IDT(5%). However, if we use M1 to run 10% 1,3,5-TMB IDT and M2 to run 20% 1,3,5-TMB, we will get IDT(10%)>IDT(20%), which doesn't make sense. 

### Question
1. We wonder does RMG mechanism depends on initial mole fractions a lot?   
2. Is that possible we only need to list species in the species block and don't need to set initial mole fraction of species in the simpleReactor block and we can get a mechanism that doesn't depend on mole fraction?

**Comment by mjohnson541** [comment]
RMG uses rate based mechanism generation.  This means RMG decides what species to react and what species to add to the model based on simulating the system and looking at the flux through reactions that aren't in the model. In order to run a simulation you need to have initial conditions to start the simulation from.  In general RMG can be very sensitive to these initial conditions because they change how important various reactions are.  You can reduce the dependence of the mechanism on initial mole fractions by including more reactor blocks at a greater variety of initial mole fractions.  

Now if you want to just list species to include in the mechanism and then generate reactions between all of them there is a script call generateReactions.py in RMG-Py/scripts that can be run on an input file.  If you set filterReactions=False in the model block this script will react all of the species included together and estimate all thermo and reactions based on the database block and returns a chemkin file.  This will give you a model completely independent of your choice of initial mole fractions.
