### ISSUE TITLE
generateReactions.py script

### ISSUE THREAD

**Issue by AH9316** [ReactionMechanismGenerator/RMG-Py#1716]
### Topic
General area which your question is related to.
 - [ ] Installation of RMG
 - [ ] Running an RMG job
 - [ ] Using RMG API
 - [ ] Arkane (formerly CanTherm)
 - [ ] Dependencies
 - [ ] An error message 

### Context
I try to use generateReactions.py to generate reactions, however, I meet an error message shows below:
   
Using Theano backend.
Traceback (most recent call last):
  File "generateReactions.py", line 38, in <module>
    import rmgpy.tools.generate_reactions as generate_reactions
  File "/home/rcf-40/anguohu/.conda/envs/rmg_env/lib/python2.7/site-packages/rmgpy/tools/generate_reactions.py", line 45, in <module>
    from rmg import parse_command_line_arguments
ImportError: No module named rmg

### Question
How to fix this issue?

**Comment by amarkpayne** [comment]
Before going any further, can we confirm that you have installed RMG through the anaconda binary? (i.e. not from source from GitHub). If you look at your traceback, it is calling RMG files that are inside of your conda environment, which is the expected behavior for a binary install but not if you cloned from GitHub.

**Comment by AH9316** [comment]
@amarkpayne Hi, I have confirmed that I install with anaconda.

**Comment by amarkpayne** [comment]
@mliu49 I wonder if this issue is because rmg.py is not defined as a module in setup.py. We have it listed as a script of course, but that won't help if we need to import a function from it, right?

**Comment by mliu49** [comment]
I think so. When installing or building the conda package, scripts end up in the `bin` directory, which is probably not on PYTHONPATH.

**Comment by amarkpayne** [comment]
@AH9316 as a temporary solution, see what happens if you append the following onto your .bashrc file:

`export PYTHONPATH=$PYTHONPATH:~/.conda/envs/rmg_env/bin` (make sure that this is the right path to the bin folder of you rmg environment).

Let us know if this works. On our end we will implement a fix so that future binaries include the rmg.py file as a module.

**Comment by AH9316** [comment]
@amarkpayne Hi, thank you for your help and it works now.
