### ISSUE TITLE
ImportError: No module named util

### ISSUE THREAD

**Issue by NtuCheRoy** [ReactionMechanismGenerator/RMG-Py#1722]
When I run my ARC job, it appeared "ImportError: No module named util" error, util is a package of arkane. I installed rmg by "conda install -c rmg rmg", and I had added the PYTHONPATH by  "export PYTHONPATH=$PYTHONPATH:~/.conda/envs/arc_env/bin". Could you tell me how to solve this problem?

**Comment by amarkpayne** [comment]
This issue should probably get moved to the ARC repo, but I think the issue is that ARC currently does not use the RMG-Py binary, so adding your conda environment bin to the PYTHONPATH won't resolve this issue (as is the case for you). Instead you need to clone the RMG-Py and RMG-database repos (side-by-side) and add the RMG-Py folder to PYTHONPATH. @alongd correct me if I am wrong though.

**Comment by alongd** [comment]
Correct.Cloned to https://github.com/ReactionMechanismGenerator/ARC/issues/189
