### ISSUE TITLE
Profile information not saved if job killed by SLURM scheduler

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#1783]
### Motivation or Problem
When RMG is killed suddenly by a SLURM scheduler for running over the allocated wallclock time, it doesn't get a chance to save the profiling information (when running with the `-p` option), which means you can't tell why it was taking so long in the first place.

### Desired Solution
I wonder if we could call `dump_stats` at the end of each generation, without much overhead.
https://docs.python.org/2/library/profile.html#pstats.Stats.dump_stats
I have not looked into this very far.

**Comment by amarkpayne** [comment]
I like this idea a lot, and I am wondering why I didn't look into this when I was adding commits to my profiler tools branch in #1173. I am doing some RMG profiling with @kspieks so I will see if I can add this and clean up the profiler tools branch so that this can get merged in. Thanks for the suggestion @rwest !
