### ISSUE TITLE
Silane family not working

### ISSUE THREAD

**Issue by dronekill** [ReactionMechanismGenerator/RMG-Py#1821]
### Bug Description
I created a family for atom silane namely Silylene_insertion and Silylene_to_Silene. The files are attached.

### How To Reproduce
The input file is also attached
### Expected Behavior
The families should generate reactions based on their recipe but no reactions is getting generated and model generation gets to completion.

### Installation Information
Describe your installation method and system information.
 - ubuntu 18
 - Installation method: developer version
 - RMG version information:
   
   - RMG-Py: 2.4.0
   - RMG-database: 2.4.0

![Screenshot from 2019-11-18 12-12-13](https://user-images.githubusercontent.com/51900085/69030136-b4ec1200-09fc-11ea-970b-90e6f7e75911.png)

**Comment by alongd** [comment]
Hi, thanks for reporting the problem.
To help you debug we'll need to take a look (or run) the families you created and added to RMG. Please upload them by dragging the files to these comment boxes (note that you'll need to change all file extensions to `.txt` for GitHub to accept them). Please also upload your input file in a text format. Also, if you got any errors while running this job, please past them here as well.

**Comment by dronekill** [comment]
[groups.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3862183/groups.txt)
[rules.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3862184/rules.txt)
[reactions.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3862185/reactions.txt)
[dictionary.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3862186/dictionary.txt)
[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3862190/input.txt)

**Comment by dronekill** [comment]
[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3862192/input.txt)
[groups.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3862193/groups.txt)
[rules.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3862194/rules.txt)
[reactions.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3862195/reactions.txt)
[dictionary.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3862196/dictionary.txt)

**Comment by dronekill** [comment]
I am new to this i accidently closed this issue. Should i open a new one?

**Comment by dronekill** [comment]
Silylene_to_Silene family
[rules.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3862243/rules.txt)
[groups.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3862244/groups.txt)
[reactions.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3862247/reactions.txt)
[dictionary.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3862248/dictionary.txt)

**Comment by dronekill** [comment]
[SiliconHydrideLibrary.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3862261/SiliconHydrideLibrary.txt)

**Comment by dronekill** [comment]
output
![Screenshot from 2019-11-19 11-57-48](https://user-images.githubusercontent.com/51900085/69122081-e7ad0d80-0ac3-11ea-92d3-284db862b4eb.png)

**Comment by alongd** [comment]
I think you're not seeing any reactions from the family you defined and get a very small model since the `toleranceMoveToCore` was set to 0.1. Try setting it to 0.005, and then play with it to increase/decrease the model size.

**Comment by dronekill** [comment]
Still, the Model didn't produce any reactions.

**Comment by alongd** [comment]
In the database block of the input file you have `kineticsFamilies = ['Silylene_Insertion']`, so RMG doesn't use any other family (it's restricted to only use that one). Hence, we don't see any initiation reactions. [See the documentation about defining this section of the input file](http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/input.html#kinetics-families). I suggest using a mix of the predifined set (`default`) and the new families you care about, e.g.:
```python
kineticsFamilies = ['default', 'Silylene_Insertion']
```

**Comment by dronekill** [comment]
I have added training reactions in the 'Silylene_Insertion' family, so these should get into my core or edge. But these reactions are not being used.

**Comment by alongd** [comment]
right, because the chemistry wasn't initiated (nothing reacted yet)

**Comment by dronekill** [comment]
![Screenshot from 2019-11-27 10-23-45](https://user-images.githubusercontent.com/51900085/69694795-092f7a00-1100-11ea-9065-34cc5cccfae0.png)
I switched on default as you recommended but still the training reactions were not involved.

**Comment by alongd** [comment]
I'm also happy to hear that RMG started giving a relevant model. Check whether the model contains species that can react via the families you added. Also check whether the reactions you are expecting we're added to the edge (their rate might be too low).
At this point I think you need to start analyzing fluxes to understand what's going on, and how and why is the model different than what you are expecting.

**Comment by mliu49** [comment]
Just to reiterate what Alon has already mentioned, training reactions are not automatically added to the model. They are only used to inform rate estimates for reactions which may be generated.

If you know for sure that you want certain reactions in the model, you should add the reactions to a kinetics library, and then specify the library as a seed mechanism.

**Comment by dronekill** [comment]
I think the problem lies in the application of the family template; the template is not being applied. I have tried putting the reactions in the seed mechanism, but no new reactions got generated except ones that are already present in the seed. I am trying to replicate the work of Belinda L.Slakman and trying to extend RMG further to other reactions. The families that she created has a recipe action "LOSE_PAIR" when I tried to apply the same, it gave me an error. Therefore, I would like to know if this recipe action (LOSE_PAIR) still working in this version of RMG or has it become obsolete. Please also suggest me if I am making any mistake while writing the input file. 
Here is the link to here commit page:
https://github.com/ReactionMechanismGenerator/RMG-database/compare/master...bslakman:silicon-hydrides

**Comment by rwest** [comment]
Hi. We recently made some progress updating Belinda's work to be compatible with the current RMG. Not fully debugged and tested yet, but you can see @MingyuWAN's progress at https://github.com/ReactionMechanismGenerator/RMG-database/compare/master...MingyuWAN:sih4

**Comment by dronekill** [comment]
I went through the page 
https://github.com/ReactionMechanismGenerator/RMG-database/compare/master...MingyuWAN:sih4
Silylene_insertion is still producing absurd errors.
[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3942981/input.txt)
![Screenshot from 2019-12-10 09-34-28](https://user-images.githubusercontent.com/51900085/70494456-5e708000-1b31-11ea-99a0-1f0797ba149a.png)

**Comment by dronekill** [comment]
https://github.com/MingyuWAN can you suggest something?

**Comment by dronekill** [comment]
@MingyuWAN can you suggest something?

**Comment by mliu49** [comment]
I think there are a number of different issues here. Unfortunately, I don't have time to investigate in too much detail, but here are some initial observations from briefly looking at this:

1. The most recent screen shot posted with an `UndeterminableKineticsError` points towards an incorrect training reactions. As you can see, the error occurs right after `Adding rate rules from training set in kinetics families...` is printed in the log. The problematic reaction is apparently `SiH4 = SiH4 + H2`, which is clearly wrong.
2. The lack of the `LOSE_PAIR` action in the original version of the `Silylene_insertion` family is definitely the reason why you don't get any reactions from it. Once you form the new bonds, the product species with 4 bonds and 1 lone pair is invalid, so RMG discards the reaction.
3. You mentioned that adding the `LOSE_PAIR` action leads to an error. The error I encountered was `ActionError: Unable to update GroupAtom due to LOSE_PAIR action: Unknown atom type produced from set "[<AtomType "Sis">]".` I assume you would have encountered the same. This is because the `Sis` atomtype does not have product atomtypes defined for this action. What RMG does when loading kinetics families is take the reactant templates and apply the recipe to obtain product templates. During this process, it must update the atomtypes accordingly so that the product template is accurate. For a given reactant atomtype and reaction recipe action, there is a list of associated product atomtypes. You can find that [here](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/molecule/atomtype.py#L621) for the `Sis` atomtype. As you can see, the product atomtypes for increment/decrement lone pair are empty. I think it may be sufficient to fill in `Sis` for those. In theory, you should consider _all_ of the potential atomtypes which could result from any `Sis` atom losing a lone pair.

I did not look at the `Silylene_to_Silane` family, but you should review it with similar considerations. Make sure that the recipe is correctly written to include all necessary actions, make sure that the atomtypes used in the group definitions have product atomtypes defined for all of the recipe actions used, and make sure that your training reactions are written correctly.

**Comment by dronekill** [comment]
@mliu49 @alongd @rwest 
Thank you for helping me resolve this issue.
