### ISSUE TITLE
Difficulty creating adjacency list for web interface of Molecule Search

### ISSUE THREAD

**Issue by jgiaccai** [ReactionMechanismGenerator/RMG-Py#1874]
We are interested in a project using the Molecule Search to calculate the thermodynamic properties of some molecules.  Ultimately we hope to use the Python code itself, but at the moment we are testing the feasibility with the web version of Molecule Search.  

To enable us to do this somewhat efficiently I have written a piece of code in python that will generate an adjacency list to input into the Molecule Search webpage.  As far as I can tell the adjacency list generated _should_ work, but it generates an "invalid adjacency list" error.  I have checked that all of the bonds are correct (both feasible in the molecule and correctly represented in the adjacency list).  I have tried changing the line endings (trying \r, \n, and \r\n endings).  

I have compared it to an adjacency list generated by Molecule Search by using the molecule drawing popup window to draw the same molecule.  Although the atoms are numbered differently (and therefore the atom numbers and bond descriptors differ) when I have compared my generated adjacency list with the Molecule Search generated adjacency list there do not appear to be any syntax differences.  

I have attached a text file with the adjacency list as my program has generated it and a picture of the molecule in question.  
![Hc_c24h14_0pent_0](https://user-images.githubusercontent.com/26629271/73042885-ed5f0080-3e30-11ea-9059-8d15c8376e07.png)

[Hc_c24h14_0pent_1.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/4106713/Hc_c24h14_0pent_1.txt)

The lines of code I am using to write the adjacency text files are:  

    ############ Write adjacency list file  ############## 
    # <number> [<label>] <element> u<unpaired> [p<pairs>] [c<charge>] <bondlist>

    with open(molfilename+".txt", 'w+') as fileout:
        fileout.write(molfilename); fileout.write('\n')  #first line with molecule name
        fileout.write("multiplity 1 \n")
        for x in range(0,len(AtomsDF)):   #Atoms block
            if AtomsDF['AN'].iloc[x] == 6:
                if AtomsDF['N1_BO'].iloc[x] ==1:
                    BO1 = 'S'
                else:
                    BO1 = 'D'
                if AtomsDF['N2_BO'].iloc[x] ==1:
                    BO2 = 'S'
                else:
                    BO2 = 'D'
                if AtomsDF['N3_BO'].iloc[x] ==1:
                    BO3 = 'S'
                else:
                    BO3 = 'D'
                string = str(AtomsDF['AtomNo'].iloc[x]) + ' ' + AtomsDF['element'].iloc[x] + ' u0 p0 c0 ' + '{' + str(AtomsDF['N1'].iloc[x]+1) + ','+ BO1 +'} ' +  '{' + str(int(AtomsDF['N2'].iloc[x])+1) + ','+ BO2 +'} '+ '{' + str(AtomsDF['N3'].iloc[x]+1) +','+ BO3 +'}\n'
            if AtomsDF['AN'].iloc[x] == 1:
                string = str(AtomsDF['AtomNo'].iloc[x]) + ' ' + AtomsDF['element'].iloc[x] + ' u0 p0 c0 ' + '{' + str(AtomsDF['N1'].iloc[x]+1) + ',S}\n'

            fileout.write(string)

Any help appreciated!

**Comment by alongd** [comment]
Hi,

I strongly recommend using RMG's API instead of the web platform for these operations for several reasons. First, exactly for cases like this, the API will tell you what the problem is with your adjacency list, whereas the website simply says "invalid adj list" if there's a problem. Second, the RMG codebase is more up to date, we update the website accordingly only periodically.

I ran your adjlist through the API and got:
`ValueError: invalid literal for int() with base 10: 'multiplity'`
Since there was a typo in the word "multiplicity".
(note that you don't have to specify trivial multiplicity such as `multiplicity 1`)

Fixing this typo resulted in another error:
`AtomTypeError: Unable to determine atom type for atom C, which has 1 single bonds, 2 double bonds to C, 0 double bonds to O, 0 double bonds to S, 0 triple bonds, 0 benzene bonds, 0 lone pairs, and 0 charge.`
So you should look for a C atom defined with 1 S and 2 D, which results in invalid valance.
And here it is :`10 C u0 p0 c0 {9,D} {11,S} {2,D}`

### How to generate thermo?
Install RMG following the direction in the documentation (http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/index.html#for-developers-installation-by-source-using-anaconda-environment) - choose installation for developers
After installing and adding to the PYTHONPATH, you can use the thermo estimator script: https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/scripts/thermoEstimator.py

### How to use our API?
To use the API to just validate an adjacency list, do the following in a Jupyter Notebook:
```python
from rmgpy.molecule import Molecule
from IPython.display import display
%matplotlib notebook

adj = """multiplicity 2
1 C u1 p0 c0 {2,S} {3,S} {4,S}
2 H u0 p0 c0 {1,S}
3 H u0 p0 c0 {1,S}
4 H u0 p0 c0 {1,S}"""
mol = molecule.Molecule().from_adjacency_list(adj)
display(mol)
```

**Comment by jgiaccai** [comment]
Ugh... five bonded carbon, rookie mistake!  I guess I was too tired when looking at the JMOL of the molecule.  

Thanks for your help.  Downloading the API was on my list of tasks for today, and this just bumped it up the list even further.
