### ISSUE TITLE
Unable to update atomtype while creating a new surface family involving CO atom

### ISSUE THREAD

**Issue by dronekill** [ReactionMechanismGenerator/RMG-Py#1878]
We are creating a new surface family for the water gas shift reaction. In this reaction, the physically adsorbed CO on the  Pt catalyst reacts with chemically adsorbed OH atom, which forms formate as an intermediate. However, applying the recipe on Van der Waal bond yields error unable to determine atomtype.

**Comment by dronekill** [comment]
The surface family files are attached.
[groups.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/4147834/groups.txt)
[rules.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/4147835/rules.txt)
[reactions.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/4147838/reactions.txt)

The input file is:
[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/4147840/input.txt)

The error is: 
 
![Screenshot from 2020-02-03 17-54-50](https://user-images.githubusercontent.com/51900085/73653051-599df780-46ae-11ea-9eb2-c23f1295c4f9.png)

**Comment by mjohnson541** [comment]
I don't think what you've defined is a physically adsorbed CO. Because
1   O2d u0 {1,D}
2   CO  u0 {2,D}
Isn't a resonance structure of CO in RMG. In RMG the representative resonance structure is: 
1 O u0 p1 c+1 {2,T}
2 C u0 p1 c-1 {1,T}

I'm unsure precisely why you're getting the error you are. Essentially the problem is that you're getting a catalyst site with two single bonds, which there is no atom type defined for, but I'm not sure how this recipe is causing a catalyst site to be bonded to two different things. However, I think the above should change what's going on in the structures considerably.

**Comment by dronekill** [comment]
Initially, we used smiles structure for CO and as per your recommendation ,changed it to this adjacency list for CO. We also tried various termination time criteria and got no increase in total reaction count. Further, we varied conversion criteria but our simulation got stuck after a certain point. Please suggest something in this direction.
