### ISSUE TITLE
collision rate violators during mechanism generation

### ISSUE THREAD

**Issue by shrabanti1937** [ReactionMechanismGenerator/RMG-Py#1898]
### Topic
General area which your question is related to.

 - [ ] Running an RMG job

### Question
Hi,
I am trying to generate a mechanism for anisole oxidation. 
I started the initial input file  with  'BurkeH2O2', 'DFT_QCI_thermo','Chernov','primaryThermoLibrary' as thermo library and BurkeH2O2inN2, aramco2.0, Chernov as kinetic library. Considered the reactor conditions for 400-1500 K temperature, 1-10 atm pressure and equivalent ratio 1. Initially able to get  the simulation converge considering larger tolerances.
However, after a complete simulation it is generating a file of collision rate violators. I am wondering how it is affecting the main mechanism? How can I overcome this violation. Can I get some suggestions regarding this? 

Thanks.

**Comment by alongd** [comment]
The collision rate violators file details the direction and factor by which a reaction violates the collision rate limit. Often, the case is that some species' thermo have bad estimations, which significantly affects the reverse rate, resulting in collision violations. Since RMG could not resolve this on-the-fly, it alerts the user using this log.

You should look at all entries in this file, and asses whether the reason for the violation is bad rate estimation or bad thermo estimation. Also, consider running a sensitivity analysis for your observable(s), and see whether you're sensitive to any of these rates. Eventually, better data needs to be added to RMG (rates and/or thermo) to overcome this.

**Comment by shrabanti1937** [comment]
Thanks @alongd for your reply.
Just to be clear, eventually by adding better data to RMG, do you mean for the given case it may eventually required pressure dependent calculation or quantum calculation? Or I can also try by adjusting the  input file used in generating mechanism?

**Comment by alongd** [comment]
Hi,
Many methods (or a combination) could work.
For instance, you could try RMG's ML tool for thrmo estimation (see the documentation).
Also a literature search could help for attaining better data.
Of course, if you have the capability, then direct QM computations are always great.
Be sure to also push your addittions back to the RMG-database repo.
I would start by first identifying the parameters you care about.

**Comment by shrabanti1937** [comment]
Thanks again for your help. I will work based on the information.
