### ISSUE TITLE
Output Cantera YAML files directly.

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#2078]
### Motivation or Problem
Currently RMG can only output mechanisms in CHEMKIN format.
We then translate them into Cantera's CTI format using the ck2cti script.

1. Cantera is no longer supporting CTI format, but has switched to a YAML format. (Official release of Cantera 2.5 was last week)
2. New features coming soon to Cantera (like Blowers Masel kinetics) are not available in CHEMKIN syntax.
3. Electrochemistry, already in Cantera, uses the YAML format and cannot be translated from CHEMKIN syntax.
4. The RMS code also reads YAML format (I _hope_ the same flavor of YAML as Cantera?)

### Desired Solution
I propose RMG should be able to output Cantera- and RMS-compatible YAML mechanisms directly, rather than only outputting CHEMKIN format.

### Potential Alternatives
Invent new pseudo-CHEMKIN syntax for a CHEMKIN code that doesn't exist, and hack Cantera's chemkin-to-yaml script to interpret it into Cantera YAML format, so RMG continues to only output CHEMKIN(ish) mechanisms and use the translator.

**Comment by mjohnson541** [comment]
So RMG already outputs the .rms format without generating Chemkin first. Unfortunately since the Cantera format didn't exist when I made the RMS format it isn't the same format, but I'm planning to shift over to it since it makes it easier to read reactions. I haven't seen the final Cantera yaml format, but I suspect it's pretty similar to the RMS format, with some differences in key names and top level dictionary organization. The yml.py file (that has the .rms output functions) is probably a solid copy paste basis for starting to make a writer for Cantera yaml.

**Comment by sevyharris** [comment]
@mefuller, I'm also working on a project where this functionality would be very useful to have. Let me know if you need a reviewer for your PR
