### ISSUE TITLE
Kinetics search on the RMG website can't find the reactions rates

### ISSUE THREAD

**Issue by Tingchenlee** [ReactionMechanismGenerator/RMG-Py#2079]
### Bug Description
Kinetics search on the RMG website can't calculate the reactions rates for some mechanisms, which look like this one:
![image](https://user-images.githubusercontent.com/56702445/108298101-5c10a980-716a-11eb-8757-0b3b6ae3fbc4.png)
While their reverse reactions rates can be found:
![image](https://user-images.githubusercontent.com/56702445/108298166-7ea2c280-716a-11eb-9ee6-4f67be189ff4.png)
### How to Reproduce
```
1 N u0 p1 c0 {2,S} {3,S} {4,S}
2 H u0 p0 c0 {1,S}
3 H u0 p0 c0 {1,S}
4 X u0 p0 c0 {1,S}
``` 
react with
```
1 N u0 p1 c0 {2,S} {3,S} {4,S}
2 H u0 p0 c0 {1,S}
3 H u0 p0 c0 {1,S}
4 X u0 p0 c0 {1,S}
```

### Expected Behavior
RMG can calculate the rates of these reactions

### Installation Information
   - RMG-website
  
### Additional Context
other examples:
 - N2H4_X ⇔ N2H4 + X , in Surface_Adsorption_vdW  
 - H2_X ⇔ H2 + X , in Surface_Adsorption_vdW  
 - H_X + NH2_X ⇔ NH3 + X + X , in Surface_Adsorption_Dissociative  
 - N2H_X ⇔ H_X + N2  , in Surface_EleyRideal_Addition_Multiple_Bond
 - X_O2_X ⇔ O2 + X + X , in Surface_Adsorption_Bidentate 
 - N_X + N_X ⇔ N2 + X + X , in Nitrogen

**Comment by rwest** [comment]
Probably a problem reversing the rate from the sticking coefficient. In order to calculate the reverse rate, from a sticking coefficient, it will need to assume a surface site density. Which might not be specified in the context of a generic web search.

**Comment by rwest** [comment]
Perhaps this is OK to not calculate the reverse, and just tell users to use it in the forward (sticking) direction. 

But in that case the message displayed to users on the website could be clearer.

**Comment by xiaoruiDong** [comment]
Sorry, I just saw your reply, @rwest.

Some of my investigations are included in 
https://github.com/ReactionMechanismGenerator/RMG-website/issues/212#issuecomment-781636694

For short, in order to get those rates, RMG-website is calling `generate_reverse_rate_coefficient()` of `Reaction`, but `StickingCoefficient` and some other classes don't support this method. And I guess you just mentioned the reason why they are not supported. I can try to modify the message, but need to exactly which `KineticsModels` should have such special treatment. Besides, `StickingCoefficient` and `StickingCoefficientBEP`, what else? classes defined in `surface.pyx`?
