### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by shikharnigam8** [ReactionMechanismGenerator/RMG-Py#2096]
[shikhar.zip](https://github.com/ReactionMechanismGenerator/RMG-Py/files/6257800/shikhar.zip)

### Bug Description
I have created reaction libraries (2) and families (11) to produce a mechanism for pyrolysis of small molecule. I also updated thermo data to facilitate better kinetic estimation. However, on running every time RMG is throwing a type error which says: "'NoneType' object is not iterable"

### How To Reproduce
All necessary files are attached. 

### Expected Behavior
The RMG model execution should terminate without any error.

### Installation Information
Describe your installation method and system information.
 - OS : Windows 10 with Ubuntu 18.04 LTS (Linux subsystem)
 - Installation method: Source with anaconda
 - RMG version information:
   
   - RMG-Py: Latest version
   - RMG-database: Latest database

**Comment by mjohnson541** [comment]
So first off this is occurring in processing after the run so RMG has already converged and the output should be entirely usable. 

This bug is occurring during collision limit violator detection and on master the traceback sends me to a warning about loss of RMG-java format support. However, my best guess is this wasn't run on current master and is related to having species_list be None on the special .to_chemkin() call on a ThirdBody kinetics collision violator. If self.reaction_model.core.species was None during this call that would explain things, but that would be a bit odd.

**Comment by shikharnigam8** [comment]
@mjohnson541 Thanks a lot for replying.
I ran this same simulation earlier and the model terminated (with 318 reactions) without any error.
But now the same model is throwing the error and not producing the desired output. Can you please suggest me how to get rid off this error and terminate my simulation with desired number of reactions.

**Comment by shikharnigam8** [comment]
Thank you!

**Comment by PoojaNem** [comment]
> @mjohnson541 Thanks a lot for replying. I ran this same simulation earlier and the model terminated (with 318 reactions) without any error. But now the same model is throwing the error and not producing the desired output. Can you please suggest me how to get rid off this error and terminate my simulation with desired number of reactions.

@shikharnigam8, I am facing a similar issue while generating a kinetic model for n-propylcyclohexane. Could you please provide me some hints on how you resolved it? 
@mjohnson541, please let me know if I should submit a separate query for this. 

Thank you
