### ISSUE TITLE
Pyrolysis libraries

### ISSUE THREAD

**Issue by Jakubanoo** [ReactionMechanismGenerator/RMG-Py#2151]
### Context
I am trying to speed up a pyrolysis of diethyl sulfide simulation, therefore trying to use a good seed mechanism and thermo library.

### Question
I read at http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/input.html, that oxidation library should not be used for pyrolysis model.
So if i wanted to use a 'xyz' library, that also contains oxidation reactions, i should create my own library by "deleting" these oxidation reactions from 'xyz'?

### Installation Information
 - OS: Ubuntu 18
 - Installation method: installation from source,
 - RMG version information: 
   
   - RMG-Py: 3.1.0-59-g74b176a77
   - RMG-database: 3.0.0-206-g833577ec

Thank you in advance.

**Comment by mjohnson541** [comment]
Hmm...so I think the reason the documentation is probably telling you that is because if you do that you're going to end up with a bunch of reactions and species in your model that are completely unimportant. It shouldn't inherently have an effect on the accuracy of the model you generate. If you add them as a reaction library the reactions get added to the edge instead of the core and it will not select the oxygen containing reactions because they won't have any flux, but if you want to add it as a seed (to the core) I think it's probably fine to use the oxidation library for initial testing at least. But yes, you should be able to just copy the library files over and go through the reactions file deleting all of the oxidation reactions and then reindexing the reactions.

**Comment by Jakubanoo** [comment]
Thank you,
I thought using oxidation libraries would somehow screw the obtained mechanism.
