### ISSUE TITLE
Arkane Missing atom energies

### ISSUE THREAD

**Issue by Jakubanoo** [ReactionMechanismGenerator/RMG-Py#2179]
Hey guys,

I'm trying to run a simple Arkane test job of C2H6 using data generated by Qchem.
I've calculated energy, frequencies and geometry for the job using Qchem 5.4.
However, i'm running into following error:

```
Loading statistical mechanics parameters for C2H6...
Traceback (most recent call last):
  File "/home/jakub/RMG/RMG-Py/arkane/encorr/corr.py", line 118, in get_atom_correction
    atom_energies = data.atom_energies[energy_level]
KeyError: LevelOfTheory(method='wb97xd',basis='augccpvtz',software='qchem')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jakub/RMG/RMG-Py/arkane/encorr/corr.py", line 121, in get_atom_correction
    atom_energies = data.atom_energies[energy_level.simple()]
KeyError: LevelOfTheory(method='wb97xd',basis='augccpvtz',software='qchem')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Arkane.py", line 59, in <module>
    arkane.execute()
  File "/home/jakub/RMG/RMG-Py/arkane/main.py", line 214, in execute
    job.execute(output_directory=self.output_directory, plot=self.plot, pdep=is_pdep(self.job_list))
  File "/home/jakub/RMG/RMG-Py/arkane/statmech.py", line 208, in execute
    self.load(pdep, plot)
  File "/home/jakub/RMG/RMG-Py/arkane/statmech.py", line 516, in load
    atoms, self.atomEnergies)
  File "/home/jakub/RMG/RMG-Py/arkane/encorr/corr.py", line 123, in get_atom_correction
    raise AtomEnergyCorrectionError(f'Missing atom energies for {energy_level}')
arkane.exceptions.AtomEnergyCorrectionError: Missing atom energies for LevelOfTheory(method='wb97xd',basis='augccpvtz',software='qchem')

```
My ethane.py:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

bonds = {
	'C-C': 1, 
    	'C-H': 6,
}

linear=False

externalSymmetry = 6

spinMultiplicity = 1

opticalIsomers = 1

energy = Log('ethane.log')

geometry = Log('ethanegeom.log')

frequencies = Log('ethane.log')

```
Input.py:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

modelChemistry = LevelOfTheory(
	method='wb97x-d',
	basis='aug-cc-pvtz',
	software='qchem'
)

useHinderedRotors = True
useBondCorrections = False

species('C2H6', 'ethane.py',
        structure=SMILES('CC'))

statmech('C2H6')
thermo('C2H6', 'NASA')
```
Thanks in advance, i can drop more input file if needed.

**Comment by kspieks** [comment]
Thanks for asking about this. The issue is that the RMG-database only supports `LevelOfTheory(method='wb97xd',basis='augccpvtz',software='gaussian')` ([source](https://github.com/ReactionMechanismGenerator/RMG-database/blob/master/input/quantum_corrections/data.py#L349-L352)) for Atom Energy Corrections, so specifying Q-Chem with this method and basis is causing the error. We specify the software used because I believe our group had noticed cases where different software give different answers. Admittedly, I don’t remember which cases these were but I’ve tagged Mark Payne (@amarkpayne) who might remember. Also, @amarkpayne would it probably be okay to use these AECs from Gaussian for a calculation with Q-Chem? It'd be the fastest solution; I think I've asked about this before and just forget the answer.

Going forward, here are a few options to consider:
1. If you’re set on using Q-Chem, perhaps it is worth recalculating the ethane test example with a different Level of Theory (LoT) in Q-Chem that is supported by `RMG-database/input/quantum_corrections/data.py`. Depending on what software is available to you, you could also use Gaussian for the same LoT or use a different one that is also supported.
2. If using this exact LoT is very important to you, it will be probably be necessary to recalculate the atom energy corrections (and possibly the bond additivity corrections) for this LoT. I'd recommend checking out these [notebooks](https://github.com/ReactionMechanismGenerator/RMG-database/pull/501/commits) if you're interested in doing the QM calculations and subsequent fitting.

**Comment by amarkpayne** [comment]
Thanks for answering this @kspieks ! I agree with your answer. For added context, I believe wb97xd is one of the methods where Gaussian and QChem give different numbers (Anything involving dispersion models such as D3 seem to be the issue). 

I think the numbers you'll get by taking the fast solution above (changing the software in the input file to Gaussian even though you used QChem) will be good, but if you get to the point that you need publication accuracy and want to be absolutely sure then the AECs will need to match the software for this particular DFT functional.

**Comment by Jakubanoo** [comment]
Thank you very much, that helps a lot!
