### ISSUE TITLE
'make eg2' failed

### ISSUE THREAD

**Issue by NUSCondy** [ReactionMechanismGenerator/RMG-Py#2204]
### Bug Description
Dear Sir,
I try to test if my installation is successful so I use 'make eg2' to test both RMG and QM. FYI, I already have mopac. However, I encountered the following error:
**Filling in rate rules in kinetics families by averaging...
Traceback (most recent call last):
  File "rmg.py", line 118, in <module>
    main()
  File "rmg.py", line 100, in main
    rmg_profiler.runctx(command, global_vars, local_vars)
  File "/home/zhuqiren/anaconda3/envs/rmg_env/lib/python3.7/cProfile.py", line 100, in runctx
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/zhuqiren/RMG-Py/rmgpy/rmg/main.py", line 695, in execute
    self.initialize(**kwargs)
  File "/home/zhuqiren/RMG-Py/rmgpy/rmg/main.py", line 507, in initialize
    self.reaction_model.add_species_to_edge(spec)
  File "/home/zhuqiren/RMG-Py/rmgpy/rmg/model.py", line 1142, in add_species_to_edge
    self.edge.phase_system.phases["Default"].add_species(spec)
  File "/home/zhuqiren/RMG-Py/rmgpy/rmg/reactors.py", line 232, in add_species
    spec = to_rms(spc)
  File "/home/zhuqiren/RMG-Py/rmgpy/rmg/reactors.py", line 453, in to_rms
    rad = rms.getspeciesradius(atomnums, bondnum)
NameError: name 'rms' is not defined
Coverage.py warning: Module Arkane.py was never imported. (module-not-imported)
Coverage.py warning: Module rmg.py was never imported. (module-not-imported)
make: *** [Makefile:105: eg2] Error 1**

I am running on WSL ubuntu 20.0. I noticed that Julia is needed for MacOs in the installation guide. Need I also install a Julia or Python-jl? How could I avoid this problem?

### How To Reproduce
make eg2

### Installation Information
Use the up to date development RMG and data set.

**Comment by mjohnson541** [comment]
On ubuntu the only thing you probably really need to do is update your conda environment (which will install everything needed) and then tell pyrms to install the julia stuff (the command is in the installation instructions).  But depending on your familiarity with conda it may simpler to just fully reinstall. The full updated installation instructions are here: http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaDeveloper.html. Additionally when you launch RMG now you need to use python-jl to launch the executable instead of python (this is fully described in the installation instructions).

**Comment by NUSCondy** [comment]
Thank you so much for the explanation! Since I use the previous version, which does not to be run using python. Now I use replace the console with python-jl, it works now. However, I think maybe the 'make eg' there is a little bit confusing since python-jl cannot be chosen.
