### ISSUE TITLE
Invalid k(E) at high T for BM rate rule estimate

### ISSUE THREAD

**Issue by davidfarinajr** [ReactionMechanismGenerator/RMG-Py#2238]
@ChrisBNEU and I are testing my halogens pdep PR with the [1,3-hexadiene pyrolysis](http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/examples.html#hexadiene-pyrolysis) example (without mopac).   

RMG is crashing on main branch with this error
```
Warning: For path reaction [CH2]C(C=CCC)C([CH2])C=CCC(50) <=> [CH2]C=CC(CC)C([CH2])C=CCC(47):
Warning:     Expected kf(1896.74 K) = 2.39965e+11
Warning:       Actual kf(1896.74 K) = 7.72355e+10
Warning:     Expected Keq(1896.74 K) = 10.7667
Warning:       Actual Keq(1896.74 K) = 0
Error: Invalid k(E) values computed for path reaction "[CH2]C(C=CCC)C([CH2])C=CCC(50) <=> [CH2]C=CC(CC)C([CH2])C=CCC(47)".
Error: Increasing number of grains did not decrease error enough (Current badness: 0.5, previous 0.5). Something must be wrong with network PDepNetwork #13
```

<img width="999" alt="Screen Shot 2021-12-02 at 1 20 45 PM" src="https://user-images.githubusercontent.com/32377555/144480474-34aede29-a165-44ce-bb5b-5c0ef3c4e363.png">

[website kinetics](https://rmg.mit.edu/database/kinetics/reaction/reactant1=multiplicity%203%0A1%20%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B7,S%7D%20%7B11,S%7D%20%7B13,S%7D%0A2%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B8,S%7D%20%7B12,S%7D%20%7B14,S%7D%0A3%20%20C%20u0%20p0%20c0%20%7B5,S%7D%20%7B9,S%7D%20%7B15,S%7D%20%7B16,S%7D%0A4%20%20C%20u0%20p0%20c0%20%7B6,S%7D%20%7B10,S%7D%20%7B17,S%7D%20%7B18,S%7D%0A5%20%20C%20u0%20p0%20c0%20%7B3,S%7D%20%7B19,S%7D%20%7B20,S%7D%20%7B21,S%7D%0A6%20%20C%20u0%20p0%20c0%20%7B4,S%7D%20%7B22,S%7D%20%7B23,S%7D%20%7B24,S%7D%0A7%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B9,D%7D%20%7B25,S%7D%0A8%20%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B10,D%7D%20%7B27,S%7D%0A9%20%20C%20u0%20p0%20c0%20%7B3,S%7D%20%7B7,D%7D%20%7B26,S%7D%0A10%20C%20u0%20p0%20c0%20%7B4,S%7D%20%7B8,D%7D%20%7B28,S%7D%0A11%20C%20u1%20p0%20c0%20%7B1,S%7D%20%7B29,S%7D%20%7B30,S%7D%0A12%20C%20u1%20p0%20c0%20%7B2,S%7D%20%7B31,S%7D%20%7B32,S%7D%0A13%20H%20u0%20p0%20c0%20%7B1,S%7D%0A14%20H%20u0%20p0%20c0%20%7B2,S%7D%0A15%20H%20u0%20p0%20c0%20%7B3,S%7D%0A16%20H%20u0%20p0%20c0%20%7B3,S%7D%0A17%20H%20u0%20p0%20c0%20%7B4,S%7D%0A18%20H%20u0%20p0%20c0%20%7B4,S%7D%0A19%20H%20u0%20p0%20c0%20%7B5,S%7D%0A20%20H%20u0%20p0%20c0%20%7B5,S%7D%0A21%20H%20u0%20p0%20c0%20%7B5,S%7D%0A22%20H%20u0%20p0%20c0%20%7B6,S%7D%0A23%20H%20u0%20p0%20c0%20%7B6,S%7D%0A24%20H%20u0%20p0%20c0%20%7B6,S%7D%0A25%20H%20u0%20p0%20c0%20%7B7,S%7D%0A26%20H%20u0%20p0%20c0%20%7B9,S%7D%0A27%20H%20u0%20p0%20c0%20%7B8,S%7D%0A28%20H%20u0%20p0%20c0%20%7B10,S%7D%0A29%20H%20u0%20p0%20c0%20%7B11,S%7D%0A30%20H%20u0%20p0%20c0%20%7B11,S%7D%0A31%20H%20u0%20p0%20c0%20%7B12,S%7D%0A32%20H%20u0%20p0%20c0%20%7B12,S%7D%0A__product1=multiplicity%203%0A1%20%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B3,S%7D%20%7B7,S%7D%20%7B13,S%7D%0A2%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B8,S%7D%20%7B11,S%7D%20%7B14,S%7D%0A3%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B5,S%7D%20%7B15,S%7D%20%7B16,S%7D%0A4%20%20C%20u0%20p0%20c0%20%7B6,S%7D%20%7B9,S%7D%20%7B17,S%7D%20%7B18,S%7D%0A5%20%20C%20u0%20p0%20c0%20%7B3,S%7D%20%7B19,S%7D%20%7B20,S%7D%20%7B21,S%7D%0A6%20%20C%20u0%20p0%20c0%20%7B4,S%7D%20%7B22,S%7D%20%7B23,S%7D%20%7B24,S%7D%0A7%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B10,D%7D%20%7B25,S%7D%0A8%20%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B9,D%7D%20%7B26,S%7D%0A9%20%20C%20u0%20p0%20c0%20%7B4,S%7D%20%7B8,D%7D%20%7B27,S%7D%0A10%20C%20u0%20p0%20c0%20%7B7,D%7D%20%7B12,S%7D%20%7B28,S%7D%0A11%20C%20u1%20p0%20c0%20%7B2,S%7D%20%7B29,S%7D%20%7B30,S%7D%0A12%20C%20u1%20p0%20c0%20%7B10,S%7D%20%7B31,S%7D%20%7B32,S%7D%0A13%20H%20u0%20p0%20c0%20%7B1,S%7D%0A14%20H%20u0%20p0%20c0%20%7B2,S%7D%0A15%20H%20u0%20p0%20c0%20%7B3,S%7D%0A16%20H%20u0%20p0%20c0%20%7B3,S%7D%0A17%20H%20u0%20p0%20c0%20%7B4,S%7D%0A18%20H%20u0%20p0%20c0%20%7B4,S%7D%0A19%20H%20u0%20p0%20c0%20%7B5,S%7D%0A20%20H%20u0%20p0%20c0%20%7B5,S%7D%0A21%20H%20u0%20p0%20c0%20%7B5,S%7D%0A22%20H%20u0%20p0%20c0%20%7B6,S%7D%0A23%20H%20u0%20p0%20c0%20%7B6,S%7D%0A24%20H%20u0%20p0%20c0%20%7B6,S%7D%0A25%20H%20u0%20p0%20c0%20%7B7,S%7D%0A26%20H%20u0%20p0%20c0%20%7B8,S%7D%0A27%20H%20u0%20p0%20c0%20%7B9,S%7D%0A28%20H%20u0%20p0%20c0%20%7B10,S%7D%0A29%20H%20u0%20p0%20c0%20%7B11,S%7D%0A30%20H%20u0%20p0%20c0%20%7B11,S%7D%0A31%20H%20u0%20p0%20c0%20%7B12,S%7D%0A32%20H%20u0%20p0%20c0%20%7B12,S%7D%0A__res=True)

Not sure if this is due to a bad microcanonical rate due to poor density of state estimates from group freqs, or a poor high pressure rate at 1900 K (or both).  Since the high P kinetics are fit to 300 - 1500 K range, and the T exponent is ~22, the rate may be too fast at T > 1500 K

**Comment by kspieks** [comment]
Thanks @mjohnson541 for notifying me of this issue. I recently created the 1,3 sigmatropic rearrangement reaction family ([PR 532](https://github.com/ReactionMechanismGenerator/RMG-database/pull/532) on RMG-database) that is involved in this issue and wanted to share an update.

Based on the picture above, the problem is with this node in the rate tree: `Root_N-1R!H-inRing`. Previously, the estimate at this node was rather interesting... ([link](https://github.com/ReactionMechanismGenerator/RMG-database/pull/550/commits/e6194d42d9499e25572edc49b9f506b13fea83d3#diff-2f2b14b248e079e27066989894cf36d85cef7f3b5cf1c6594aae91bff16b42baL39-L43))
```
label = "Root_N-1R!H-inRing",
ArrheniusBM(A=(3.50759e-62,'s^-1'), n=22.1275, w0=(750402,'J/mol'), E0=(-20429.3,'J/mol') ...
Total Standard Deviation in ln(k): 13.494121433083981"""),
```

However, I recently made a new PR on RMG-database ([PR 550](https://github.com/ReactionMechanismGenerator/RMG-database/pull/550)) that adds a thermo library for the species involved in the training reactions I had added that were used to fit this tree. On the new PR, the rate estimate for this specific node looks more reasonable and the standard deviation decreased ([link](https://github.com/ReactionMechanismGenerator/RMG-database/pull/550/commits/e6194d42d9499e25572edc49b9f506b13fea83d3#diff-2f2b14b248e079e27066989894cf36d85cef7f3b5cf1c6594aae91bff16b42baR56-R58))
```
label = "Root_N-1R!H-inRing",
kinetics = ArrheniusBM(A=(1.69526e+13,'s^-1'), n=-0.0541346, w0=(705700,'J/mol'), ...
Total Standard Deviation in ln(k): 8.759382282596956"""),
```

I do not know how relevant this change in the rate estimate is vs. other potential issues, perhaps RMG struggling with biradicals? None of the training reactions I had added involve radicals (let alone biradicals) so perhaps the thermo I added for the stable species will not matter for this specific reaction. Anyways, just wanted to share this info
