### ISSUE TITLE
Unable to run binary RMG: ModuleNotFoundError

### ISSUE THREAD

**Issue by mefuller** [ReactionMechanismGenerator/RMG-Py#2253]
### Bug Description
Binary RMG installation is missing modules when called

### How To Reproduce
Installing according to instructions at https://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaUser.html (but using miniconda since on storage-limited server)
From `rmg.py input.py`, following error results immediately:
```
  File "/home/fuller/miniconda3/envs/rmg_bin/bin/rmg.py", line 48, in <module>
    from rmgpy.rmg.main import RMG, initialize_log, process_profile_stats, make_profile_graph
  File "/home/fuller/Code/RMG-Py/rmgpy/rmg/main.py", line 55, in <module>
    from rmgpy.rmg.model import Species, CoreEdgeReactionModel
  File "/home/fuller/Code/RMG-Py/rmgpy/rmg/model.py", line 41, in <module>
    import rmgpy.data.rmg
  File "/home/fuller/Code/RMG-Py/rmgpy/data/rmg.py", line 38, in <module>
    from rmgpy.data.base import ForbiddenStructures
  File "/home/fuller/Code/RMG-Py/rmgpy/data/base.py", line 44, in <module>
    from rmgpy.kinetics.uncertainties import RateUncertainty
  File "/home/fuller/Code/RMG-Py/rmgpy/kinetics/__init__.py", line 30, in <module>
    from rmgpy.kinetics.model import KineticsModel, PDepKineticsModel, TunnelingModel, \
ModuleNotFoundError: No module named 'rmgpy.kinetics.model'
```

### Expected Behavior
RMG should run or have pulled in the necessary additional components in installation

### Installation Information
Describe your installation method and system information.
 - OS: EL7 (3.10.0-1127.19.1.el7.x86_64)
 - Installation method: binary, miniconda
 - RMG version information:
# Name                    Version                   Build  Channel
rmg                       3.1.0            py37h1515d6f_0    rmg
rmgdatabase               3.1.0                    py37_0    rmg

**Comment by amarkpayne** [comment]
I think I have an idea of what is going on. It looks like you are calling the rmg binary as you wanted to do (see the top line in the traceback, the path is `/home/fuller/miniconda3/envs/rmg_bin/bin/rmg.py`, which is inside your conda environment for the binary). However, in the next lines, it is calling files from what I am guessing is your source installation (see files like `/home/fuller/Code/RMG-Py/rmgpy/rmg/model.py`). 

Given this, I think this is caused by a PATH issue, where your source installation is higher on your path than the binary. It is possible though that this is simply that it can't find the binary files in your `rmg_bin` environment, and then falls back to the source installation which is lower on your PATH.

Can you look through your .bashrc file and comment out anything that would put the source installation on your PATH or PYTHONPATH? Then open up a new terminal and try running the RMG binary again (make sure you activate the conda environment).

**Comment by amarkpayne** [comment]
Just to follow-up, I also tried installing the binary version of RMG just now in a clean conda environment on Linux (Manjaro) and was able to run the minimal example file. I double checked all of my PATH variables to make sure that this was the only version on PATH, so I think the binary version is still okay. 

Let me know if you are able to get anywhere with the PATH variable investigation on your end. Depending on what you find we can go from there.

**Comment by mefuller** [comment]
Good call - $PATH wasn't causing any issues, but it seems $PYTHONPATH was the problem:
I have several locations added to it by default for development and the binary throws the above error with $PYTHONPATH set. Once I clear/unset it, the binary runs.
However, after stopping and/or killing the RMG program, $PYTHONPATH is still unset, so it would be interesting to know what is happening here: where does the binary search by default and why does having (any/additional) locations in the $PYTHONPATH cause it to not find something? I'm trying to read the error trace and make sense of this still.
