### ISSUE TITLE
Calculate Reaction Degeneracy Fails in Intra_R_Add_Endocyclic Family

### ISSUE THREAD

**Issue by sevyharris** [ReactionMechanismGenerator/RMG-Py#2296]
### Bug Description
RMG fails to calculate a reaction's degeneracy  ( [CH2]C=CC=CC=C <=> [CH]1C=CC=CCC1 in reaction family Intra_R_Add_Endocyclic) while attempting to add_rules_from_training. This occurred while loading the database for an uncertainty calculation.

### How To Reproduce
Try running the following code:

```
from rmgpy.data.rmg import RMGDatabase
from rmgpy import settings

database = RMGDatabase()
database.load(
    settings['database.directory'],
    thermo_libraries=[
        'BurkeH2O2',
        'CurranPentane',
        'FFCM1(-)',
        'primaryThermoLibrary',
        'thermo_DFT_CCSDTF12_BAC',
        'DFT_QCI_thermo',
        'CBS_QB3_1dHR',
    ],
    kinetics_families=[
        'Intra_R_Add_Endocyclic',
    ],
)

for familyLabel, family in database.kinetics.families.items():
    family.add_rules_from_training(thermo_database=database.thermo)


```

### Expected Behavior
I expect the database to load without issue because it has in the recent past

### Installation Information
Describe your installation method and system information.
 - OS: WSL: Ubuntu 20.04.1
 - Installation method: source
 - RMG version information:
   - RMG-Py: 3.0.0-938-g4377398cf
   - RMG-database: 3.0.0-539-g89564b633

### Additional Context
Here's the error traceback:
```
Unable to calculate degeneracy for reaction [CH2]C=CC=CC=C <=> <Molecule "[CH]1C=CC=CCC1"> in reaction family Intra_R_Add_Endocyclic. Expected 1 reaction but generated 0
  File "/home/moon/rmg/RMG-Py/rmgpy/data/kinetics/family.py", line 1948, in calculate_degeneracy
    'but generated {2}').format(reaction, self.label, len(reactions)))
  File "/home/moon/rmg/RMG-Py/rmgpy/data/kinetics/family.py", line 1303, in add_rules_from_training
    new_degeneracy = self.calculate_degeneracy(item)
  File "/home/moon/rmg/my_examples/debug_degeneracy/min_err.py", line 22, in <module>
    family.add_rules_from_training(thermo_database=database.thermo)
```

**Comment by xiaoruiDong** [comment]
Same error saw here. https://github.com/ReactionMechanismGenerator/RMG-website/issues/241. But that issue seems to go away after the website was updated for unknown reason.

I looked at the hashes of your commits, and both RMG-Py and RMG-database are up to the latest main. Using the same version, I can replicate the issue. Looking into this now.

- OS: MacOS 12.3.1

**Comment by sevyharris** [comment]
> Same error saw here. [ReactionMechanismGenerator/RMG-website#241](https://github.com/ReactionMechanismGenerator/RMG-website/issues/241). But that issue seems to go away after the website was updated for unknown reason.
> 
> I looked at the hashes of your commits, and both RMG-Py and RMG-database are up to the latest main. Using the same version, I can replicate the issue. Looking into this now.
> 
> * OS: MacOS 12.3.1

Thank you for looking into it!

**Comment by xiaoruiDong** [comment]
Part of the reason is that `reactantNum` and `productNum` are not defined in the `groups.py` of the family Intra_R_Add_Endocyclic.

After fixing this, I still got the same error. The problem is
https://github.com/ReactionMechanismGenerator/RMG-Py/blob/4377398cf30eff9f28cf2ae65306cdd9dcb3d204/rmgpy/data/kinetics/family.py#L1302-L1303
at line 1302, the templated generated for this reaction is `['Root_N-1R!H-inRing']`;
but inside `self.calculate_degeneracy(item)` 
https://github.com/ReactionMechanismGenerator/RMG-Py/blob/4377398cf30eff9f28cf2ae65306cdd9dcb3d204/rmgpy/data/kinetics/family.py#L1932-L1938
at line 1933 generated 2 reactions but with different templates: 
- `['Root_N-1R!H-inRing_Ext-3R!H-R_Sp-4R!H-3R!H_Ext-1R!H-R_N-5R!H-inRing_Sp-5R!H-1R!H_N-2R!H->S_Ext-4R!H-R_N-Sp-6R!H-4R!H_Ext-5R!H-R_Int-7R!H-6R!H']`.

The difference in template cause line 1937 raise an warning `No reactions matched the specified template, frozenset({'Root_N-1R!H-inRing'})` and empty the `reactions` list.

**Comment by xiaoruiDong** [comment]
One thing really weird about the newly merged families are *labels are expected to be *1, *2, *3, but a few cases in the species dictionary have label index over 3 (*4, *5, *6, *7). Not sure if this is the case causing this issue.

**Comment by xiaoruiDong** [comment]
@sevyharris, the short answer is `add_rules_from_training` and `fill_rules_by_averaging_up` are not designed for ATG rate rules and shouldn't be called on ATG families. 

However, this is a good catch helping us find multiple issues in both RMG-database and RMG-Py.
https://github.com/ReactionMechanismGenerator/RMG-database/pull/576
https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2297
https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2299

Let me know if you other questions.
