### ISSUE TITLE
[installation] developer installation (from source) and environment.yml version conflicts

### ISSUE THREAD

**Issue by anandijain** [ReactionMechanismGenerator/RMG-Py#2307]
I am following the ARC installation guide, which recommends using the developer installation of RMG-Py. So I'm following https://reactionmechanismgenerator.github.io/ARC/installation.html and http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaDeveloper.html

I'm on `3.1.0-546-g6c45bf2c5` of Rmg-Py. I'm using Ubuntu-20.04. When running `conda env create -f environment.yml`
```
~/rmg2/RMG-Py$ conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                       -  
Solving environment: - 
```
And this has been going on for ~20 minutes or so, I just want to run the ARC example. What do I do?

I got the same issues with `conda env create -f environment.yml` with the ARC environment.yml

**Comment by JacksonBurns** [comment]
@anandijain apologies for the delay on replying to this! As you can see, we are doing some cleanup.

The documentation has been updated a few times since this was originally opened. In particular, we now recommend using the `libmamba` solver, and we have simplified our environment file somewhat.

Could you pull the latest stable version of RMG (main) and try going through the installation instructions again? Please let us know how it proceeds.

**Comment by JacksonBurns** [comment]
Will close as completed for now.
