### ISSUE TITLE
Stop using (and maybe remove) the old Mopac from RMG's conda channel

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#2328]
Via email from @godotalgorithm (thank you for reporting it, Jonathan!)
> I'm maintaining MOPAC, which became an open-source project last year https://github.com/openmopac/mopac. I'm also maintaining MOPAC's availability on conda-forge https://anaconda.org/conda-forge/mopac. I noticed that you are distributing an older version of MOPAC that requires a license key on your conda channel (rmg), and I'm wondering if your software is tied in some way specifically to that version of MOPAC. If not, could you consider updating the version of MOPAC that you are distributing? There have been several reports now of people who have accidentally downloaded your version of MOPAC on conda and been confused by the need for a license key (which was removed from the open-source version). I'm trying to minimize such sources of confusion when possible.

## Suggestion

- [ ] change our environment file to use the conda-forge mopac
- [ ] update RMG as needed to make this version work
- [ ] update the github actions recipes on RMG-Py, RMG-database, and RMG-tests
- [ ] change our conda recipe to use the conda-forge mopac
- [ ] rebuild binaries
- [ ] do something to warn/help people who inadvertently put the rmg channel as higher priority than the conda-forge channel and accidentally install the wrong one?  options are remove our old one (but that makes it impossible for people to install old versions of RMG, which can be helpful for debugging); add a new one (but then this will gradually become out of date); replace with a dummy package that just prints something like "this is not the package you're looking for. use a different channel" and quits; other ideas?

## Related issues
#2322 
#2251

**Comment by godotalgorithm** [comment]
I could attempt to migrate the development version of RMG-Py to the open-source version of MOPAC and switch the environment to point to the conda-forge version. I don't think too many adjustments are needed, mainly there is some logic looking for a MOPAC license key that is no longer relevant. Other projects under the ReactionMechanismGenerator org refer to MOPAC as well, but the changes outside of RMG-Py look even more minor.

If older versions of RMG depend on your MOPAC version on Conda, then by all means you shouldn't remove it. Part of the confusion is probably that your version of MOPAC presently has more total downloads since it has been available for about 7 years, and the open-source version has been available for less than 2 months. In time, the open-source version should accrue more total downloads and then people making hasty decisions based on number of downloads will pick the right version.

By the numbers, this isn't a big problem: the open-source version has almost 1k downloads already on the conda-forge channel, and I've only received support questions from 2 people so far who had accidentally downloaded it from the RMG channel.

**Comment by rwest** [comment]
> I could attempt...

If you have bandwidth to try this, pull requests are welcome! Else we'll probably get around to it eventually, now that this issue is open. I agree it doesn't sound like a big task.

**Comment by dylanrubini** [comment]
@rwest @godotalgorithm what would be the most appropriate way forward for me to use the open-source version of MOPAC in the meantime? I tried to replace the RMG-PY version of MOPAC with the open-source version. It runs. but crashes after many iterations. Is there a more effective way forward if we don't have the license for the one on the RMG channel? 

Thank you in advance!

**Comment by rwest** [comment]
If it runs, as you say, then I think you have solved the how to run it question?

What remains is why something crashes after many iterations. And for that we'd need more information to help. What type of crash? What error message? When? What situation?

**Comment by acjoven** [comment]
I support this issue and the suggestions from @rwest.

I can confirm the error reported by @dylanrubini. The MOPAC features run fine for me when symlinked to the open source binary. The error occurs when rmgpy/qm/molecule.py attempts to read a successfully generated *.thermo file.

The modification required to fix this would fit into the second suggested bullet point in the original post.
