### ISSUE TITLE
` NameError: name 'rms' is not defined`  for examples 

### ISSUE THREAD

**Issue by Croccs** [ReactionMechanismGenerator/RMG-Py#2333]
### Bug Description
Downloaded the latest developer's version of RMG. When trying to run example jobs, received error:` NameError: name 'rms' is not defined` referring to `rad = rms.getspeciesradius(atomnums, bondnum)` which is line 556 in RMG/RMG-Py/rmgpy/rmg/reactors.py

### How To Reproduce
1. Go to RMG/RMG-Py/testing/eg1
2. `python path/to/rmg.py input.py`

### Expected Behavior
```
MODEL GENERATION COMPLETED
The final model core has 26 species and 71 reactions
The final model edge has 175 species and 391 reactions
```

### Installation Information

 - Ubuntu 20.04.2
 - Python 3.7.13
 - Installation method: Installation by source using Anaconda environment 
 - RMG version information: 3.1.0-598-ge3d0617fb

**Comment by SolmazPTB** [comment]
I just recently installed RMG using Docker, and I tried to run different input.py available in examples/rmg, but I saw the same error: "NameError: name 'rms' is not defined". I could not find any solution in the previous issues. Could you please assist me in understanding how to solve this?

**Comment by JacksonBurns** [comment]
@SolmazPTB have you installed using the version specified in the documention, i.e. with `docker pull reactionmechanismgenerator/rmg:3.2.0`?

**Comment by SolmazPTB** [comment]
@JacksonBurns Yes, Exactly!

**Comment by JacksonBurns** [comment]
Thanks for the quick reply @SolmazPTB. Unfortunately I am not able to reproduce this error. On my own machine, I pulled the Docker image, started the container, and was able to execute examples.

First and foremost, please make sure you are running the command with `python-jl` instead of just `python`, i.e. `python-jl rmg.py examples/rmg/superminimal/input.py`.

If that does not work, my only suggestion is to try deleting and re-pulling the image. You should be able to remove the image with something like `docker image rm reactionmechanismgenerator/rmg:3.2.0` (double check that command with Docker documentation though).

If none of that works, could you post the full error that you are seeing?

**Comment by SolmazPTB** [comment]
@JacksonBurns thanks for your reply. The command I used was exactly the same as you wrote. I deleted and re-pulled the image, but still, I saw the same error: NameError: name 'rms' is not defined.

**Comment by JacksonBurns** [comment]
@SolmazPTB could you try `docker pull reactionmechanismgenerator/rmg:latest` instead of the previous version? This is a release tag that we typically only use for developers, but it might help you out here.

**Comment by JacksonBurns** [comment]
@SolmazPTB seems that your system may have some permission errors. You may want to try installing from source, as described in our documentation: https://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaDeveloper.html
