### ISSUE TITLE
Add CI + Build Checks for Apple Silicon

### ISSUE THREAD

**Issue by JacksonBurns** [ReactionMechanismGenerator/RMG-Py#2369]
### Motivation or Problem
Ever since Apple deigned to release to us their own proprietary hardware, there have been issues across the Python ecosystem that are gradually being resolved over time. Unfortunately since we cannot readily test on this hardware, we often are left high and dry when bugs start popping up.

### Desired Solution
GitHub has plans to release actions runners which will execute on Apple Silicon, and once they are out we should look to implement CI on that hardware in particular. These issue serves as a long-term reminder, and the below tracking list will alert us when is _should_ be possible to implement the above:

- [ ]  Support for VMs on Apple M1 actions/runner-images#2187
- [ ]  Actions: GitHub-hosted macOS runners now offer Apple M1 silicon options (Beta) github/roadmap#528

**Comment by xiaoruiDong** [comment]
Probably related. Something about installing the conda environment on Apple Silicon VM during CI.

For Mac with Apple Silicon, the current environment cannot be successfully installed with all pure ARM-64(/noarch) packages... A few independencies miss versions compiled on Apple Silicon, namely pyDAS, and probably others. All conda packages of pyDAS were created by RMG and Green group alumni, so we need to compile pyDAS anyway if we want to go through this path... I tried but failed even after fixing a few things, like invalid URLs and arguments for compilation. Since I have very little knowledge of program compilation and Fortran, it would be nice if you could help and take a look at what went wrong...

There is a workaround to force all packages installed with their OSX-64 version. I tested this approach, and the installed environment worked fine with RMG. The script I used is
```
conda create -n rmg_env; conda activate rmg_env;`
conda config --env --set subdir osx-64;`
conda install python=3.7`
conda env update -f environment.yml`
```
`conda` replaced by `mamba` should be also workable.

**Comment by JacksonBurns** [comment]
Going to give this one more 4 month go around to see if the tagged issues are resolved, otherwise will just let this close and assume it isn't happening on any reasonable timescale.
