### ISSUE TITLE
superfluous relational operator Warning when building conda environment with latest conda version

### ISSUE THREAD

**Issue by aliirezaKh** [ReactionMechanismGenerator/RMG-Py#2551]
### Bug Description
When I execute the command 'conda env create -f environment.yml' during installation in the terminal, I receive a WARNING: 'conda.models.version:get_matcher(556): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.9.0.*, but conda is ignoring the .* and treating it as 1.9.0
| failed
The installation does not progress beyond this step. How should I resolve this?
### How To Reproduce
Steps to reproduce the behavior.

### Installation Information
Describe your installation method and system information.
 - OS (include version if known): (e.g. Windows 10, Ubuntu 18, macOS 10.13, etc.)
 - Installation method: (e.g. installation from binary or source, with or without anaconda)
 - RMG version information:
   
   - RMG-Py: 
   - RMG-database:

**Comment by JacksonBurns** [comment]
Hi @aliirezaKh thanks for bringing this to our attention. I can confirm that this warning does occur on our builds as well when using the latest version of conda (we haven't dealt with it yet because most of our development team uses older versions).

This warning should be unrelated to the environment not building, though. Could you let us know what platform you are attempting to do the installation on, and which set of installation instructions you are following (from source code, from binaries)? This will help us debug the issue. If you not currently following any set of instructions in particular, check out [these](https://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaDeveloper.html) from our docs.

**Comment by aliirezaKh** [comment]
Hi @JacksonBurns  thank you for your answer. I am following the installation steps from YouTube channel @reactionmechanismgenerator4444 (https://youtu.be/kn7eeHAYbt4?si=uwKWinb3QiePwR2c) and I want to install it on Ubuntu(22.04.3) in Linux and my python version is 3.

**Comment by JacksonBurns** [comment]
The instructions in that video are slightly outdated, please use the updated instructions at the link from my previous comments to make things work.

**Comment by aliirezaKh** [comment]
@JacksonBurns Can you please give me the link here?

**Comment by JacksonBurns** [comment]
@aliirezaKh here is the link: https://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaDeveloper.html

You may also want to follow the installation instructions using Docker: https://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/index.html#recommended-install-docker
This installation procedure is easier, and is our recommended procedure.

**Comment by aliirezaKh** [comment]
Thanks a lot

**Comment by JacksonBurns** [comment]
Going to close this as resolved, please open again if any new issues arise!
