### ISSUE TITLE
Using python-jl for Jupyter Notebook

### ISSUE THREAD

**Issue by calvinp0** [ReactionMechanismGenerator/RMG-Py#2613]
Hi, is it possible to run packages, like RMS, in Jupyter Notebook? Currently, when I use rmg_env as the kernel (linking to python) it cannot do

```
from pyrms import rms
```

I assume this is to do with importing PyCall. Is there a way to use `python-jl` instead of `python` for the kernel in Jupyter?

**Comment by mjohnson541** [comment]
You're correct that the issue is the kernel. If you run `jupyter --paths`, go to any of the data paths (using the rmg_env one might feel like instinctively the right choice, but that one will be deleted if you regenerate the rmg_env so a more general one will likely make your life easier) and then to `kernels`. You should be able to mostly copy a python kernel folder to make a `python-jl` kernel  folder. The only modification that needs made to the copied python kernel is to change the path in the `kernel.json` to the path to the appropriate `python-jl` (which you can get running `which python-jl`).
