### ISSUE TITLE
Species in core is isomorphic to species in the edge

### ISSUE THREAD

**Issue by PoojaNem** [ReactionMechanismGenerator/RMG-Py#2616]
### Bug Description
I am trying to generate a kinetic mechanism for CH2F2 refrigerant using RMG. After completion of the simulation, I get the following warning (image attached below):
Species NNH is isomorphic to species NNH in the edge.
![image](https://github.com/ReactionMechanismGenerator/RMG-Py/assets/131012151/3a67b203-ef91-4c97-a306-4f9037ab706e)

### How To Reproduce
input.py file is attached below for further investigation.

### Installation Information
OS: Windows 11, WSL2, Ubuntu 22.04
Installation method: Installation by Source Using Anaconda Environment for Unix-based Systems: Linux and Mac OSX
RMG version information:
RMG-Py: Latest version
RMG-database: Latest database

[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/14436784/input.txt)

**Comment by JacksonBurns** [comment]
@mjohnson541 I think you originally added this warning, could you take a look at this error?

(was added in this commit: https://github.com/ReactionMechanismGenerator/RMG-Py/commit/973d8bf16a4da0b184f9c19bc2074d79517f41ad)

**Comment by mjohnson541** [comment]
First, for this particular run for species in the edge I don't think this is something to be particularly worried about. 

These two structures are the same in terms of connectivity but different electronically without any difference in multiplicity so we should consider them the same species. These kinds of issues usually occur because of how the resonance system and our reaction definitions interact. My guess is some reaction family is producing an electronic structure of NNH that isn't in the list of resonance structures for the expected NNH causing it to think they are different species, but @alongd might have better idea what is happening.
