### ISSUE TITLE
Updating RMG-Py

### ISSUE THREAD

**Issue by kirkbadger18** [ReactionMechanismGenerator/RMG-Py#2626]
Updating RMG-Py

When updating RMG-Py, should we also be recompiling the code with the "make" command, and also should we be updating the rmg conda environment from the updated .yaml file? If so could we add these steps to the website to make this more clear?

**Comment by JacksonBurns** [comment]
Hi @kirkbadger18! Thanks for using RMG.

If you are using RMG from a docker image, you can just pull the latest image and run it in a separate container.

If you have installed from source, it depends.
 - If you update RMG-Py and we have changed any of the Cython files, you would need to run `make clean` and `make` again to incorporate the new changes.
 - If we have **removed** dependencies from the environment file (which is somewhat rare), you would be best served to re-build the entire environment. If we have only updated package **versions** then you can probably safely just update your existing environment.

Since it can be difficult to tell when changes have been made to Cython/the envrionment when pulling down a ton of changes, it may be best to always go through a quick environment + RMG rebuild if you haven't pulled in a while.


I agree that our docs are not thorough enough about this - [this is the best we have right now](https://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/updatingSourceCode.html). Adding to the todo list.

**Comment by oroppas** [comment]
Can RMG-Py be updated by using Anaconda?

**Comment by JacksonBurns** [comment]
> Can RMG-Py be updated by using Anaconda?

Unfortunately not. We have moved our primary distribution method to Docker, and the added difficulty of building conda packages means that we have not been keeping them up.

There are some ongoing efforts in #2539 but they are not yet ready for general use. We will provide and update if anything changes, but the best option now is to use Docker.

**Comment by oroppas** [comment]
Got it. Thanks!

**Comment by JacksonBurns** [comment]
Closing this as resolved rather than stale.
