### ISSUE TITLE
CS atomtype not being detected properly.  

### ISSUE THREAD

**Issue by connie** [ReactionMechanismGenerator/RMG-Py#327]
After reviewing https://github.com/GreenGroup/RMG-Py/blob/master/rmgpy/molecule/atomtype.py the getAtomType() function does not assign the atomtype CS to any atom, which means that the CS group is meaningless.  Even with the correct connectivity we are never able to match the group.  It will just fall up to something more general but this is dangerous behavior.

See unit test: https://github.com/GreenGroup/RMG-Py/commit/ad84506b5097690a330317937fd608b7bb9abda3

This is probably an issue with some other groups as well.

**Comment by rwest** [comment]
A reminder of #283 for discussing re-doing AtomTypes

**Comment by nyee** [comment]
As part of my attempt to fix database [issue #100](https://github.com/ReactionMechanismGenerator/RMG-database/issues/100), I made a [commit](https://github.com/nyee/RMG-database/tree/fixTrees) removing all groups with CS atomType , keeping them in a separate file.  This process was done with RMG-Py commit #664, and this script,
[removeCS.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/294441/removeCS.txt)

I started down this path because I wanted to write a script to add thermo groups correctly. I imagine that once I have finished that and the CS issue is fixed, all these CS groups can be added back in.

**Comment by nyee** [comment]
Fixed by Pull request #676
