### ISSUE TITLE
Group definitions for aromatic rings containing O

### ISSUE THREAD

**Issue by bslakman** [ReactionMechanismGenerator/RMG-Py#348]
I want to make a group (for solvation kinetics) for H-Abstraction from a carbon in a furan ring (the C which is 2 atoms away from the O). Since furan is aromatic I wanted to use Cb, but I'm not sure this is correct. I have specified it this way:

```
    group =
"""
1 *1 Cb       u0 {2,S} {3,B} {4,B}
2 *2 H        u0 {1,S}
3    Cb       u0 {1,B}
4    Cb       u0 {1,B} {5,S}
5    O        u0 {4,S}
"""
```

Cb should have two "benzene" bonds but O cannot have a benzene bond to it (and there is no Ob atom type), so I used a single bond. So the way I have specified it, nothing indicates that O is part of the ring.

Also, if you type "furan" into RMG website molecule search, it's connected with double and single bonds, not "B" benzene bonds, meaning we are not using any special aromatic type of thermo or kinetics for furan.

**Comment by shamelmerchant** [comment]
I think that will apply Benzenic corrections not the ones you want. In Java we use Cb only for 6 Carbon aromatic rings. You could define a ring correction for furan maybe?

**Comment by rwest** [comment]
We think adding aromatic oxygen atom types is probably the way to go.

**Comment by nyee** [comment]
Recently noticed that the furan ring correction for thermo gives very poor values, maybe about 10 kcal/mol for H298. Possibly could be related to confusion on whether to use Cb or Cd/Cs bonds when the entry was first made. (Git blame says it was 2005) . 

Posting as a reminder here because we should probably check all aromatic ring corrections along with other changes for aromatics functionality.

I am using the kekulized and making corrections so that the kekulized value looks reasonable because I think it is unreasonable to use Cb for furan. 

It might be prudent to make a script/unit test that compares thermo library values to GAV values so we can at least flag when something looks very wrong.
