### ISSUE TITLE
SMILES string [C] interpreted as quintuplet C with 4 radicals

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#401]
A thermo search for 

```
multiplicity 1
1 C u0 p2 c0
```

finds a match in the primary thermo library (and a bad estimate via group additivity).

A thermo search for 

```
multiplicity 3
1 C u2 p1 c0
```

finds a few matches (including another bad group additive estimate)

However, the SMILES string `[C]` is interpreted as 

```
multiplicity 5
1 C u4 p0 c0
```

which causes RMG to crash, because there's no such thing as four radicals according to the HBI radical tree, and there's no other way to guess the thermo.

Two thoughts, maybe both should be implemented:
1. [ ] 1. Allow quad-radicals in the HBI database, so at least it doesn't crash.
2. [ ] 2. Change it so that the SMILES `[C]` is interpreted as the most stable electronic state of a single carbon atom (the triplet?)

**Comment by nickvandewiele** [comment]
Ignoring the fact that SMILES is wrongly parsed for [C], RMG does have an entry in the global forbiddenStructures.py:

```
entry(
    label = "C_quintet",
    group = 
"""
1 C u4 p0
""",
    shortDesc = u"""""",
    longDesc = 
u"""

""",
)
```

So, when somebody added this entry, it must mean that at least one thing may go wrong in RMG with C_quintet.

**Comment by nickvandewiele** [comment]
On a more general note, one should be very careful in using the parsers and converters of SMILES/InChI for polyradicals. They were not build for these types of structures. 

For example, I've discovered many patterns of InChI that are wrongly parsed (non-adjacent two-center biradicals interpreted as zwitterions, adjacent two-center biradicals interpreted as an additional bond, the wrong addition of lone pairs, etc...), not in the least caused by the fact that multiplicity is not currently supported by InChI nor SMILES. 

For now, I would refrain from defining polyradicals through line identifiers like SMILES and InChI.

**Comment by rwest** [comment]
Ok. Good points. Thanks Nick

1) no point adding quintuplet C to the radical tree if it is globally forbidden. Instead perhaps Molecule.fromSMILES() should (or whatever calls it) should check things against the global forbidden structures list?

2) as both inchi and smiles define only connectivity the grouping of the spare electrons into pairs, radicals, charges, etc it ambiguous and so interpretation cannot be "wrong" so much as "not the one I was hoping for". Which is still a problem and you are right the only option is to avoid inchi and smiles for these instances. A shame though. Are there any additional layers to inchi proposed to solve this? Maybe we should devise one, a bit more powerful than greg's /mult3 layer.

**Comment by bslakman** [comment]
Bumping this up, still an issue when searching [C] on the website (or [Si]). Perhaps I should hack the interpretation of [Si] as it seems you have done on your branch for [C], @rwest? And/or globally forbid `Si u4` ?

**Comment by mliu49** [comment]
[C] is now hardcoded to return the triplet state.
