### ISSUE TITLE
generateFluxDiagrams unusable

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-Py#414]
Troubleshooting the generateFluxDiagrams, I found that it called methods from pydot (like set_pinwidth) that did not exist in my version (1.0.2) of pydot. I encountered other errors like string concatenation deep within pydot when running generateFluxDiagrams.  I am not sure what version of pydot was used to run generateFluxDiagrams successfully. If this is the only issue, we could rewrite the code to use the most up to date documentation or get people to use an older versions of pydot.

**Comment by rwest** [comment]
Please try to make it compatible with whatever pydot @connie has at https://github.com/connie/pydot because that's the one we're using with the anaconda build. Is that what you'd suggest @connie? It's a shame if the official pypi version doesn't also work, for people doing the `pip install` method. Though if it really doesn't then we should update the `requirements.txt` file to point to your new fork.

**Comment by connie** [comment]
Closed via https://github.com/ReactionMechanismGenerator/RMG-Py/pull/711
