### ISSUE TITLE
Solver does not use collision efficiencies??

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#417]
We can read the advanced collision efficiencies from chemkin files, store them in RMG P-Dep reactions, and output them again, but when integrating the reaction models internally, I think they are not used.

The `getRateCoefficient()` methods of all subclasses of `PDepKineticsModel` are given only `T` and `P` and not a vector of species. 

This would be taken care of by using the result of  `getEffectivePressure()` as `P` which is what happens if you use `Reaction.getRate()` but the actual ODE solver bypasses this and just calls `getRateCoefficient()`.  It looks like `Reaction.getRate()` is never actually used?

**Comment by rwest** [comment]
I have a vague memory of people reporting that their RMG simulations don't quite match CHEMKIN simulations of the same thing. Could this be the cause? If you are such a person, please comment!

**Comment by connie** [comment]
Confirmed that that `getEffectivePressure` is not being used in the solver. This indeed looks very troubling.  I'm guessing it never got caught because hardly anyone checked PDEP rates with collision efficiencies against CHEMKIN, especially because we often use single bath gases, the errors would've been hidden now.
