### ISSUE TITLE
Temperature quantity object does not interpret (350,'C') correctly

### ISSUE THREAD

**Issue by connie** [ReactionMechanismGenerator/RMG-Py#459]
Running a job with Temperature = (350,'C') results in the solver thinking RMG is running at 350 K.  Trying the following code in a terminal:

    from rmgpy.quantity import *
    T = Quantity(350,'C') 
    T.value_si
    >> 350.0
    T = Temperature(350,'C')
    >> rmgpy.quantity.QuantityError: Invalid units 'C'.
    T=Temperature(350,'degC')
    T.value_si
    >> 350.0
    T=Temperature(350,'degF')
    T.value_si
    >> 350.0

None of these get the the correct SI value of 350.0 + 273 K.  It turns out that `degC` is the correct unit type for a `Temperature` Quantity rather than `C`, but even so it does not properly convert to the right Kelvin units when used.  `degF` units don't work either.  Note that RMG does not throw an error when we use `C` in a normal Quantity object.  

I think we need to check for robustness of Quantity objects, because a user is highly likely to be using F or C in their inputs, and the code is not interpreting the units correctly.

**Comment by nickvandewiele** [comment]
maybe related: #248

**Comment by nickvandewiele** [comment]
I believe the problem is situated within the `quantities` library:
>
Quantities is not a package for describing coordinate systems that require a point of reference, like positions on a map. In particular, Quantities does not support absolute temperature scales. Instead, temperatures are assumed to be temperature differences.

So quantities can only compute conversion _factors_, not additive conversion _constants_.

**Comment by nickvandewiele** [comment]
So the issue will arise with every quantity that has a temperature component in its unit.

**Comment by nickvandewiele** [comment]
I currently see 2 strategies:

* Only allow Kelvin as temperature units throughout RMG.*
This would require us to ensure temperature variables are not stored as an instance of the classes of `rmgpy.quantities`. For the user, this will be a bit counterintuitive: you may specify variables in whatever unit you want, _except_ quantities with temperature components.

* Extend the `rmgpy.quantities` functionality to support temperature conversions*
This can be tricky if you want to do it for every quantity that has a temperature component in it, like heat capacities, entropies, ... I noticed a unit test in which even an energy could be defined in Kelvin.

My personal preference would be constrain the users' freedom to choose the unit of the quantity to a limited set of _supported_ units and ensuring that conversions are correctly applied for these cases. Currently, a more _libertarian_ approach is implemented and we pray that the `quantities` library will take care of it all.

**Comment by nickvandewiele** [comment]
Additionally, we could save some memory if we didn't store the units of parameters but simply converted quantities to SI units during the startup phase. This way we allow users to still define their activation energies in their beloved `kcal/mol`, but convert them to `kJ/mol` right from the start.

**Comment by rwest** [comment]
For now I think we should modify quantities so whenever a temperature is specified in something other than Kelvin it raises a NotImplementedError or a polite message to the user, suggesting they replace `(300, 'C')` with `(300+273.15, 'K')` in their input file.

We *do* convert to SI units right away, because it's faster to look them up that way than convert every time you look it up. We store what they were originally specified in, however, so that we can output it that way again. Eg. if you define a rate coefficient in kcal/mol, you want it showing up in your chemkin file or log file in kcal/mol when you're done, else you'll get confused about where it came from.   In places where we'll never output the value, we can (and I think sometimes do) just store the SI value as a float to save time and memory.
