### ISSUE TITLE
Symmetrical reactions appear in RMG chemkin models

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/RMG-Py#508]
`A+B = B+A` should never be added to a model, afaik.

version of RMG-Py: 670e781
```
! Reaction index: Chemkin #3; RMG #273
! Template reaction: H_Abstraction
! Exact match found for rate rule (C/H2/CbCs;C_rad/H/CdCs)
! Multiplied by reaction path degeneracy 2
PDD(1)+C18H29(34)=C18H29(34)+PDD(1)                 1.506e-03 4.340     13.100 
```

**Comment by connie** [comment]
Can we check if this was happening in one of the much older commits such as the version 1.0 release?

**Comment by connie** [comment]
Looks it the same error still pops up in 1.0.1 but the symmetrical reactions seem to occur only for alkylbenzenes, not something like n-hexane + n-hexane_radical

**Comment by connie** [comment]
I think the error arises from https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/data/kinetics/family.py#L1146 where we try to prevent symmetric reactions from being created.  However, note that the reactants and products at this point are molecule objects, which means they must be exactly isomorphic, and not resonance isomers of each other.  We have no other place where we check this when they have become species objects instead.  I think this is also part of the reason why we see errors like https://github.com/ReactionMechanismGenerator/RMG-Py/issues/545 because the `generateReactions()` step deals almost entirely with `Molecule`, rather than `Species` objects.
