### ISSUE TITLE
Runtime scoop error even when scoop flag is not used

### ISSUE THREAD

**Issue by connie** [ReactionMechanismGenerator/RMG-Py#510]
Noticed that we now get default runtime error when running the minimal example: 

```
/Users/connie/code/RMG-Py/rmgpy/scoop_framework/util.py:77: RuntimeWarning: SCOOP was not started properly.
Be sure to start your program with the '-m scoop' parameter. You can find further information in the documentation.
```

When running without the `-m scoop` flag.  What kind of default behavior do we want?  If we want users to ALWAYS run with scoop, then why not get rid of this flag altogether and always run with scoop by default?  But if they do not use the flag, I feel that we should not by default display any sort of runtime warning.

**Comment by nickvandewiele** [comment]
Small detail: it's a `warning`, rather than an `error` meaning that it doesn't impact the correct functioning of RMG-Py. I will try to get rid of the message.

>What kind of default behavior do we want?

My idea was to _ignore_ SCOOP by default, rather than the opposite, for a number of reasons:

* there is an overhead of several seconds associated with starting up SCOOP due to the initialization of the broker, and workers.
* unknowingly using the parallel version by default (SCOOP grabbing all the CPUs it can find) may lead to bad performance (e.g. CPU context switches because of competing jobs), or may not work if the parallel environment is not properly set.
* for most scientific software, 1 CPU is the default, and more CPUs is set by the user explicitly.

**Comment by connie** [comment]
Sounds good, I agree with getting rid of the message during normal use, since casual users will probably think they did something wrong when this warning pops up.
