### ISSUE TITLE
Unit tests starting to take too long

### ISSUE THREAD

**Issue by connie** [ReactionMechanismGenerator/RMG-Py#549]
We should profile what tests are slow and see if we can trim them down while testing the same functionality.

**Comment by goldmanm** [comment]
I have some thoughts about ways to reduce time (and possibly make the tests easier to write)

Some time consuming tasks in unittests is: loading database, loading an rmg job, and other large RMG objects. These tasks are typically done, at best, once per Test Class. Ideally, we only need to do that once for the entire testing run. This can reduce the need to create multiple databases. One idea is to import a file that has all these objects. This would require less time running the entire set, but may increase the time on individual test runs (since it may load an RMG object that is not used in `[method]Test.py`).

**Comment by goldmanm** [comment]
Some recent pull requests #1055 #953 (and others) have reduced the time for testing by using a small test database and loading it only once per module or class. 

I think there are a few testing classes that still need to be brought up to code with this, but now the average on my computer is 0.1 seconds / test which is an improvement.
