### ISSUE TITLE
merge_models.py could not read reaction

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#576]
Running mergeModels.py I got the following error message with readReactionsBlock:

```
Loading model #1... 
Loading model #2...
Traceback (most recent call last):
File "scripts/mergeModels.py", line 24, in <module> 
           main()
File "scripts/mergeModels.py", line 21, in main
           merge_models.main()
File "C:\Code\RMG-Py\rmgpy\tools\merge_models.py", line 67, in main
           execute(inputModelFiles, **kwargs)
File "C:\Code\RMG-Py\rmgpy\tools\merge_models.py", line 87, in execute
           model.species, model.reactions = loadChemkinFile(chemkin, speciesPath, transportPath=transportPath)
File "C:\Code\RMG-Py\rmgpy\chemkin.py", line 826, in loadChemkinFile
         reactionList = readReactionsBlock(f, speciesDict, readComments = readComments)
File "C:\Code\RMG-Py\rmgpy\chemkin.py", line 1245, in readReactionsBlock
          raise e 
rmgpy.chemkin.ChemkinError: Could not read collider efficiencies for reaction: H2O(9) <=> H(5) + OH(7).
The following line was parsed incorrectly:CO(12)/1.90/ H2(8)/3.00/ O2(2)/1.50/ N2(37)/2.00/ CO2(13)/3.80/ H2O(9)/0.00/AR/0.36/
(Case-preserved tokens: ['CO(12)', '1.90', ' H2(8)', '3.00', ' O2(2)', '1.50', ' N2(37)', '2.00', ' CO2(13)', '3.80', ' H2O(9)', '0.00', ' Ar', '0.36', ''] )
```   

The block causing the problem was:                                             
```
H2O(9)+M=H(5)+OH(7)+M                               1.450e+28 -3.322    120.800  
CO(12)/1.90/ H2(8)/3.00/ O2(2)/1.50/ N2(37)/2.00/ CO2(13)/3.80/ H2O(9)/0.00/ Ar/0.36/ 
```

**Comment by nyee** [comment]
If you look at the error, there is an empty string at the end of the list:

(Case-preserved tokens: ['CO(12)', '1.90', ' H2(8)', '3.00', ' O2(2)', '1.50', ' N2(37)', '2.00', ' CO2(13)', '3.80', ' H2O(9)', '0.00', ' Ar', '0.36', ''] )

There is probably a space at the end of your line; try deleting it. This might be caused by line ending issues between windows and linux. I think you might be able to fix that with configurations in whatever program you're using to transfer files....

**Comment by alongd** [comment]
Right, that's what @KEHANG and I thought as well.
But the problematic line
```CO(12)/1.90/ H2(8)/3.00/ O2(2)/1.50/ N2(37)/2.00/ CO2(13)/3.80/ H2O(9)/0.00/ Ar/0.36/ ```
ends the same as other collider efficiencies of earlier reactions in that file that, I assume, did go through the merge Models correctly, e.g.:
```CO2(13)/3.80/ H2O(9)/12.00/ H2(8)/2.50/ CO(12)/1.90/ Ar/0.00/ ```
On my windows Notepad++ all of these lines end with the same blank space after the last ```/```.
This was run on my local RMG-Py, so it's not caused due to the file transfer.
I just deleted the last space in that line, but the problem persists.

**Comment by rwest** [comment]
Is there a species that has not been defined yet? or with a different name eg. if merging models, maybe in the second model you import there is no "N2(37)" because it's called "N2(5)" in the first model.  (I'm basing this speculation on my knowledge of the chemkin importer - I am not familiar with the model merger or how it calls the chemkin reading routines).

**Comment by alongd** [comment]
Right, there was indeed a problem with the dictionary I used, the mergeModels.py works smooth now.
Thank!

**Comment by rwest** [comment]
The remaining issue is therefore that the error message wasn't helpful enough!

**Comment by alongd** [comment]
right :)
