### ISSUE TITLE
 libgfortran isn't found for clean install on OS X 

### ISSUE THREAD

**Issue by cfgoldsmith** [ReactionMechanismGenerator/RMG-Py#610]
After trying a clean installation, I get the following error message:
Fetching package metadata: ..........
Error: No packages found in current osx-64 channels matching: libgfortran ==1.0

If I comment out 
- libgfortran ==1.0
in environment.yml
Things proceed.

**Comment by connie** [comment]
We can probably change that to just apply to linux and default back to the normal libgfortran for everything else.

**Comment by connie** [comment]
Unfortunately we can't really make os-specific flags for `environment.yml` files, which is why we had to have `environment_windows` and `environment.yml` files.   I wonder if we should hope that this flag is no longer necessary for linux users so that we can revert it, or should we create an `environment_osx.yml` file?
