### ISSUE TITLE
RMG confusing Triplet Carbon Atom, C(T), with Methylidene, CH2, at high-T with P-dep on

### ISSUE THREAD

**Issue by zjburas** [ReactionMechanismGenerator/RMG-Py#621]
While running an RMG job for stoichiometric natural gas combustion at 2.5 atm, up to 2700 K and with P-dep on, I was able to get a converged mechanism that seems to confuse triplet carbon atom, C(T), with methylidene, CH2. Specifically, at the end of the final mechanism there are six P-dep reactions between CO2 and C(T) that assume the presence of two additional hydrogens. For example:

CO2(5)+C(T)(19)(+M)=C2H2O2(84)(+M)

The Chebyshev polynomials are all "nan" for these reactions, causing the mechanism to not run in Chemkin. Of course, I can just manually delete these problematic reactions and then the mechanism runs in Chemkin, but I don't know how the presence of these reactions during mechanism generation might be affecting other reactions on the same surface. 

Both C(T) and CH2 are assigned the correct adjacency lists in the "species dictionary". Perhaps other people haven't had issues with C(T) before because it is unusual to run RMG at such high T (2700 K) where weird species like C(T) become thermodynamically feasible.

**Comment by rwest** [comment]
Sorry for closing - my thumb slipped. 
I was about to comment:

@bslakman recently had a problem with PDep that was in fact due to incorrect SMILES being written for silylene species. I suspect this is related, in that we often got SMILES wrong for atomic carbon or CH2 etc. I suspect the flaw is that we are relying on correct and canonical SMILES strings to communicate with the PDep module, and this is not safe. We must pass species or molecule objects, or full adjacency lists.  I have not looked at the code to check or locate, but this is my suspicion.
