### ISSUE TITLE
Liquidreactor: Thermo corrections for solvent species

### ISSUE THREAD

**Issue by yunsiechung** [ReactionMechanismGenerator/RMG-Py#635]
For a liquid reactor, the enthalpy and entropy of every species are corrected by adding the enthalpy and entropy of solvation to the gas-phase thermo inside `rmgpy\rmg\model.py`
The enthalpy of solvation is calculated from Mintz Correlations and the entropy of solvation is calculated simply by using the following equation:
![image](https://cloud.githubusercontent.com/assets/17207530/14499629/183d419a-016d-11e6-8556-d780d97619dc.png)
where dG_solvation is obtained from the Abraham LSER. 

The issue with this correction is that this correction is not accurate for solvent species since the free energy of solvation is associated with the process of transferring a molecule from the gas phase to the solvent phase. This correction would work for solute species, but for solvent species with dilute solute concentrations, the correction should be the enthalpy and entropy change of condensation (from gas to liquid). For example, when I run the liquidreactor simulation in RMG using water as a solvent, it reports H298 as -57.80 kcal/mol and S298 as 45cal/molK (reports the same values with both presence and absence of any solutes). However, for liquid water (neglecting the effects of dilute solutes concentrations), the literature values of H298 and S298 are -68.315 kcal/mol and 16.718 cal/molK. 

However, there are some concerns with using a different correction for solvent species. We are worried that the equilibrium constants for certain reactions might change significantly depending on whether the involved species is a solvent or solute. For example, we wouldn't expect the reactions between hexane and other species to differ significantly when the reactions take place in similar solvents, such as pentane and hexane. However, if the thermo for hexane is adjusted by the changes upon condensation when hexane is a solvent while it is adjusted by the changes upon solvation when pentane is a solvent, the two equilibrium constants for the same reaction in similar solvents might turn out to be considerably different. These two cases have not been tested yet, but I will run them soon. It would be nice if anyone has a good idea about how to fix this issue.

Lastly, there is no correction for heat capacity in liquidreactor simulation right now. The change in heat capacity of solutes upon solvation cannot be calculated since the temperature dependence of entropy of solvation is unknown. However, since the dilute concentrations of solutes are assumed, I think it would be fine to just use the heat capacity of a solvent species to represent the bulk thermo property of the solution. This would require adding a separate library for solvent species that contains the heat capacity of liquid phase solvents. Furthermore, I think it would be a good idea to add the critical temperatures of solvents in the library as well so that RMG can output the error message when the temperature is above the critical temperature for the liquidreactor.

**Comment by bslakman** [comment]
Hi @yunsiechung . We've talked these points in person, but I figured it's best to continue the discussion here to get others involved. Have you made any progress or run into any bugs with this? 

As I may have mentioned, solvents are currently represented with just a string name instead of an actual molecule. So, the RMG simulation has no knowledge that the solvent 'water' that is causing all of the thermo and kinetics to be different, is also the same thing as the chemical species H2O which may also participate in reactions. I think it would be helpful as a first step to change how the solvent is represented by representing the solvent in the library with an adjacency list or SMILES. One can then add more properties such as heat capacity and critical temperature to the existing solvent library. Also, knowing the molecular structure of the solvent lends itself to being able to figure out a scheme for determining solvent parameters of interest for a mixture of solvents. We also talked a little about adding the solvent species to the core as default (and maybe having an option to enable/disable this), as it may not be intuitive to the user that they must do it separately.

**Comment by yunsiechung** [comment]
Hi @bslakman . Thank you for the additional comments. 

Currently, I am studying the temperature dependence of solvation free energies. I realized that the solvation free energies also depend on pressure, and therefore we should have RMG liquidreactor to take Pressure as an input as well at some point. 

I agree that the solvent needs to be represented by an adjacency list or SMILES. I have talked with Prof. Green, and he also thinks that different thermo correction should be used for solvent species. I would try to implement these changes after I figure out the temperature dependence issue. 

Thank you so much and let me know if you find any other issues.

**Comment by yunsiechung** [comment]
One paper showed that the pressure effect is negligible for approximately P < 100 bar. (Vladimir Majer, Josef Sedlbauer, Gaetan Bergin, Fluid Phase Equilibria 272 (2008) 64-74)
Therefore, the pressure dependence of liquid phase reactions can be neglected for mild pressure.

**Comment by yunsiechung** [comment]
@bslakman @rwest 
For solvent species, if Raoult's law can be applied by assuming ideal solutions, the formation free energy of solvent species can be expressed as:
![image](https://cloud.githubusercontent.com/assets/17207530/15838459/22a64450-2c0c-11e6-831e-3e3ee7417ff6.png)

What do you think about using this relationship for the solvent thermo correction? The formation free energy of solvents could be calculated by using CoolProp.
