### ISSUE TITLE
checkForExistingSpecies not working for biaromatics

### ISSUE THREAD

**Issue by KEHANG** [ReactionMechanismGenerator/RMG-Py#643]
During RMG model generation, if some species has more than one aromatic rings and only
some of them are kekulized, current `checkForExistingSpecies` will fail. 

For example, species (`SMILES="C1=CC=C(C=C1)CCCC1C=CC=CC=1"`) already existed, which has two resonance isomers:
![image](https://cloud.githubusercontent.com/assets/2739496/15056234/8e5c2878-12de-11e6-864d-a22d3d487693.png) and 
![image](https://cloud.githubusercontent.com/assets/2739496/15056242/97bc1f0e-12de-11e6-98bb-be7e3cb1853b.png), 
then if new molecule is generated in a partially kekulized form (product from the reaction below): 
![image](https://cloud.githubusercontent.com/assets/2739496/15056314/edbbb770-12de-11e6-855a-2c69378bbf3d.png), 
`checkForExistingSpecies` will fail and treat it as a new species.

**Comment by KEHANG** [comment]
It's fixed by this [PR#644](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/644).

**Comment by nickvandewiele** [comment]
I guess RMG-Py will have more than two resonance isomers for Species C1=CC=C(C=C1)CCCC1C=CC=CC=1, not just the kekulized and aromatic one. 

If you call `spc.generateResonanceIsomers()` on a given isomer of that species how many isomers will be generated?

**Comment by KEHANG** [comment]
@nickvandewiele only two isomers are generated. This is actually an [unittest](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/644/commits/93873bdff90435ae8d112ec3eb31ce4765e96949) I made here.

**Comment by rwest** [comment]
I would only expect 2 resonance isomers for that because it is so symmetrical.
Break the symmetry a bit and you are more likely to run into trouble with making all the resonance forms every time (see #405).
`C1=C(C)C=C(C=C1)CCC=CC1C=CC=C(O)C=1`
![biaromatic](https://cloud.githubusercontent.com/assets/93807/15076656/b7290182-1378-11e6-812c-1ed9804d386e.png)

**Comment by KEHANG** [comment]
@rwest the current issue is the asymmetrical biaromatics is generated by RMG as edge species, which actually should be recognized as same as the symmetrical one that already exists in speciesDict.

**Comment by rwest** [comment]
I understand. I was addressing Nick's comment that he'd expect more than 2 resonance isomers.
But I'm wrong - I would expect 3, and that would solve your problem: the kekulized (in this case all kekulized forms are equivalent due to simple rotational symmetry, even without moving bond orders around), the aromatic (again, only one), and the mixed with one end aromatic and one end kekulized (if RMG had found this already, your problem would be solved). 

I can't think of an easy way to find the mixed case, as we use RDKit (or sometimes OpenBabel??) to aromaticize and kekulize molecules as a whole.

**Comment by KEHANG** [comment]
Yes, you are right. If we could generate partially-kekulized isomers from aromatic isomer, that will solve the problem. The current RMG only generates fully kekulized and fully aromatic isomers after calling `spc.generateResonanceIsomers()`, shown below .
![image](https://cloud.githubusercontent.com/assets/2739496/15079137/be7dfd5a-1384-11e6-8def-ac50c8de3d3b.png)

**Comment by connie** [comment]
Closed via https://github.com/ReactionMechanismGenerator/RMG-Py/pull/644
