### ISSUE TITLE
Particular reactant giving trouble?

### ISSUE THREAD

**Issue by bslakman** [ReactionMechanismGenerator/RMG-Py#674]
Kind of a strange error, so I'll try to give as much info as possible...
I am trying to process a chemkin file/ RMG dictionary combo. One part of my script tries to generate RMG reactions from (known) family for a set of the reactions in the chemkin file.
There's about 5000 reactions I'm doing this to, and it works for all but 99 of them. Not an error, but it doesn't generate any reactions. I noticed that all 99 of these are hydrogen abstractions by a particular reactant (SMILES="[O][CH]CCC=O") to give a particular product (SMILES="[O]CCCC=O"). 
Then when I search for these reactions on the RMG website, and click one of the links where it says `4 results` or something (for example, I tried octane + [O][CH]CCC=O <-> 1-octyl + [O]CCCC=O) I get the error:
`The requested URL /database/kinetics/reaction/reactant1=multiplicity%202 ......  was not found on this server.`
Other H-Abstractions from octane work. Also, when I get to the webpage with the reactions and click the reactants or products individually, no error there. 
Any ideas about why this particular species pair is giving issues?

**Comment by rwest** [comment]
This was me trying to figure out if it's hitting a forbidden structure from the bottom of [H_Abstraction/groups.py](https://github.com/ReactionMechanismGenerator/RMG-database/blob/master/input/kinetics/families/H_Abstraction/groups.py#L6874), which I think were designed (by Aaron) to prevent disproportionation reactions showing up in the H-abstraction family:
> If it's H abstraction by reactant (SMILES="[O][CH]CCC=O") to give product (SMILES="[O]CCCC=O") then the abstraction is being done by *3 the radical [CH] near the end, which is next to a radical [O] on the end. In the reverse direction then, the *2 H is being abstracted from a *1 C  which is next to a radical [O] on one side and a carbon on the other, with 2 H atoms...

but I don't think it should.

However, that *3 is a 2-center adjacent biradical that won't match the `Y_2centeradjbirad` definition:
```
entry(
    index = 193,
    label = "Y_2centeradjbirad",
    group = 
"""
1 *3 [Ct,Os,Ss] u1 {2,[S,T]}
2    [Ct,Os,Ss] u1 {1,[S,T]}
""",
    kinetics = None,
)
```
because the atom type is Cs not Ct.

However, it should still match the generic `Y_rad` node.

I feel like I'm not getting very far here

**Comment by bslakman** [comment]
I don't think it's hitting a forbidden structure, because the reaction still shows up as an option when you search for it on the RMG website. The error happens when I try to click the details.

**Comment by rwest** [comment]
@hamza-khan has a functioning website-clone on his computer, see if he can help debug the website issue (which I think is separate)

**Comment by mliu49** [comment]
Closing stale issue. I'm pretty sure that this was caused by the URL length problem, which has been slightly alleviated.
