### ISSUE TITLE
Aromatic species matching non-aromatic groups in kinetics rate rules

### ISSUE THREAD

**Issue by connie** [ReactionMechanismGenerator/RMG-Py#682]
Investigation of our PDD model led to this bug discovery: benzyl + phenyldodecane reactions were using the wrong group in H_Abstraction and R_Addition_MultipleBond.  Benzyl was matching to groups such as `C_rad/H2/Cd`, rather than the correct `C_rad/H2/Cb` group, although PDD was identified using the aromatic group:

```
! Template reaction: H_Abstraction 
! Flux pairs: PDD(1), RAD1(14); BENZYL(58), TOLUENE(2);
! Exact match found for rate rule (C/H2/CbCs;C_rad/H2/Cd) 
! Multiplied by reaction path degeneracy 2 
PDD(1)+BENZYL(58)=TOLUENE(2)+RAD1(14) 2.980e-03 4.340 12.500
```

The source of this problem was due to the resonance isomers.  All of the species do have their resonance isomers generated.  HOWEVER, the benzyl radical uses the thermo from a Thermo Library, whereas PDD uses group additivity for thermo estimation.  This meant that the aromatic species that used group additivity thermo had their isomers reordered such that the aromatic representations were prioritized, and therefore matched Cb groups in the kinetics.    But Benzyl radical does not have this reordering take place, and as a result,  the kekulized form of benzyl is prioritized when matching groups in the kinetics. 

I did a quick check and there is a somewhat large difference at low temperature for instance in:

Benzyl + Hexane = Toluene + Hexyl radical

Rate using kekulized group for benzyl: 8.76E-2  4.34 19.7    k(650 K) = 3.4e4 cm3/mol s
Rate using aromatic group for benzyl: 8.1E-2 4.34 17.6      k(650 K) = 1.6e5 cm3/mol s

In any case, this behavior makes kinetics inconsistent in our models and ought to be fixed.

**Comment by rwest** [comment]
This doesn't sound quite right. I think we generate reactions for EACH resonance structure, not the lowest. And once you've generated a reaction for a given resonance structure, you surely have to use exactly that structure to find its kinetics, not the lowest, otherwise you'd risk decrementing a single bond or something like that. i.e. what choice of thermo you use should not effect the groups matched while searching kinetics, because you search kinetics for the resonance structure used to generate the reaction. 

Or did I misunderstand something?

**Comment by connie** [comment]
I thought we generate reactions for all resonance structures also... but perhaps what happens is that they collapse onto a single set of kinetics when isomorphism checks show that reactants and products are identical?  The way RMG currently does it is to increase degeneracy, so I wouldn't be surprised if only the first set of kinetics was being selected.

**Comment by rwest** [comment]
This is an interesting case though. For benzyl the radical that is participating in the reaction is just attached to the aromatic thing with various resonance forms. In this case probably only two structures - kekulized and not - but for some other polyaromatics there are many resonance forms. Multiplying by the "multiplicity" in this case seems a bad idea.

**Comment by KEHANG** [comment]
@connie I think your intuition was right, I just recalled that I made an ipynb before to explain how the order of resonance isomers of a species can affect the kinetics (e.g. `reaction.template`), see [here](https://github.com/KEHANG/rmg_wiki/blob/master/wiki/how_rmg_estimates_kinetics_non-deterministically.ipynb)

**Comment by mliu49** [comment]
This issue has been touched on by a number of fixes.
1. Resonance structures are now reordered after matching a library entry (therefore the aromatic structure would now appear first)
2. The degeneracy algorithm previously chose the first reaction, but then was changed to keep all reactions as duplicates, but will soon be changed again to restore the original behavior for cases related to resonance.

I'm going to close this issue because it should have been resolved by the first change of reordering resonance structures.
