### ISSUE TITLE
Create new environment_mac.yml?

### ISSUE THREAD

**Issue by connie** [ReactionMechanismGenerator/RMG-Py#691]
Just saw that even though we have this in merged into master (https://github.com/ReactionMechanismGenerator/RMG-Py/pull/672), the documentation has actually not been updated.  Regardless, asking the user to do things like comment out parts of Makefiles is probably not what we want.  I think perhaps a `environment_mac.yml` should be created instead?

**Comment by mliu49** [comment]
I agree. I was updating the environment on my mac, and was confused when it didn't work. The documentation didn't say anything, and it wasn't until I looked at `environment.yml` that I saw a comment saying to comment it out for mac.

**Comment by rwest** [comment]
Maybe the wiki should include a page on how to update the documentation.

We could have three separate environment files and instruct people to type
`conda env create -f environment_[mac/linux/win].yml` as appropriate instead of `conda env create`.
Then the instructions would be the same for everyone.

**Comment by connie** [comment]
Sounds good. Richard could you add the wiki page? I can do the source code changes.

**Comment by rwest** [comment]
Wiki page is at https://github.com/ReactionMechanismGenerator/RMG-Py/wiki/Updating-Documentation
and I just published the latest version of the documentation.
