### ISSUE TITLE
Improvements required for PDep reactions involving Nitrogen

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#731]
Although RMG successfully generates the reactions:
```H + C=CN <=> [CH2]CN    ;    [CH2]CN <=> C=C + [NH2]```
or:
```H + CCON=O <=> CCON[O]    ;    CCON[O] <=> CC[O] + HN=O```

It doesn't generate the combined P-dependent addition-elimination reactions:
`H + C=CN <=> C=C + [NH2]`
or:
`H + CCON=O <=> CC[O] + HN=O`

An input file for testing is attached.
[input.py.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/387073/input.py.txt)

**Comment by rwest** [comment]
@whgreen mentioned this earlier this evening. He said the two independent 2-1 and 1-2 reactions were being generated and treated as pressure dependent, but the 2-2 chemically activated (well-skipping) net reaction wasn't being generated. My guess was that the networks are not being merged, and I recalled that when we merged everything we ended up with huge PDep networks so the algorithm was changed to only explore networks from a certain entrance channel, or something like that. I thought possibly if a "leak flux" was too small relative to your tolerance (or relative to other things that happen first) then the network would never be explored, expanded, and merged.  This could be because your tolerance is too loose, or one of the rates is being estimated as too slow (or another one is being estimated too fast), so it doesn't become important. i.e. it's possibly not that it would *never* show up, just that it hasn't shown up.

The commit messages around https://github.com/ReactionMechanismGenerator/RMG-Py/commit/ff0fe201ce2dd0f998bb29835cd1b7198ce348f4 and subsequent commits, and perhaps @jwallen's thesis, may give some insight into how and when pdep networks are merged.

Perhaps one could argue that everything in the core should be merged no matter what the fluxes. But perhaps that was causing the problems with big networks.


I tried to debug a bit by simplifying your input down a little (only including `H` and `C=CN`) and tightening the tolerance ([input.py.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/387707/input.py.txt)), but I can't get it to generate any of the reactions you mention at all! The only core reaction is H+H=H2. Similar result searching `C=CN` reacting with `[H]` at rmg.mit.edu gives no results. Are you using a custom database?

**Comment by connie** [comment]
The database was just updated with https://github.com/ReactionMechanismGenerator/RMG-database/pull/115 to unforbid nitrogen reactions so that's why website may not show them.

**Comment by rwest** [comment]
That could explain the website, but running locally with the latest official master database my input file still doesn't react `[H]` and `C=CN` in the core. 😕

**Comment by alongd** [comment]
I managed to generate both of the above well-skipping reactions, starting from the products at high concentration (NH2 & C2H4 for the 1st reaction, and HNO & CCOJ for the 2nd), rather than what I so far defined as the reactants, as @rwest and suggested to @whgreen.

RMG generates a one direction reaction, e.g.:
```
NH2(1)+C2H4(2)=>H(4)+C2H5N(18)                      1.000e+00 0.000     0.000    
    PLOG/ 0.005     8.942e+02 2.811     10.264   /
    PLOG/ 0.022     9.052e+02 2.810     10.272   /
    PLOG/ 0.099     9.549e+02 2.804     10.304   /
```

At least the mystery is solved!

To run N chemistry I made some modifications to RMG-Py & RMG-database, I'll collect the changes and push them to official.

**Comment by whgreen** [comment]
Great!

Can we make RMG generate Chebyshev instead of PLOG?

Bill

Sent from my iPhone

On Jul 28, 2016, at 3:52 PM, Alon Grinberg Dana <notifications@github.com<mailto:notifications@github.com>> wrote:


I managed to generate both of the above well-skipping reactions, starting from the products at high concentration (NH2 & C2H4 for the 1st reaction, and HNO & CCOJ for the 2nd), rather than what I so far defined as the reactants, as @rwest<https://github.com/rwest> and suggested to @whgreen<https://github.com/whgreen>.

RMG generates a one direction reaction, e.g.:

NH2(1)+C2H4(2)=>H(4)+C2H5N(18)                      1.000e+00 0.000     0.000
    PLOG/ 0.005     8.942e+02 2.811     10.264   /
    PLOG/ 0.022     9.052e+02 2.810     10.272   /
    PLOG/ 0.099     9.549e+02 2.804     10.304   /


At least the mystery is solved!

To run N chemistry I made some modifications to RMG-Py & RMG-database, I'll collect the changes and push them to official.

**Comment by alongd** [comment]
Sure:
```
NH2(1)+C2H4(2)(+M)=>C2H5N(18)+H(4)(+M)              1.000e+00 0.000     0.000    
    TCHEB/ 1000.000  4000.000 /
    PCHEB/ 0.005     0.099    /
    CHEB/ 6 4/
    CHEB/ 1.069e+01    -3.697e-04   -1.213e-04   1.422e-19   /
    CHEB/ 1.661e+00    4.951e-04    1.622e-04    -1.904e-19  /
    CHEB/ 1.395e-01    -1.827e-04   -5.965e-05   7.026e-20   /
    CHEB/ 2.682e-02    5.705e-05    1.857e-05    -2.194e-20  /
    CHEB/ 3.792e-03    -1.103e-05   -3.559e-06   4.243e-21   /
    CHEB/ -7.573e-16   -6.122e-17   3.198e-19    -3.758e-34  /
```

**Comment by alongd** [comment]
Thanks @rwest !

**Comment by alongd** [comment]
Depending on conditions, this reaction could also be generated by RMG as reversible:

```
! Reaction index: Chemkin #39; RMG #1435
! PDep reaction: PDepNetwork #73
! Flux pairs: C2H5N(19), C2H4(20); H(5), NH2(1); 
H(5)+C2H5N(19)(+M)=NH2(1)+C2H4(20)(+M)              1.000e+00 0.000     0.000    
    TCHEB/ 1000.000  1600.000 /
    PCHEB/ 0.493     2.961    /
    CHEB/ 6 4/
    CHEB/ 1.226e+01    -1.428e-02   -2.551e-03   -2.865e-04  /
    CHEB/ 3.164e-01    8.452e-03    1.322e-03    1.224e-04   /
    CHEB/ 3.623e-03    -1.183e-03   -1.546e-04   -1.103e-05  /
    CHEB/ 3.992e-04    8.171e-05    1.151e-05    9.132e-07   /
    CHEB/ 1.755e-05    2.881e-06    -1.810e-07   7.569e-08   /
    CHEB/ 3.669e-07    9.066e-07    1.105e-07    -3.796e-08  /```

**Comment by whgreen** [comment]
We should look into this further to be sure we understand it. I understand why RMG generates the reactions as irreversible initially. In the final output model we want all the reactions to be reversible to satisfy the laws of thermodynamics. It looks like RMG is trying to do this but maybe not consistently? The issue is that sometimes RMG will find both forward and reverse separately (but maybe not exactly satisfying Keq), but in other cases it will only find the reaction in one direction.

Bill

Sent from my iPhone

On Jul 29, 2016, at 11:24 AM, Alon Grinberg Dana <notifications@github.com<mailto:notifications@github.com>> wrote:


Depending on conditions, this reaction could also be generated by RMG as reversible:

! Reaction index: Chemkin #39; RMG #1435
! PDep reaction: PDepNetwork #73
! Flux pairs: C2H5N(19), C2H4(20); H(5), NH2(1);
H(5)+C2H5N(19)(+M)=NH2(1)+C2H4(20)(+M)              1.000e+00 0.000     0.000
    TCHEB/ 1000.000  1600.000 /
    PCHEB/ 0.493     2.961    /
    CHEB/ 6 4/
    CHEB/ 1.226e+01    -1.428e-02   -2.551e-03   -2.865e-04  /
    CHEB/ 3.164e-01    8.452e-03    1.322e-03    1.224e-04   /
    CHEB/ 3.623e-03    -1.183e-03   -1.546e-04   -1.103e-05  /
    CHEB/ 3.992e-04    8.171e-05    1.151e-05    9.132e-07   /
    CHEB/ 1.755e-05    2.881e-06    -1.810e-07   7.569e-08   /
    CHEB/ 3.669e-07    9.066e-07    1.105e-07    -3.796e-08  /```

**Comment by alongd** [comment]
I agree. @whgreen just suggested that we should build a tool which kicks in subsequent to each PDep network, changes all ```=>``` sings to ```=```, and checks that there are no identical pre-existing reactions in the model (in which case, we should remove them).
Other than that, we should look into the networks that generated the irreversible reactions, follow how they were explored, and see if we can tease out why the final reaction is still irreversible.
