### ISSUE TITLE
Round trip SMILES generation with Nitrogen broken

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#735]
Starting with this adjacency list

```
multiplicity 2
1 N u1 p0 c+1 {2,S} {3,S} {4,S}
2 O u0 p3 c-1 {1,S}
3 H u0 p0 c0 {1,S}
4 H u0 p0 c0 {1,S}
```

I generate the SMILES string `[NH2+][O-]`
But starting from that SMILES string I generate the adjacency list

```
1 N u0 p1 c+1 {2,S} {3,S} {4,S}
2 H u0 p0 c0 {1,S}
3 H u0 p0 c0 {1,S}
4 O u0 p3 c-1 {1,S}
```

which is invalid and causes the error `InvalidAdjacencyListError: Invalid valency for atom N (N3s) with 0 unpaired electrons, 1 pairs of electrons, 1 charge, and bonds [S,S,S].
`

**Comment by alongd** [comment]
Nitrogen SMILES indeed require out attention.
Here is another example involving N val 5 where RMG + OB fail to recognize the radical site.
Starting with this adjacency list
```
multiplicity 2
1 O u0 p2 c0 {2,S} {4,S}
2 N u0 p1 c0 {1,S} {3,D}
3 O u0 p2 c0 {2,D}
4 N u1 p0 c0 {1,S} {5,T}
5 N u0 p1 c0 {4,T}
```
The generated SMILES string is `O(N=O)[N]#N`. Going back to AdjList from that SMILES string gives:

```
1 O u0 p2 c0 {2,S} {3,S}
2 N u0 p1 c0 {1,S} {4,D}
3 N u0 p0 c0 {1,S} {5,T}
4 O u0 p2 c0 {2,D}
5 N u0 p1 c0 {3,T}
```

(atom 3 here has a valance of 4, not 5 due to the missing rad)

**Comment by alongd** [comment]
One idea is to develop augmented SMILES in RMG. This is even more important when it comes to sulfur.
This might look something like:
`O[:S](=O)[::O.]`, or
`O[S.](=O)=[::O]`
(where ':' denotes a lone pair, '.' denotes a radical)

**Comment by alongd** [comment]
Just documenting an even stranger SMILES round trip problem:
Both of the following structures
![image](https://user-images.githubusercontent.com/16158262/42704530-2ae30cea-869e-11e8-875b-c3932537d68d.png)
![image](https://user-images.githubusercontent.com/16158262/42704539-3073cfc8-869e-11e8-90c4-c5397904baec.png)
share the same SMILES string in RMG, `N(=O)[O]`, which in turn doesn't translate into any of them. It is concerning that the SMILES doesn't capture the ring, the radical position, and even suggests that N is in the middle, when it is not in the second structure.

Additional info for debugging:
[struc1](http://rmg.mit.edu/database/molecule/multiplicity%202%0A1%20*2%20O%20u0%20p1%20c+1%20%7B2,D%7D%20%7B3,S%7D%0A2%20*3%20O%20u0%20p2%20c0%20%7B1,D%7D%0A3%20*1%20N%20u1%20p2%20c-1%20%7B1,S%7D%0A)
[struc2](http://rmg.mit.edu/database/molecule/multiplicity%202%0A1%20O%20u0%20p2%20c0%20%7B2,S%7D%20%7B3,S%7D%0A2%20N%20u1%20p1%20c0%20%7B1,S%7D%20%7B3,S%7D%0A3%20O%20u0%20p2%20c0%20%7B1,S%7D%20%7B2,S%7D%0A)

**Comment by cgrambow** [comment]
I figured out what the issue is for those two molecules, @alongd. Instead of using RDKit or Open Babel when creating SMILES, it finds the corresponding SMILES for `NO2` in `RADICAL_LOOKUPS` in `rmgpy/molecule/translator.py`. I suspect that it was not considered that the formulas in those lookup dictionaries could have other structures associated with them. In fact, I would probably recommend removing other formulas from those dictionaries as well. For example, `CH2O` could also correspond to hydroxymethylene instead of formaldehyde and there are probably other structures for `CO2` and `N2O`.

**Comment by alongd** [comment]
Wonderful insight!
We should re-discuss the purpose of our SMILES lookups, and how to properly use them.

**Comment by mliu49** [comment]
History:
- 0a33279c8c90d437fa5ca32a508e90a5f8ab33c8
- 3a1c5144af19b8df9676b222638dcd7b65f8d8f6

They should definitely only be included if there's only a single interpretation of the chemical formula. They were originally included for speed-up, though I agree that it seems a bit unnecessary.
