### ISSUE TITLE
Indexes missing for Inert species in mechanism

### ISSUE THREAD

**Issue by soumsrani** [ReactionMechanismGenerator/RMG-Py#759]
Hi,

I am using RMG to generate a natural gas mechanism with aromatic chemistry. I have 3 isomers of bicyclopentadienyl radical (C10H9) in my input file. I set the reactivity of this species False in the input file. The RMG generated mechanism has three C10H9 species with different SMILES but the same name. I do not get any errors in mechanism generation but I get errors when preprocessing in CHEMKIN. For example, the mechanism has reactions such as C10H9=C10H9, which will create a preprocessing error. The input, species dictionary and the chem_annotated files are attached. Any help in solving this problem is appreciated. Thank you. 

[chem_annotated.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/433722/chem_annotated.txt)
[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/433721/input.txt)
[species_dictionary.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/433720/species_dictionary.txt)

**Comment by KEHANG** [comment]
@soumsrani for reactive species, RMG usually doesn't have problem creating unique chemkin labels because they have unique index. So even two reactive species have same label, RMG will append index e.g., `ethane(1)`. However, for non-reactive species, by design they have same index `-1`, so there is some potential RMG can create duplicate chemkin labels.

A good practice is for those non-reactive species, you **give species label less than 10 characters** in the input file and **make sure there's no characters such as `=`** (in you input file I saw your label is the SMILES, and contains `=`) in there that will confuse downstream CHEMKIN because it's same as reaction equal sign.

**Comment by nyee** [comment]
@KEHANG, This was the work-around that we decided to use, but I think this is still an issue we should fix. Maybe a good convention is to use increasing negative integers for all the inert species.
