### ISSUE TITLE
Test suite speedup opportunity

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-Py#786]
While repeatedly running the test suite today, I noticed that [`test_liquidInputReading`](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/solver/liquidTest.py#L260) always took a long time (~19 s, or ~11% of total run time).

The reason is that this test loads the entire database from scratch because no options are specified when initializing the RMG object. The test could be sped up considerably if we don't actually need to load all the databases, which seems reasonable from a cursory look.

I was hoping to hear from people who are more familiar with liquid reactor to see if this test actually needs the entire database. It seems that @chatelak wrote the original test, although @nickvandewiele made the change to use initialize().

**Comment by yunsiechung** [comment]
It seems like for this test, it doesn't even need to load database. The test initializes the RMG object because the constant species indices are stored as the reactor attributes in the initialize(). 
`#chatelak: store constant SPC indices in the reactor attributes if any constant SPC provided in the input file
#advantages to write it here: this is run only once (as species indexes does not change over the generation)
            if self.solvent is not None:
                for index, reactionSystem in enumerate(self.reactionSystems):
                    if reactionSystem.constSPCNames is not None: #if no constant species provided do nothing
                        reactionSystem.get_constSPCIndices(self.reactionModel.core.species)  ##call the function to identify indices in the solver `

But the lines above are also written under this test, which seem redundant to me. 

I'm not familiar with initialize(), so I'm not sure how to specify the options to avoid the database loading.

**Comment by mliu49** [comment]
Oh, that's interesting. It seems that the duplicated code is the part that's supposed to be tested, so this test will always pass, even if `initialize()` were to be broken.

I'll make a fix, including not loading the database. It would be great if you could review it.

**Comment by yunsiechung** [comment]
Thank you. 
Connie suggested moving/modifying the code around so that the constant spc loading would be done inside `rmgpy.input.py`  , but I encountered some problems with that. 

It would be better if you could fix it for now as you said and I will review it. I would try to rearrange / modify the code for efficiency in the future.
