### ISSUE TITLE
H Abstraction and Disproportionation Families Misidentifying Phenyl Radical

### ISSUE THREAD

**Issue by zjburas** [ReactionMechanismGenerator/RMG-Py#829]
If you run either RMG or generatereactions with only phenyl and propene as reactants, you get the following incorrect reactions (along with the expected reactions) from the H Abstraction and Disproporionation families, respectively:

![image](https://cloud.githubusercontent.com/assets/12465817/20653558/5293c476-b4dd-11e6-88a4-e09ee64be77f.png)

Matched Tempate: [Cd/H/NonDeC;C_rad/H/CdCd]

![image](https://cloud.githubusercontent.com/assets/12465817/20653574/8a00cdfa-b4dd-11e6-9c7e-5304682ffd42.png)

Matched Template: [C_rad/H/TwoDe;Cd_Cdrad]

It seems based on the matched templates that somehow the phenyl radical is being misidentified.

**Comment by mliu49** [comment]
I think this is a resonance issue. RMG does not recognize which orbital a radical is in, so it will make a resonance structure by shifting the radical with one of the double bonds in the aromatic ring, even though that does not actually happen. This is fixed in #823, such that these kinds of radicals are no longer delocalized.

**Comment by zjburas** [comment]
@mliu49 , yes, your new resonance branch in #823 fixes this problem. The nonsensical reactions above no longer appear. Thanks.
