### ISSUE TITLE
merging documentation

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-Py#840]
It seems like RMG has multiple places where different pieces of documentation are kept: 

1. The [wiki page](https://github.com/ReactionMechanismGenerator/RMG-Py/wiki) on Github
1. The [RMG User Guide](http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/index.html)
1. The [RMG Theory Guide](http://reactionmechanismgenerator.github.io/RMG-Py/theory/index.html)

Philosophically, I can understand the difference between the User and Theory Guides. In reality, a lot of theory about algorithms seem intermingled in the User Guide. Some examples: [thermo](http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/thermo.html#symmetry-and-chirality), [kinetics](http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/kinetics.html), [diffusion limited kinetics](http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/liquids.html#diffusion-limited-kinetics). The theory guide itself seems sort of sparse with only 

I think the wiki page contains mostly notes to help developers, though it also contains some user guides: [reduction](https://github.com/ReactionMechanismGenerator/RMG-Py/wiki/Reaction-centered-reduction-of-RMG-generated-kinetic-models) and [reaction family addition](https://github.com/ReactionMechanismGenerator/RMG-Py/wiki/Adding-reaction-families). 

My preference would be to have one repository, though having clear separation is also preferable. If anyone has any preferences, feel free to share. I might try to merge the theory into the user guide, and I'd appreciate other ideas for improvement.

**Comment by rwest** [comment]
Although this is contrary to your aim of reducing the number of documentation sources, there also used to be, and perhaps ought to be, a "Developers Guide", giving an overview, introduction, tips like what classes are where, why we have two Species classes, what's the difference between a Molecule and a Species, etc. That type of thing. Things that *users* don't need to know, but new developers do, and can't currently get by reading anything.  Something to consider.  This could be in the wiki.  I think the wiki should also contain things like how to package a release, how to configure Travis regression tests, how to republish the documentation.

I think probably the chunks of theory could be appendices to the user guide. At least should be well linked from the user guide. I wouldn't want to force people to read the theory in order to find the spelling of a command or the choices available for an option, for example, but should be available to anyone reading the user guide.

**Comment by goldmanm** [comment]
I like your idea of a developer's guide. I drafted up a beginning in the [github wiki](https://github.com/ReactionMechanismGenerator/RMG-Py/wiki/code-organization). 

It seems like much of the theory about a topic appears below user guide information already. It would make sense for it to be in the back of the same repository so the guide can reference the theory. 

Once the user guide info from the wiki get merged into the master branch, I can remove it from the wiki.

**Comment by goldmanm** [comment]
I wanted to make it easier for people to edit the documentation, so I wrote a brief description of how to edit it from github.com (in the wiki). Benefits: no local setup needed, Risks: the user can't see what their changes look like.

Here is a blurb I wrote in editing the documentation in the wiki:

### Changing documentation from github.com

This is the easiest method of modifying the code, though you won't be able to see how your changes look on the website.

If you have github pushing permissions, you can easily edit [the documentation](https://github.com/ReactionMechanismGenerator/RMG-Py/tree/documentation/documentation/source/users) and commit it on the `documentation` branch from your web browser. When you are ready to publish, you can create a pull request to the master branch (which will be sent to the `gh-pages` branch for website update).
