### ISSUE TITLE
RMG quantity objects return unexpected results when compared

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-Py#903]
RMG quantity objects (at least ScalarQuantity specifically) don't compare values to each other or have valid addition/subtraction operations. A simple example:

```
from rmgpy.quantity import ScalarQuantity
ScalarQuantity(1.,'s') > ScalarQuantity(0.5,'s')
```

Intuitively, we would expect the comparison to always be True, since 1 second is more than 0.5 seconds. However, RMG currently returns either True or False for this depending on other attributes of the object (like memory location, etc.).

**Comment by goldmanm** [comment]
For me, this issue leads to less robust programming. For example, I currently compare `quantity.value > 1`, which may cause an issue if later the the quantity classes were modified to store time values in milliseconds instead of seconds (where 0.5 seconds would then return true, since it is stored as 500).

**Comment by KEHANG** [comment]
I guess using `quantity.value_si > 1` for comparison is recomended.

**Comment by rwest** [comment]
The workaround for current implementation is to always compare the .value_si attributes, but I think a modification to the class so that just comparing the objects does this for you (and checks the dimensions are the same!) would reduce chances of people making mistakes. It's not unreasonable to expect "a > b" to work! (So I'm not sure this should have been closed yet)
