### ISSUE TITLE
Current KlippenstienH2O2 library does not account for different main bath gases

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#917]
The `H + O2 (+M) = HO2 (+M)` reaction in the KlippensteinH2O2 kinetic library has different kinetics (which don't simply differ by a constant that could be compensated by using a collider efficiency) depending if the main bath gas is N2 or Ar/He.
However, in RMG we don't end up modifying this library for the different bath gases. One possible solution is to duplicating this library into two: `KlippensteinH2O2inN2` and `KlippensteinH2O2inArHe`.
The two new libraries will be identical except for the kinetics of the `H + O2 (+M) = HO2 (+M)` reaction.

A side issue (yet related) in the implementation of this library is that the `H2 <=> H + H` reaction has collider efficiencies of zero for He and Ar, while the kinetics for `H2 + Ar = H + H + Ar` and `H2+He = H+H+He` are commented-out. They should be an active part of the library.

**Comment by rwest** [comment]
A note on the second side issue,
Note that this model came in via the RMG-Java project and was added in 2011 in commits
https://github.com/ReactionMechanismGenerator/RMG-Java/commit/b69ae33c0059e76a69d257e81d4cd3a57b548457
and 
https://github.com/ReactionMechanismGenerator/RMG-Java/commit/fb9b677293b3351b823a470439bfe8a5ff035233
Because RMG-Java at that time did not treat Ar and He as real species, these reactions were commented out:
```
//! Tsang and Hampson, J. Phys. Chem. Ref. Data, 15:1087 (1986) 
//H2+AR = H+H+AR                              	5.840E+18 -1.10  1.0438E+05
//H2+HE = H+H+HE                              	5.840E+18 -1.10  1.0438E+05
//! Tsang and Hampson, J. Phys. Chem. Ref. Data, 15:1087 (1986) 
//O+O+AR = O2+AR                              	1.886E+13  0.00 -1.788E+03
//O+O+HE = O2+HE                              	1.886E+13  0.00 -1.788E+03
```
You are right - they should not be excluded!

**Comment by alongd** [comment]
Shall we simplify the names to `H2inN2` and `H2inArHe`?

**Comment by rwest** [comment]
Or switch to Burke.... Who now has a name for himself and isn't "just" a postdoc. 
Depends if people will also want other choices in future (eg Turanyi)

**Comment by alongd** [comment]
Closed with https://github.com/ReactionMechanismGenerator/RMG-database/pull/168
