### ISSUE TITLE
liquid reactor with no solvent

### ISSUE THREAD

**Issue by dyu2017** [ReactionMechanismGenerator/RMG-Py#930]
Can I run liquid reactor simulation with no solvent?
I only have one species in the system. And the species is not in the solvent list.

**Comment by bslakman** [comment]
Unfortunately we do not support solvents that are not in the solvent list (I think this is right, @yunsiechung even if it can be found in CoolProp?)

**Comment by yunsiechung** [comment]
To run the liquid reactor with the solvent species that is not in the solvent list, you have to add its Abraham, Mintz, and viscosity parameters in RMG-database. Otherwise, you cannot run it. @dyu2017 What solvent species are you looking at? I might be able to find some solvent parameters.

**Comment by dyu2017** [comment]
@bslakman @yunsiechung Thank you for your reply!
If you do not specify a solvent, and you only have one reactant, for example, naphthalene, is that still a liquid reaction system? or RMG treated it as a simple reactor (gas phase reaction)?

**Comment by rwest** [comment]
Your options are 
1) use the ideal gas law to calculate an artificially high pressure that will give the same density as liquid napthalene, specify that pressure, and run the simple reactor that will assume ideal gas phase but constant volume (and hence density). But it will then use ideal gas phase thermochemistry, and there will be no diffusion limits on the reaction rates (so they may be too fast). 

2) Use the liquid phase reactor with a solvent that is "similar" to napthalene as a solvent - in terms of polarity, H-bonding, etc. - so that the solvation thermochemistry is about right - and in terms of temperature-dependent viscosity so that the diffusion limits on the liquid phase reactions is about right. Perhaps I would choose toluene. 

3) Add the parameters and make your own solvent as @yunsiechung suggested. Or you could copy a "similar" solvent and modify it a bit (eg. perhaps you can fix the viscosity data, even if you can't find appropriate Mintz and Abraham parameters for your real solvent). You'll need to modify
[RMG-database/input/solvation/libraries/solvent.py](https://github.com/ReactionMechanismGenerator/RMG-database/blob/master/input/solvation/libraries/solvent.py)
The parameters are as described in http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/liquids.html
