### ISSUE TITLE
using RMG for silicon chemistry

### ISSUE THREAD

**Issue by dyu2017** [ReactionMechanismGenerator/RMG-Py#931]
Can I run RMG for molecules having silicon atoms with the most recent RMG-Py release?

**Comment by alongd** [comment]
Yes, RMG currently accepts:
H / C / N / O / Si / S
in reactive species.

**Comment by dyu2017** [comment]
@alongd awesome! Thank you.

**Comment by rwest** [comment]
Hi @dyu2017 you may want to see http://dx.doi.org/10.1021/acs.iecr.6b02402
If you run into trouble @bslakman can help you further and can outline the current limitations in terms of data, reliability, etc. 
(Also, you may want to follow the instructions to build from source - I'm not sure what's been fixed since the last binary release, although we are preparing for another one within the week...)

**Comment by bslakman** [comment]
Hi @dyu2017 , while the current RMG-Py release will accept Si atoms as input it may not have the data/chemistry that you need for a particular application. As @rwest suggested you can take a look at the work we have done for SiH4 decomposition and also see my silicon-hydride branches of the software: 
https://github.com/bslakman/RMG-Py/tree/silicon-hydrides 
and the corresponding RMG-database branch: 
https://github.com/bslakman/RMG-database/tree/silicon-hydrides

**Comment by dyu2017** [comment]
@rwest @bslakman Thanks for your reply!
I read your paper already. How difficult is it to generate data/chemistry for a particular application?
