### ISSUE TITLE
How to run RMG after a installation?

### ISSUE THREAD

**Issue by cehangir** [ReactionMechanismGenerator/RMG-Py#945]
Hi there, 

I am installing RMG using binary installation on Windows. I have followed steps for installation in 3.1.2 and have successfully completed Step 1-6. I have saved the input.py file in the Anaconda\envs\rmg_env\Scripts. 

However, when I run the the command in Step 7 in command prompt. I get the following error 
![image](https://cloud.githubusercontent.com/assets/26471170/24021914/af056ce0-0a79-11e7-8955-9f08893733df.png)

Please, correct me where I am doing the mistake.

**Comment by alongd** [comment]
Hi,

Try either running from the folder where your input file is located (using the same command you typed), or adding the path to the input file before the `input.py` part of the command (in which case, it's not a good idea to be running from the Windows system32 folder, since RMG will generate all outputs there).
It is also recommended to open a new folder for each RMG run, creating the relevant input file there, and running the command you typed from that folder.

For example, if I ran from `C:\RMG-runs\run01\`, then I'll type:
```
cd \RMG-runs\run01
activate rmg_env
python %RMGPy%\rmg.py input.py
```

Good luck

**Comment by alongd** [comment]
The error you got implies that `rmg.py` is missing from the `C:\Anaconda\evn\rmg_env\Scripts\` folder. Can you check the folder to confirm this?

**Comment by cehangir** [comment]
Just confirmed. The rmg.py file was missing due to the incomplete installation of RMG . 

Reinstalled RMG again and now everything is working fine. 

Thanks
