### ISSUE TITLE
Optional dependencies (and updating documentation of dependencies)

### ISSUE THREAD

**Issue by keceli** [ReactionMechanismGenerator/RMG-Py#958]
Cantera is not listed in the [dependencies list](http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/dependencies.html), but I get an import error when running the minimal example. 

I guess cantera import at rmgpy/rmg/main.py should be optional, and caught with try except block. The related commit is here: a0555d608f3f013b38bb3d543f

**Comment by alongd** [comment]
Hi,
Then I guess the dependencies list in the documentation isn't updated. Cantera should be part of your environment, as defined in the relevant .yml file (e.g., [windows](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/environment_windows.yml)).
Strange that you get this error. Can you try updating to the latest version (2.1.0) and re-making?

**Comment by keceli** [comment]
Thank you for a quick reply.

I got the error because I compiled form the source and manually installed the dependencies. 

Anyhow, I can get rid of it by installing Cantera, which I actually prefer to use instead of Chemkin. I'd just like to have optional dependencies rather than strict requirements whenever possible.

I think Cantera is used in RMG for the following purposes. 
1) An alternative to Chemkin for chemical kinetics modeling (post-processing)
2) Provide reactor solvers beyond RMG's native solver
3) Uncertainty analysis

May I learn if there are any other usages?

**Comment by goldmanm** [comment]
@keceli, I think you raise a good point. Dependencies that are not needed in core RMG runs may be optional, to reduce the necessary size of a minimal installation. For example, dependencies for modules only triggered when turned on, like pdep, qmtp, reduction, isotopes, pruning, centralThermoDB, surface could be made optional. In doing this, we may also want to have something like 'make minimal test' which only tests core parts of RMG (ignoring ReductionTest, GenerateReactionsTest, IsotopeTest, CentralThermoDBTest, etc.) Some of these tests, especially ReductionTest, do take a while to run as well, so it may be a useful feature as well.

Another good point it is to link the documentation to the corresponding environment file  instead of listing the depenencies also in the documentation (duplication is tough to maintain, as evidenced here).

**Comment by JacksonBurns** [comment]
Dependency list has since been updated, we have also incremented major version of RMG-Py. Closing as stale.
