### ISSUE TITLE
Representation of singlet\triplet bi-rads

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#965]
The  [N]=C=[N] bi-rad is an important species for Prompt NO models.

The ground state of [N]=C=[N] is a triplet, as expected: [↑N]=C=[↑N]
However, another state would be a **singlet bi-rad**: [↑N]=C=[↓N]
(where the different electron spins cancel each other out)

Sources: [M.C. Lin 2010](http://www.sciencedirect.com/science/article/pii/S0082078400806529), [M.C. Lin 2007](http://pubs.acs.org/doi/abs/10.1021/jp069038%2B).

We currently don't have a way to represent this difference in RMG. Surprisingly, RMG doesn't give an error for the following AdjList:
```
multiplicity 1
1 N u1 p1 c0 {2,D}
2 C u0 p0 c0 {1,D} {3,D}
3 N u1 p1 c0 {2,D}
```
which might suggest that it is possible to represent these two species uniquely. But as was pointed out by @mliu49, there's a concern that the multiplicity line could be overwritten when running RMG.

Running a test with both species in the input file resulted in the following error:
```
Traceback (most recent call last):
  File "D:\Code\RMG-Py\/rmg.py", line 156, in <module>
    rmg.execute(**kwargs)
  File "D:\Code\RMG-Py\rmgpy\rmg\main.py", line 529, in execute
    self.initialize(**kwargs)
  File "D:\Code\RMG-Py\rmgpy\rmg\main.py", line 371, in initialize
    self.loadInput(self.inputFile)
  File "D:\Code\RMG-Py\rmgpy\rmg\main.py", line 208, in loadInput
    readInputFile(path, self)
  File "D:\Code\RMG-Py\rmgpy\rmg\input.py", line 411, in readInputFile
    reactionSystem.convertInitialKeysToSpeciesObjects(speciesDict)
  File "rmgpy\solver\simple.pyx", line 117, in rmgpy.solver.simple.SimpleReactor.convertInitialKeysToSpeciesObjects (build\Release\pyrex\rmgpy\solver\simple.c:2349)
KeyError: 'NCN'
```

**Comment by mliu49** [comment]
I looked into the multiplicity checking, and it seems that we simply raise an error if the multiplicity is not valid. However, multiplicity checking for species with more than 2 unpaired electrons has not been implemented, which is probably why you were able to visualize them without any issues on the website.

See the method [here](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/molecule/adjlist.py#L103). It does consider that the radicals could be either same or opposite spin. We should probably extend the method up to 4 unpaired electrons, and perhaps raise the logging level to warning rather than debug.

**Comment by alongd** [comment]
Thanks @mliu49 .
I'll elaborate adjlist.py as you suggested to check multiplicity for more than 2 rads.

It still won't solve the birad NCN problem, I'll look at it again and try to identify the problem.
