### ISSUE TITLE
How is backward reaction calculated?

### ISSUE THREAD

**Issue by dyu2017** [ReactionMechanismGenerator/RMG-Py#967]
I noticed that in the output, for a reversible reaction, there are forward reaction rate coefficients, energy barrier, etc. How about backward reaction, how do I derive the rate for backward reaction?

**Comment by amarkpayne** [comment]
RMG calculates the rate constant for the reverse reaction from the equilibrium constant of the reaction. RMG uses the thermo properties of the species involved to calculate the equilibrium constant for the reaction, and since Keq = kfwd/krev, it calculates krev = kfwd/Keq.

**Comment by amarkpayne** [comment]
I believe this is talked about in a little more detail in the paper on RMG by Connie et al., which can be found here: http://www.sciencedirect.com/science/article/pii/S0010465516300285

**Comment by dyu2017** [comment]
Is there anyway to output the backward reaction rates also?
I found that sometimes the reaction given in the output is actually the backward reaction (not forward reaction).
Having both reaction rates will help determine which reaction is the rate-limiting step in the overall reaction network. @amarkpayne

**Comment by amarkpayne** [comment]
Are you looking at these rates in the chem.inp file, or are you looking at them with the mechanism analyzer script?

**Comment by mliu49** [comment]
You can use the [Plot Kinetics](http://rmg.mit.edu/tools/plot_kinetics) tool on the website to calculate and visualize reverse rate coefficients. It requires a chemkin file with thermo and kinetics data, and you can optionally provide a species dictionary to get molecule drawings as well.

I would not recommend putting your entire RMG model into the tool. Instead, choose only the reactions that you're interested in. Otherwise, it will take a long time to process, and the graphs will not be useful, since the tool plots all the rates you submitted onto the same graph.

**Comment by dyu2017** [comment]
@amarkpayne I am looking at chem.inp file

**Comment by dyu2017** [comment]
@mliu49 Is there an offline tool I can use for the same purpose?

**Comment by mliu49** [comment]
There's a work-in-progress script [here](https://github.com/ReactionMechanismGenerator/Work-In-Progress_scripts/blob/master/misc/getReverseRxnFromNasa.py) that you can try to modify for your purposes.
