### ISSUE TITLE
charged species and invalid adjacencylist

### ISSUE THREAD

**Issue by dyu2017** [ReactionMechanismGenerator/RMG-Py#976]
During simulation, I got the following species and its structures.
The structures looks very weird and it seems that the O atom is charged.
Is this correct output? Does RMG generate charged species?

[CH]1C=CC=CC1(Oc1ccccc1)c1ccccc1
![ch 1c cc cc1 oc1ccccc1 c1c cc cc 1 86](https://cloud.githubusercontent.com/assets/26123070/24470423/e31b073e-148c-11e7-9a15-f7891da701db.png)

When I look at the aadjacency list, it has O charge at 4+
S(86)
multiplicity 2
1  C u0 p0 c0 {2,S} {3,S} {4,S} {19,S}
2  C u0 p0 c0 {1,S} {6,B} {7,B}
3  C u0 p0 c0 {1,S} {8,D} {20,S}
4  C u1 p0 c0 {1,S} {9,S} {21,S}
5  C u0 p0 c0 {10,B} {11,B} {19,S}
6  C u0 p0 c0 {2,B} {13,B} {22,S}
7  C u0 p0 c0 {2,B} {14,B} {23,S}
8  C u0 p0 c0 {3,D} {12,S} {24,S}
9  C u0 p0 c0 {4,S} {12,D} {25,S}
10 C u0 p0 c0 {5,B} {15,B} {26,S}
11 C u0 p0 c0 {5,B} {16,B} {27,S}
12 C u0 p0 c0 {8,S} {9,D} {28,S}
13 C u0 p0 c0 {6,B} {17,B} {29,S}
14 C u0 p0 c0 {7,B} {17,B} {30,S}
15 C u0 p0 c0 {10,B} {18,B} {31,S}
16 C u0 p0 c0 {11,B} {18,B} {32,S}
17 C u0 p0 c0 {13,B} {14,B} {33,S}
18 C u0 p0 c0 {15,B} {16,B} {34,S}
19 O u0 p0 c+4 {1,S} {5,S}
20 H u0 p0 c0 {3,S}
21 H u0 p0 c0 {4,S}
22 H u0 p0 c0 {6,S}
23 H u0 p0 c0 {7,S}
24 H u0 p0 c0 {8,S}
25 H u0 p0 c0 {9,S}
26 H u0 p0 c0 {10,S}
27 H u0 p0 c0 {11,S}
28 H u0 p0 c0 {12,S}
29 H u0 p0 c0 {13,S}
30 H u0 p0 c0 {14,S}
31 H u0 p0 c0 {15,S}
32 H u0 p0 c0 {16,S}
33 H u0 p0 c0 {17,S}
34 H u0 p0 c0 {18,S}

**Comment by mliu49** [comment]
I think the charge is due to a bug in how we generate kekule structures right now. We use RDKit for kekulization, and during the conversion from an RMG molecule to an RDKit molecule, lone pair information is lost. This has apparently not been encountered much until recently, but it's definitely a serious issue.

I've created a new kekulization algorithm which circumvents the issue, which you can check out if you're interested. There's an open pull request for those changes in #968.

An actual fix would be to account for lone pairs during the conversion to RDKit Mol. I've only looked into it briefly, but I couldn't figure out how RDKit stores lone pairs, which might be why we don't handle it accurately.

**Comment by dyu2017** [comment]
Thanks. How do I check this out and apply in my code?

**Comment by dyu2017** [comment]
Should I do 
git cherry-pick 16655aa? Which directory? RMG-Py or RMG-database?

**Comment by mliu49** [comment]
You would need to cherry-pick d7c2a695c3e499adad7b2b356b8dc8ca6e16b39b and 545fb2eb6ef325ce7b09c46011a4492aeeae3591 to your RMG-Py installation.

**Comment by dyu2017** [comment]
It told me it is bad revision when I do "git cherry-pick d7c2a69'
fatal: bad revision 'd7c2a69'
The same for 545fb2e

**Comment by mliu49** [comment]
You might need to do `git fetch` first in order to retrieve these commits from Github.

**Comment by dyu2017** [comment]
Thanks! The first one worked after git fetch
The second one need do commit, how can I do it?
git cherry-pick 545fb2e
error: Your local changes to the following files would be overwritten by merge:
        rmgpy/molecule/resonance.py
Please, commit your changes or stash them before you can merge.
Aborting

**Comment by dyu2017** [comment]
it worked after delete resonance.py.
Thanks!

**Comment by dyu2017** [comment]
Has this issue been fixed?

**Comment by mliu49** [comment]
Yes, the new kekulization algorithm has been pulled into the master branch (#968), so this should be fixed now.

**Comment by dyu2017** [comment]
Thanks @mliu49 
Is this a temporary fix or a permanent fix (solving the RDKit problem)?
Also, what about clar structure generation? Has it been fixed?

**Comment by mliu49** [comment]
This fixes the particular issue you encountered by no longer using RDKit for resonance structure generation. The conversion from RMG to RDKit still does not explicitly account for lone pairs, but so far, that has not appeared to be a major issue for the other functions which use the conversion.

A number of fixes and improved error handling for Clar structure generation were pulled into master in #974. If you encounter the same errors, a more helpful error message should be printed. If it is still not working for you, please post another issue. It is also somewhat easier to disable Clar structure generation now, if you need to. Simply set the default value for the `clarStructures` flag to false [here](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/molecule/resonance.py#L129).

**Comment by dyu2017** [comment]
@mliu49 Thanks again for your help.
Using the recent updated RMG., it seems that those charged structures are no longer there.
But I got the following kind of new reactions in the reaction network generated. Is this a bug or something else? 

![picture1](https://cloud.githubusercontent.com/assets/26123070/26203485/743afb64-3ba9-11e7-92b6-acab2922d4aa.png)

**Comment by mliu49** [comment]
This does not appear to be a bug. The radical on the oxygen can delocalize into the aromatic ring, and a normal radical recombination reaction can occur to give that product.

**Comment by dyu2017** [comment]
But I don't quite understand why the reaction rate (7.6 at 500K) is much faster than the reaction (6.7 at 500K) to form regular 
diphenyl oxide (see below). Is there something wrong with the rate rule estimate? 


T/[K]
500 1000 1500 2000 

log10(k/[mole,m,s]) 
+7.6 +7.5 +7.5 +7.5 
Arrhenius(A=(1.33198e+08,'m^3/(mol*s)'), n=-0.196065, Ea=(0.0534622,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [C_rad/H/TwoDe;Y_rad] for rate rule [C_rad/H/TwoDe;Cb_rad]""") 
  

Reaction form DPO
T/[K]
500 1000 1500 2000 
log10(k/[mole,m,s]) 
+6.7 +6.7 +6.7 +6.7 
Arrhenius(A=(5.18377e+06,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Y_rad;O_sec_rad] for rate rule [Cb_rad;O_rad/OneDe]""")

**Comment by dyu2017** [comment]
It is also weird that it estimates using a C_rad/H/TwoDe instead of O_rad

**Comment by mliu49** [comment]
Although these rate estimates do seem odd, it's not unexpected behavior. The first rate is estimated using `C_rad/H/TwoDe` because it's using the resonance structure where the radical is delocalized to the ortho position on the ring, which means that it's now a carbon radical. The difference in rates is a result of the data which RMG has on reaction rates for carbon vs oxygen radicals. You can also tell that RMG does not have data for phenyl radicals because it used `Y_rad` to estimate `Cb_rad`.

In reality, you would expect that the ortho carbon has much lower radical character than the oxygen, which would reduce the rate for recombination at the carbon. However, RMG is not capable of handling unequal resonance contributors, so it assumes that they're all equivalent.

The best solution for you would be to add better data, either by creating a kinetics library or adding training reactions to the R_Recombination family.

**Comment by dyu2017** [comment]
Is it possible not to consider these types of resonance structures, where radical is delocalized to the carbon on aromatic ring? These radicals not only generate reactions in R_Recombination family, but also in R_addition_MultipleBond family. It is painful to take these reaction out from chemkin file manually.
Before the RMG update to fix the kelulization problem, I do not have these resonance radicals and their reactions in my reaction network, and the overall reaction kinetics for this system before the update was much better than right now.

**Comment by mliu49** [comment]
You would need to modify the resonance structure generation algorithm to not delocalize radicals into aromatic rings. The changes to kekulization would not have affected this, since RMG has always done this with radicals. We do this in order to consider all of the possible reactions which can occur.

I'm surprised that you did not see these delocalized radicals in your model before, since none of the recent changes should have significantly affected their treatment in RMG. I'm also curious about your claim that the reaction kinetics were better previously. Do you mean that your overall model matched your data better, or did you notice particular rate constants that are now wrong?

Either way, if you found significant issues with RMG's kinetics predictions, it would be great if you could make a separate issue documenting the system you're trying to model and the particular rates which you find to be wrong. RMG is by no means perfect, and many people are consistently working to make improvements. Since this is an open source project, you are also more than welcome to contribute.

**Comment by dyu2017** [comment]
Can you comment specifically which part of the code I should modify to not delocalize radicals into aromatic rings? That would help me greatly.
Since we do not have the right kinetics for those reactions, I would rather they do not stay in the system.

The previous overall model (without those delocalized radicals and their corresponding reactions) did match my data better. But many factors could affect the final results.

**Comment by mliu49** [comment]
In `generateResonanceStructures` [here](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/molecule/resonance.py#L170), you could remove any instances where we call `generateAdjacentResonanceStructures` for aromatics. Please note that this would stop all electron delocalization and is very likely to have unintended consequences.
