### ISSUE TITLE
the role of training reactions

### ISSUE THREAD

**Issue by dyu2017** [ReactionMechanismGenerator/RMG-Py#990]
I am confused with the  following two statements (a, b) in RMG documentation regarding training reactions.
If a reaction is exactly the same as one training reaction, is the rate in the training reaction used or not?
If we have kineticsDepositories = ['training'] in the input file, will the rate rules for the particular family change because of the training reactions? 
What is the role of NIST in those families? Can I add that in the kineticsDepositories to influence the rate rules?

(a) When determining the kinetics for a reaction, a match for the template is searched for in the kinetic database. The three cases in order of decreasing reliability are:
1.Reaction match from training set
2.Node template exact match using either training set or rules
3.Node template estimate averaged from children nodes

(b)Currently, RMG’s rate rule estimates overrides all kinetics depository kinetics, including training reactions. Unless the training reaction’s rate rule ranks higher than the existing node, it will not be used. If you want the training reaction to override the rate rule estimates, you should put the reaction into a reaction library or seed mechanism.

**Comment by nyee** [comment]
Can you point out where statement b is from? I'm pretty sure it is out of date. 

Training reactions are always used if the species exactly match. Rate rules have a rank of 3 by default. A training reaction can replace a rate rule if it has a higher rank (1 or 2). This can have a down-stream effect on averages that use these rules. 

Even if you don't put in `kineticsDepositories = ['training']`, training reactions will still be used by default. You can put `kineticsDepositories = ['!training']` to specifically request ignoring training reactions, but I don't recommend this. Each training reaction was added by a member of the RMG team, so at the time they thought the parameters were accurate and worth using. 

Other depositories (like NIST) will not change rate rules, but will be used if they match species exactly. Essentially they will act as a library. Be warned that while the training depository has been curated by members of the team, the NIST depository was automatically data-mined. Therefore, it is much less likely that the NIST depository is error-free, which is why we do not use it by default.

**Comment by mjohnson541** [comment]
I would recommend:  https://github.com/ReactionMechanismGenerator/RMG-Py/wiki/kinetics-estimation for kinetics estimation information as I updated it recently.

**Comment by dyu2017** [comment]
@nyee I saw the statement b from 
http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/database/modification.html#kinetic-training-set
under section 
12.4.2.7. Adding Training Reactions
