### ISSUE TITLE
git head updated to a new verion

### ISSUE THREAD

**Issue by dyu2017** [ReactionMechanismGenerator/RMG-Py#999]
I have a few questions regarding to git pull; git fetch.
(1) Does git pull automatically update my RMG-Py?
I just found out that my RMG-Py head is updated to April 17 version from March 30 version.
(2) How can I get back to my March 30 version?
(3) If I want to update, should I update both RMG-Py and RMG-database?

**Comment by rwest** [comment]
1) Mostly. Any files that are compiled via cython will need to be recompiled by typing `make`, or (sometimes more robust but always slower) `make clean; make`.  But if the only changes are to files that are "pure Python" and not including cython code, then the `git pull` is all you need.

2) If you still have your terminal open from when you did the `git pull` then look for a line something like `Updating 35d85d2f1..9d89e0265` which tells you the hash of the commit you were on before the pull (in my example, `35d85d2f1`). Otherwise type `git log` or visit https://github.com/ReactionMechanismGenerator/RMG-Py/commits/master to identify the commit you want to go back to.  Eg on March 30 was d5ceace4230f4990e0933906f5d9103c47d4b861.   Copy the commit hash, eg `d5ceac`.  Then in your terminal type `git reset --hard d5ceac` then `make` (or `make clean; make`).

3) Usually it is best to keep both up to date, and you must do so separately, so in general yes: update both. Many changes do not effect each other though, so it is not always required to keep them in sync. 

I suggest you learn more about using git from one of the many great online resources. One option is http://try.github.io/ but more are listed at https://help.github.com/articles/git-and-github-learning-resources/

**Comment by rwest** [comment]
Also note that near the top of your RMG.log file there should/might be an indication of the commit you were on when you ran that job (for both the RMG-Py and RMG-database), which will help you "go back in time" and reproduce it.  eg.

```
The current git HEAD for RMG-Py is:
	275f62ccd35985ef753e29727f81a26a923d25a7
	Wed Apr 5 20:38:25 2017 -0400

The current git HEAD for RMG-database is:
	011052af8dc182089675be06ee03bfb41ed6e3f9
	Wed Apr 5 10:14:30 2017 -0400
```

**Comment by dyu2017** [comment]
@rwest Thanks a lot! That helps.
I thought sticking with one-working version is fine with me right now.
